import { httpClient } from '@wix/essentials';
import { authentication } from '@wix/site-members';
import { location } from '@wix/site-location';

const apiOrigin = new URL(import.meta.url).origin;
const endpoint = `${apiOrigin}/api/public-listings/saved`;
type SavedItem = { id: string; savedPropertyId: string; savedAt: string; available: boolean; property?: { title?: string; city?: string; price?: number; currency?: string; primaryImage?: string; gallery?: Array<{ url?: string }> } };
type Page = { items: SavedItem[]; nextCursor: string | null; hasNext: boolean };

const css = `#saved-properties-root{font-family:system-ui,-apple-system,sans-serif}#saved-properties-launcher{position:fixed;right:22px;bottom:22px;z-index:2147483000;width:52px;height:52px;border:0;border-radius:50%;background:#17211b;color:#fff;box-shadow:0 10px 30px #0003;cursor:pointer}#saved-properties-launcher svg{width:22px}#saved-properties-badge{position:absolute;right:-2px;top:-2px;min-width:20px;height:20px;padding:0 5px;border-radius:10px;background:#e35d6a;color:#fff;font:700 11px/20px system-ui;text-align:center}.saved-properties-backdrop{position:fixed;inset:0;z-index:2147483001;background:#10201855}.saved-properties-drawer{position:fixed;top:0;right:0;bottom:0;z-index:2147483002;width:min(430px,100vw);display:flex;flex-direction:column;background:#fff;color:#17211b;box-shadow:-12px 0 40px #0002}.saved-properties-header{display:flex;align-items:center;justify-content:space-between;padding:24px;border-bottom:1px solid #e7ebe8}.saved-properties-header h2{margin:0;font-size:22px}.saved-properties-close,.saved-properties-remove{border:0;background:transparent;cursor:pointer;color:#52615a}.saved-properties-content{overflow:auto;flex:1;padding:14px 20px}.saved-properties-card{display:grid;grid-template-columns:82px 1fr auto;gap:12px;padding:14px 0;border-bottom:1px solid #edf0ee}.saved-properties-card img{width:82px;height:68px;object-fit:cover;border-radius:10px;background:#edf0ee}.saved-properties-card h3{margin:0 0 4px;font-size:15px}.saved-properties-card p{margin:2px 0;color:#64736b;font-size:12px}.saved-properties-view{display:inline-block;margin-top:7px;border:0;background:transparent;color:#356b4d;font:700 12px system-ui;cursor:pointer}.saved-properties-unavailable{color:#aa5a35;font-size:12px;font-weight:700}.saved-properties-empty,.saved-properties-error{padding:50px 8px;color:#64736b;text-align:center}.saved-properties-loading{text-align:center;color:#64736b;padding:18px}.saved-properties-toast-host{position:fixed;right:20px;bottom:86px;z-index:2147483647;display:grid;gap:10px}.saved-properties-toast{padding:13px 16px;border:1px solid #dfe7e2;border-radius:14px;background:#fff;color:#17211b;box-shadow:0 14px 35px #17211b26;font:600 13px system-ui;animation:saved-properties-toast-in .2s ease-out}.saved-properties-toast--error{border-left:4px solid #c94b4b}.saved-properties-toast--success{border-left:4px solid #2f8f5b}@keyframes saved-properties-toast-in{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}@media(max-width:600px){.saved-properties-drawer{top:auto;height:min(82vh,100dvh);width:100%;border-radius:20px 20px 0 0}.saved-properties-backdrop{background:#10201866}#saved-properties-launcher{right:12px;bottom:12px}.saved-properties-header{padding:16px 18px}.saved-properties-content{padding:10px 16px}.saved-properties-card{grid-template-columns:64px minmax(0,1fr) auto;gap:8px}.saved-properties-card img{width:64px;height:54px}.saved-properties-card h3{overflow-wrap:anywhere}}`;

function icon(name: 'bookmark' | 'x' | 'trash'): string { const paths = { bookmark: '<path d="M6 3h12v18l-6-3-6 3z"/>', x: '<path d="M6 6l12 12M18 6L6 18"/>', trash: '<path d="M4 7h16M10 11v6M14 11v6M6 7l1 13h10l1-13M9 7V4h6v3"/>' }; return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]}</svg>`; }
function post(body: Record<string, unknown>): Promise<Response> { return httpClient.fetchWithAuth(endpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); }
function showToast(message: string, tone: 'success' | 'error' = 'success'): void { const host = document.getElementById('saved-properties-toast-host') ?? document.body.appendChild(Object.assign(document.createElement('div'), { id: 'saved-properties-toast-host', className: 'saved-properties-toast-host', role: 'status', ariaLive: 'polite' })); const node = document.createElement('div'); node.className = `saved-properties-toast saved-properties-toast--${tone}`; node.textContent = message; host.append(node); window.setTimeout(() => node.remove(), 4500); }

async function initialize(): Promise<void> {
  const root = document.createElement('div'); root.id = 'saved-properties-root'; root.innerHTML = `<style>${css}</style><button id="saved-properties-launcher" aria-label="Open saved properties">${icon('bookmark')}<span id="saved-properties-badge" hidden>0</span></button>`; document.body.append(root);
  const launcher = root.querySelector<HTMLButtonElement>('#saved-properties-launcher'); const badge = root.querySelector<HTMLSpanElement>('#saved-properties-badge'); if (!launcher || !badge) return;
  let drawer: HTMLDivElement | null = null; let cursor: string | null = null; let loading = false; let items: SavedItem[] = [];
  const renderItems = () => { const content = drawer?.querySelector<HTMLDivElement>('.saved-properties-content'); if (!content) return; content.innerHTML = items.length ? items.map((item) => { const p = item.property; const image = p?.primaryImage ?? p?.gallery?.[0]?.url ?? ''; return `<article class="saved-properties-card"><img src="${image}" alt="${p?.title ?? 'Property'}" /><div><h3>${p?.title ?? 'Property unavailable'}</h3><p>${p?.city ?? ''}</p><p>${p?.price !== undefined ? new Intl.NumberFormat(undefined,{style:'currency',currency:p.currency ?? 'USD',maximumFractionDigits:0}).format(p.price) : ''}</p>${item.available ? `<button class="saved-properties-view" data-view-id="${item.id}">View property</button>` : '<span class="saved-properties-unavailable">Unavailable</span>'}</div><button class="saved-properties-remove" data-id="${item.id}" aria-label="Remove property">${icon('trash')}</button></article>`; }).join('') : '<div class="saved-properties-empty">You have not saved any properties yet.</div>'; content.querySelectorAll<HTMLButtonElement>('.saved-properties-remove').forEach((button) => button.onclick = () => void remove(button.dataset.id ?? '')); content.querySelectorAll<HTMLButtonElement>('.saved-properties-view').forEach((button) => button.onclick = async () => { const baseUrl = await location.baseUrl(); const cleanBaseUrl = baseUrl.endsWith('/') ? baseUrl.slice(0, -1) : baseUrl; await location.to(`${cleanBaseUrl}/property-details/?id=${encodeURIComponent(button.dataset.viewId ?? '')}`); }); };
  const load = async (append = false) => { if (loading || (append && !cursor)) return; loading = true; const content = drawer?.querySelector<HTMLDivElement>('.saved-properties-content'); if (!append && content) content.innerHTML = '<div class="saved-properties-loading">Loading saved properties…</div>'; try { let response = await post({ action: 'list', cursor, limit: 12 }); if (response.status === 401) { await authentication.promptLogin(); response = await post({ action: 'list', cursor, limit: 12 }); } if (!response.ok) throw new Error('Unable to load saved properties.'); const page = await response.json() as Page; items = append ? [...items, ...page.items] : page.items; cursor = page.nextCursor; badge.textContent = String(items.length); badge.hidden = items.length === 0; renderItems(); } catch (error) { if (content) content.innerHTML = `<div class="saved-properties-error">${error instanceof Error ? error.message : 'Saved properties are unavailable.'}</div>`; } finally { loading = false; } };
  const remove = async (id: string) => { if (!id || !window.confirm('Remove this property from your saved list?')) return; try { const response = await post({ action: 'remove', listingId: id }); if (!response.ok) throw new Error('Unable to remove property.'); items = items.filter((item) => item.id !== id); badge.textContent = String(items.length); badge.hidden = items.length === 0; renderItems(); showToast('Property removed.'); window.dispatchEvent(new CustomEvent('saved-properties:changed', { detail: { listingId: id, saved: false } })); } catch (error) { console.error(error); showToast('Could not remove property. Please try again.', 'error'); } };
  const close = () => { drawer?.remove(); drawer = null; document.body.style.overflow = ''; };
  const open = () => { if (drawer) return; drawer = document.createElement('div'); drawer.innerHTML = `<div class="saved-properties-backdrop"></div><aside class="saved-properties-drawer" role="dialog" aria-modal="true" aria-labelledby="saved-properties-title"><header class="saved-properties-header"><h2 id="saved-properties-title">Wish list</h2><button class="saved-properties-close" aria-label="Close wish list">${icon('x')}</button></header><div class="saved-properties-content"></div></aside>`; root.append(drawer); drawer.querySelector<HTMLButtonElement>('.saved-properties-close')?.addEventListener('click', close); drawer.querySelector<HTMLDivElement>('.saved-properties-backdrop')?.addEventListener('click', close); drawer.querySelector<HTMLDivElement>('.saved-properties-content')?.addEventListener('scroll', (event) => { const target = event.currentTarget as HTMLDivElement; if (target.scrollHeight - target.scrollTop - target.clientHeight < 240) void load(true); }); document.body.style.overflow = 'hidden'; void load(); drawer.querySelector<HTMLButtonElement>('.saved-properties-close')?.focus(); };
  launcher.onclick = open; document.addEventListener('keydown', (event) => { if (event.key === 'Escape' && drawer) close(); }); window.addEventListener('saved-properties:changed', (event) => { const detail = (event as CustomEvent<{ saved?: boolean }>).detail; showToast(detail?.saved ? 'Property saved.' : 'Property removed.'); if (drawer) { cursor = null; void load(); } });
  try { const response = await post({ action: 'list', limit: 1 }); if (response.ok) { const page = await response.json() as Page; badge.textContent = String(page.items.length); badge.hidden = page.items.length === 0; } } catch { /* Guests see the launcher and are prompted when opening it. */ }
}

if (document.readyState === 'loading') document.addEventListener('DOMContentLoaded', () => void initialize()); else void initialize();
