import { zip } from "../zip";

export const de = zip([
  "EstateAI",
  "Arbeitsbereich auflisten",
  "Übersicht",
  "Einträge",
  "AI Listing Writer",
  "Analytik",
  "Leitfaden",
  "Preise",
  "Einstellungen",
  "Angebotsanfragen",
  "Arbeitsbereich",
  "ProImmobilieninventar",
  "Content-Studio",
  "Lead-Management",
  "Portfolio-Intelligenz",
  "Erste Schritte",
  "Pläne",
  "Arbeitsbereichseinstellungen",
  "Navigation umschalten",
  "Wenden Sie sich an den App-Entwickler",
  "Prozess",
  "Wix",
  "Planen",
  "Auf der Website sind unbegrenzte Einträge sichtbar.",
  "{visible} von {cap} Einträgen sind auf der Website sichtbar.",
  "Kostenlose Testversion starten",
  "Pläne ansehen",
  "Schön dich zu sehen",
  "Ihr Immobilien-Arbeitsbereich",
  "Halten Sie Ihren Bestand organisiert, erkennen Sie Bewegungen schnell und bereiten Sie jeden Eintrag für die unterstützte Veröffentlichung vor. Neu hier? Folgen Sie dem {guide}.",
  "Arbeitsplatzführer",
  "Eintrag hinzufügen",
  "Versuchen Sie es noch einmal",
  "Wir konnten Ihre Übersicht nicht laden. Überprüfen Sie die Sammlungsberechtigungen und versuchen Sie es erneut.",
  "Gesamteinträge",
  "Überall in Ihrem Arbeitsbereich",
  "Aktiv",
  "Derzeit verfügbar",
  "Im Angebot",
  "Einen Deal abschließen",
  "Verkauft",
  "Abgeschlossene Transaktionen",
  "Aktuelle Angebote",
  "Die neuesten Eigenschaften, die Ihrem Arbeitsbereich hinzugefügt oder aktualisiert wurden.",
  "Alle anzeigen",
  "Ihr Inventar ist bereit für die Erstauflistung",
  "Fügen Sie eine Immobilie hinzu, um mit der Verfolgung Ihres Portfolios zu beginnen und Analysen freizuschalten.",
  "Offene Einträge",
  "Standort nicht festgelegt",
  "Nächster Fokus",
  "Verwandeln Sie Details in Dynamik",
  "Verwandeln Sie Ihre bestätigten Immobilieninformationen in Sekundenschnelle in professionelle, luxuriöse, kurze, SEO- oder Social-ready-Texte.",
  "Öffnen Sie AI writer",
  "Schalte AI writer frei",
  "Bestandsverwaltung",
  "Alle Einträge",
  "Suchen, organisieren und halten Sie jede Immobilie für die nächste Phase bereit.",
  "Auf der Live-Site werden die {visible} zuletzt aktualisierten aktiven Einträge Ihrer {cap}-Planobergrenze angezeigt.",
  "ProImmobilieninventar",
  "{count}-Eintrag in diesem Arbeitsbereich",
  "{count} Einträge in diesem Arbeitsbereich",
  "Titel oder Stadt suchen",
  "Einträge durchsuchen",
  "Nach Status filtern",
  "Filtern Sie nach Immobilientyp",
  "Status",
  "Property-Typ",
  "Alle Status",
  "Alle Arten",
  "Vorherige Seite",
  "Nächste Seite",
  "Seite {current} von {total}",
  "Aktionen für {title}",
  "Bearbeiten",
  "Einzigartige Besucher",
  "Löschen",
  "Wir konnten keine Einträge laden. Überprüfen Sie die Sammlungsberechtigungen und versuchen Sie es erneut.",
  "Keine Einträge entsprechen diesen Filtern.",
  "Erstellen Sie Ihren ersten Eintrag oder passen Sie die Suche und Filter an.",
  "Einträge werden geladen",
  "Alle Immobilienarten",
  "Titelbild",
  "Bild {n}",
  "Geben Sie einen Titel für diesen Eintrag ein.",
  "Verwenden Sie einen aus drei Buchstaben bestehenden Währungscode.",
  "Geben Sie einen gültigen Preis ein.",
  "Geben Sie einen gültigen Bereich ein.",
  "Wählen Sie ein Land aus.",
  "Wählen Sie ein Bundesland oder eine Region aus.",
  "Geben Sie die Stadt oder den Ort ein.",
  "Geben Sie die Straßenadresse ein.",
  "Geben Sie eine gültige E-Mail-Adresse ein.",
  "Geben Sie eine gültige Telefonnummer ein.",
  "Geben Sie eine gültige Nummer ein.",
  "Geben Sie eine ganze Zahl ein.",
  "Das Land, in dem sich die Immobilie befindet.",
  "Der Staat, die Provinz oder die Region, in der sich die Immobilie befindet.",
  "Die Einheit zur Messung der Grundstücksfläche.",
  "Länder konnten nicht geladen werden.",
  "Staaten konnten nicht geladen werden.",
  "Städte konnten nicht geladen werden.",
  "Die bisherigen Aufrufe stammen von nicht angemeldeten Besuchern, daher können einzelne Benutzer nicht aufgelistet werden.",
  "Zeitgenössisches Haus mit 3 Schlafzimmern in Austin, TX",
  "<p>Helles und geräumiges Haus mit moderner Ausstattung, hervorragendem Tageslicht und einer Garage für zwei Autos. In der Nähe von Geschäften, Restaurants und wichtigen Pendlerstrecken gelegen.</p><p>Ideal für Berufstätige oder eine wachsende Familie, die ein komfortables Zuhause in einem gut angebundenen Viertel sucht.</p>",
  "Schwimmbad, Fitnessstudio, Garage, zentrale Klimaanlage",
  "Einzigartige Besucher",
  "Personen, die „{title}“ angesehen haben, wurden jeweils einmal gezählt.",
  "Es werden einzelne Besucher geladen",
  "Eindeutige Besucher konnten nicht geladen werden. Versuchen Sie es erneut.",
  "Noch hat niemand diesen Eintrag angesehen.",
  "{count} einzigartiger Besucher",
  "{count} einzelne Besucher",
  "{count} unsignierte Ansicht",
  "{count} unsignierte Ansichten",
  "{count} Ansicht",
  "{count} Aufrufe",
  "letzte {when}",
  "Angemeldeter Besucher",
  "Diesen Eintrag löschen?",
  "„{title}“ wird aus aktiven Einträgen entfernt. Sie können es weiterhin anzeigen, wenn archivierte Einträge aktiviert sind.",
  "Abbrechen",
  "Eintrag löschen",
  "ProEigentum",
  "Typ",
  "Preis",
  "Status",
  "Ansichten",
  "Aktualisiert",
  "Aktionen",
  "Content-Studio",
  "Schreiben Sie Angebote, die auffallen",
  "Fügen Sie die Immobilienfakten einmal hinzu und lassen Sie sie von der KI in ausgefeilte Marketingtexte umwandeln. Überprüfen Sie jedes Detail, bevor Sie es veröffentlichen.",
  "AI Listing Writer ist auf Pro und Business",
  "Führen Sie ein Upgrade durch, um aus Ihren Immobiliendaten eine professionelle Auflistungskopie zu erstellen.",
  "Portfolio-Intelligenz",
  "Erweiterte Analysen",
  "Verstehen Sie Ihren Inventarmix, Ihre Aktivität und Ihre Inhaltsbereitschaft anhand der Daten, die Ihnen bereits vorliegen.",
  "Aktualisieren",
  "Analytics ist auf Pro und Business",
  "Führen Sie ein Upgrade durch, um den Bestandsmix, die Aktivität und die Inhaltsbereitschaft zu sehen.",
  "Wir konnten keine Analysen berechnen. Überprüfen Sie die Sammlungsberechtigungen und versuchen Sie es erneut.",
  "Verfolgter Bestand",
  "Einträge in der Sammlung",
  "AI-ready Inhalt",
  "Einträge mit ausgefüllten KI-Feldern",
  "Aktive Städte",
  "Die fünf beliebtesten Städte sind unten aufgeführt",
  "Aktivitätssignal",
  "Einträge, die in den letzten sechs Monaten hinzugefügt wurden",
  "Listungsaktivität",
  "Neue Datensätze, die in den letzten sechs Kalendermonaten erstellt wurden.",
  "Top-Städte",
  "Fügen Sie Standorte hinzu, um die geografische Konzentration anzuzeigen.",
  "ProPerty-Mix",
  "Inventar nach Immobilientyp gruppiert.",
  "Fügen Sie Einträge hinzu, um Ihren Immobilienmix zu sehen.",
  "Durchschnittlicher Angebotspreis",
  "Nach Währung gruppiert, um Vergleiche aussagekräftig zu halten.",
  "Fügen Sie Einträge hinzu, um Preissignale zu sehen.",
  "{count}-Eintrag",
  "{count}-Einträge",
  "Eintragsstatus",
  "Sobald Einträge hinzugefügt wurden, wird Ihre Statusaufschlüsselung angezeigt.",
  "Transaktionsmix",
  "Ihr Transaktionsmix wird angezeigt, sobald Einträge hinzugefügt wurden.",
  "Analysen werden aus der aktuellen Auflistungssammlung berechnet und bei Bedarf aktualisiert.",
  "Noch keine Eintragsdaten",
  "Aktuelle Verteilung in Ihrem Inventar.",
  "App-Pläne",
  "Wählen Sie den Plan, der zu Ihrem Inventar passt",
  "Ihre kostenlose Testversion umfasst alle Business-Funktionen. Nach dessen Ende folgen die Live-Site und die geschlossenen Tools Ihrem aktiven Plan.",
  "Beginnen Sie am Basic, um Angebote zu veröffentlichen und Angebote einzuholen. Upgraden Sie auf Pro oder Business, wenn Sie KI-Texte, 360°-Touren, Analysen und weitere Marketingtools benötigen.",
  "Aktueller Plan",
  "Kostenlose Testversion",
  "Am beliebtesten",
  "Funktionsvergleich",
  "Was ist in Basic, Pro und Business enthalten?",
  "Funktion",
  "Im Lieferumfang enthalten",
  "Nicht im Lieferumfang enthalten",
  "Basic",
  "Pro",
  "Business",
  "Kostenlos",
  "In der App enthalten",
  "pro Monat",
  "Veröffentlichen Sie eine kleine Bestandsaufnahme und sammeln Sie Anfragen auf der Website.",
  "KI-Texte, 360°-Touren, Besuchereinblicke und Portfolioanalysen.",
  "Unbegrenzte Einträge, KI-Assistent vor Ort und umfassende Marketingtools.",
  "Aktive Einträge",
  "Bis zu 10",
  "Bis 50",
  "Unbegrenzt",
  "Widgets für Einträge und Immobiliendetails",
  "Kontakt zum Eigentümer auf den Eintragsseiten",
  "Angebotsanfrageformular",
  "Gespeicherte Eigenschaften für Mitglieder",
  "AI Listing Writer",
  "360° virtueller Rundgang",
  "Einzigartige Besuchereinblicke",
  "Portfolioanalyse",
  "Social Sharing auf Eintragsseiten",
  "E-Mail-Benachrichtigungen zu Angebotsanfragen",
  "KI-Assistent für Immobilien vor Ort",
  "Verwandte Einträge auf Immobilienseiten",
  "Mehrere 360°-Tourszenen",
  "Vorrangiger Support",
  "Arbeitsbereichseinstellungen",
  "Einstellungen",
  "Legen Sie sinnvolle Standardwerte für neue Einträge fest und konzentrieren Sie sich im Arbeitsbereich auf die Datensätze, die Ihr Team aktiv verwaltet.",
  "Standardwerte auflisten",
  "Diese Einstellungen füllen neue Einträge vorab aus. Vorhandene Datensätze werden nicht verändert.",
  "Standardwährung",
  "Die für neue Angebotspreise vorausgewählte Währung.",
  "Wählen Sie aus der vollständigen ISO 4217-Währungsliste.",
  "Standardflächeneinheit",
  "Die für neue Listungsbereiche vorausgewählte Maßeinheit.",
  "Wird bei neuen Datensätzen auf das Flächenfeld angewendet.",
  "Standard-Eintragsstatus",
  "Der Workflow-Status, der neuen Angeboten zugewiesen wird.",
  "Mit dieser Workflow-Phase werden neue Angebote geöffnet.",
  "Beziehen Sie archivierte Einträge ein",
  "Wenn diese Option aktiviert ist, werden archivierte Einträge standardmäßig in der Auflistungsansicht angezeigt.",
  "Lassen Sie archivierte Datensätze standardmäßig in der Listenansicht sichtbar.",
  "Dashboard-Sprache",
  "Wählen Sie die Sprache für diesen Arbeitsbereich oder folgen Sie der Sprache des Wix-Kontos.",
  "Auto (Wix account language)",
  "Lokal für diesen Browser gespeichert",
  "Änderungen werden noch nicht gespeichert",
  "Zurücksetzen",
  "Einstellungen speichern",
  "Arbeitsbereichseinstellungen gespeichert.",
  "Die Einstellungen konnten in diesem Browser nicht gespeichert werden.",
  "Saved Properties-Launcher",
  "Betten Sie die Schaltfläche und Schublade für gespeicherte Mitgliedereigenschaften auf Ihrer Live-Site ein oder stellen Sie sie wieder her.",
  "Kann problemlos mehr als einmal ausgeführt werden.",
  "Launcher einbetten",
  "Einbetten…",
  "Der Saved Properties-Launcher ist auf der Website aktiv.",
  "Der Launcher konnte nicht eingebettet werden.",
  "Hilfe: {hint}",
  "Lead-Management",
  "Angebotsanfragen",
  "Überprüfen Sie Immobilienanfragen und halten Sie den Follow-up-Status auf dem neuesten Stand.",
  "Eingehende Anfragen",
  "{count}-Anfrage",
  "{count} Anfragen",
  "Immobilie durchsuchen",
  "Suchen Sie nach Angebotsanfragen",
  "Angebotsanfragen nach Status filtern",
  "Angebotsanfragen aktualisieren",
  "Angebotsanfragen konnten nicht geladen werden.",
  "Die Anfrage konnte nicht aktualisiert werden.",
  "Keine Angebotsanfragen entsprechen diesen Filtern.",
  "Keine Nachricht bereitgestellt.",
  "Interne Notizen",
  "Hinweise für {title}",
  "Status für {title}",
  "Archiv",
  "Seite {current}",
  "Zurück",
  "Als nächstes",
  "Neu",
  "Kontaktiert",
  "Zitiert",
  "Geschlossen",
  "Erste Schritte",
  "So verwenden Sie diesen Arbeitsbereich",
  "Erstellen Sie hier Einträge, veröffentlichen Sie sie mit den Site-Widgets und verfolgen Sie dann Angebotsanfragen und Besucheraktivitäten über dieses Dashboard.",
  "Empfohlener Weg",
  "Fügen Sie mindestens einen aktiven Eintrag hinzu, platzieren Sie die Widgets auf Ihrer Website und prüfen Sie dann die Angebotsanfragen, nachdem ein Besucher eine Anfrage gestellt hat.",
  "Schritt {n}",
  "Einträge erstellen und verwalten",
  "Bewahren Sie jede Immobilie in einem Inventar auf.",
  "Fügen Sie einen Eintrag mit Standort, Preis, Bildern und einer optionalen 360°-Tour hinzu.",
  "Der Agenten-/Eigentümerkontakt wird vom Websiteeigentümer ausgefüllt und kann pro Eintrag bearbeitet werden.",
  "Verwenden Sie das Aktionsmenü für Einträge, um einzelne Besucher zu bearbeiten, zu überprüfen oder zu löschen.",
  "Auf der Live-Site werden nur aktive Einträge angezeigt.",
  "Veröffentlichen Sie Einträge auf der Website",
  "Zeigen Sie Besuchern Inventar- und Objektdetails an.",
  "Fügen Sie das Immobilienlisten-Widget zu einer Seite wie /properties hinzu.",
  "Fügen Sie das Eigenschaftsdetail-Widget zu einer Seite wie /property-details hinzu.",
  "Aktivieren oder deaktivieren Sie im Editor „Kontakt“, „Angebotsanfrage“, „Teilen“ und zugehörige Einträge.",
  "Betten Sie den Saved Properties-Launcher in den Einstellungen ein, damit Mitglieder Häuser mit Lesezeichen versehen können.",
  "Einstellungen öffnen",
  "Bearbeitung von Besucheranfragen",
  "Ermöglichen Sie Käufern, Sie zu kontaktieren, ohne das Angebot zu verlassen.",
  "Besucher sehen den Namen, die Telefonnummer und die E-Mail-Adresse des Eigentümers auf der Immobilienseite, wenn „Kontakt“ aktiviert ist.",
  "„Ein Angebot anfordern“ erfasst Name, E-Mail-Adresse, Telefonnummer und eine formatierte Nachricht.",
  "Hier erscheinen neue Anfragen mit Status, Notizen und Archiv.",
  "Für Angebotsbenachrichtigungen werden die E-Mail-Adresse des Listing-Agenten und die E-Mail-Adresse des Websitebesitzers verwendet.",
  "Offene Angebotsanfragen",
  "Schreiben Sie eine Auflistungskopie mit KI",
  "Verwandeln Sie Fakten in marketinggerechte Beschreibungen.",
  "Öffnen Sie AI Listing Writer oder verwenden Sie „Write with AI“ im Listing-Editor.",
  "Überprüfen Sie die erstellte Kopie und speichern Sie sie vor der Veröffentlichung im Eintrag.",
  "Verwenden Sie Analytics, um zu sehen, welche Einträge die meisten Aufrufe anziehen.",
  "Brauche mehr Hilfe",
  "Standardeinstellungen und Support für den Arbeitsbereich",
  "Legen Sie in den Einstellungen die Standardwährung, Flächeneinheit und den Standardstatus fest. Wenden Sie sich über die Seitenleiste an den App-Entwickler, wenn nach der Installation ein Widget oder eine Sammlung fehlt.",
  "Eintrag hinzufügen",
  "Eintrag bearbeiten",
  "Halten Sie Ihre Immobilieninformationen korrekt und bereit für die Veröffentlichung.",
  "Dieser Eintrag kann nicht geöffnet werden",
  "Zurück zu den Einträgen",
  "Dieser Eintrag konnte nicht gefunden werden.",
  "Dieser Eintrag konnte nicht geladen werden.",
  "{title} wurde aktualisiert.",
  "{title} wurde hinzugefügt.",
  "Der Eintrag konnte nicht gespeichert werden.",
  "{title} wurde archiviert.",
  "Der Eintrag konnte nicht archiviert werden.",
  "Erstellen Sie einen neuen Eintrag",
  "Eintragsdetails bearbeiten",
  "Property Geschichte",
  "Verwenden Sie den Editor, um eine ausgefeilte, strukturierte Beschreibung hinzuzufügen.",
  "Titel",
  "Ein prägnanter Name, der diese Eigenschaft identifiziert.",
  "Lichtdurchflutetes Haus mit 3 Schlafzimmern in Austin, TX",
  "Beschreibung",
  "Beschreiben Sie die Immobilie, den Grundriss, die Ausstattung und die Verkaufsargumente.",
  "Schreiben Sie mit KI",
  "AI writer (Pro)",
  "Editor wird geladen…",
  "Adresse",
  "Geben Sie die Straße, Adresse oder den Standort der Immobilie ein.",
  "Straße oder Nachbarschaft",
  "Stadt",
  "Wählen Sie eine vorgeschlagene Stadt aus oder geben Sie eine manuell ein.",
  "Geben Sie eine Stadt ein oder wählen Sie sie aus",
  "Land",
  "Bundesland/Region",
  "Bilder auflisten",
  "Wählen Sie Bilder aus Wix Media Manager; Das erste Bild ist das Cover.",
  "Das erste Bild wird als Deckblatt für Karten und die Immobilienseite verwendet.",
  "Wählen Sie Bilder aus",
  "Bilder hinzufügen",
  "Noch keine Bilder ausgewählt.",
  "Bild entfernen {n}",
  "360° virtueller Rundgang",
  "Fügen Sie äquirechteckige 360°-Fotos für den interaktiven Three.js-Viewer hinzu. Besucher können zwischen Räumen und Aussichtspunkten wechseln.",
  " Virtuelle Touren sind auf Pro und Business enthalten; Zusätzliche Bilder bleiben im Dashboard, wenn Sie sie jetzt hinzufügen.",
  " Pro-Seiten zeigen die erste Szene; Weitere Szenen gehen auf Business live.",
  "360° Panoramabilder",
  "Wählen Sie äquirechteckige 360°-Bilder für den interaktiven Three.js-Viewer. Besucher können zwischen den Szenen wechseln.",
  "Optional. Jedes Bild sollte ein gleichwinkliges 360°-Foto sein.",
  "Keine 360°-Panoramen ausgewählt.",
  "Panorama entfernen {n}",
  "Szene {n}",
  "Fakten auflisten",
  "Diese Bereiche umfassen Leistungsfilter und Portfolioanalysen.",
  "Transaktionstyp",
  "Egal, ob die Immobilie zum Verkauf, zur Miete oder zur Verpachtung steht.",
  "Die Kategorie, die die Immobilie am besten beschreibt.",
  "Die aktuelle Workflow-Phase für dieses Angebot.",
  "Proguter Zustand",
  "Der aktuelle physische Zustand der Immobilie.",
  "Einrichtungsstatus",
  "Ob die Immobilie unmöbliert, teilmöbliert oder möbliert ist.",
  "Amtszeit",
  "Die Eigentums- oder Pachtvereinbarung für die Immobilie.",
  "Miethäufigkeit",
  "Wie oft wird Miete für Miet- oder Pachtangebote erwartet?",
  "Preis",
  "Der Listenpreis in der ausgewählten Währung.",
  "Währung",
  "Die aus drei Buchstaben bestehende Währung, die für den Listenpreis verwendet wird.",
  "Bereich",
  "Die Grundstücksgröße in der ausgewählten Flächeneinheit.",
  "Flächeneinheit",
  "Ausstattung",
  "Listen Sie bemerkenswerte Merkmale durch Kommas getrennt auf.",
  "Schwimmbad, Fitnessstudio, 24/7-Sicherheitsdienst",
  "Verfügbarkeitsdatum",
  "Das Datum, an dem die Immobilie verfügbar wird.",
  "Kontakt zum Makler/Eigentümer",
  "Name",
  "Der für diesen Eintrag verantwortliche Makler oder Eigentümer.",
  "Name des Agenten oder Eigentümers",
  "Telefon",
  "Eine Telefonnummer für Anfragen zu Einträgen.",
  "Internationale Telefonnummer",
  "E-Mail",
  "Eine E-Mail-Adresse für Angebotsanfragen.",
  "Kartenplatzierung",
  "Breitengrad",
  "Der Breitengrad der Eigenschaft, der für die Kartenplatzierung verwendet wird.",
  "Längengrad",
  "Der Längengrad der Eigenschaft, der für die Kartenplatzierung verwendet wird.",
  "Eintrag speichern",
  "Sparen…",
  "AI writer",
  "Fakten aus dieser Auflistung werden für Sie ausgefüllt. Wenn der Schreibvorgang abgeschlossen ist, wird die Beschreibung im Formular automatisch aktualisiert.",
  "Die Beschreibung des Eintrags wurde aktualisiert.",
  "Der Media Manager konnte nicht geöffnet werden.",
  "Wählen Sie {label}",
  "Optionaler {label}-Wert für diesen Eintrag.",
  "Optional",
  "Schlafzimmer",
  "Badezimmer",
  "Baujahr",
  "Parkplätze",
  "Servicegebühr",
  "Kaution",
  "Erforderlich",
  "Fügen Sie einen Titel hinzu.",
  "Fügen Sie eine Adresse hinzu.",
  "Fügen Sie eine Stadt hinzu.",
  "Fügen Sie einen Preis hinzu.",
  "Fügen Sie einen Bereich hinzu.",
  "Korrigieren Sie die hervorgehobenen Felder vor dem Speichern.",
  "Standortvorschläge konnten nicht geladen werden. Sie können weiterhin Werte eingeben.",
  "Property-Grundlagen",
  "Was soll die Beschreibung sagen?",
  "Standort",
  "Austin, Texas",
  "875.000 US-Dollar",
  "Schwimmbad, Fitnessstudio, Parkplatz",
  "Schreibstil",
  "Beschreibung erstellen",
  "Schreiben Sie Ihre Beschreibung ...",
  "Generierte Beschreibung",
  "Wenn der Schreibvorgang abgeschlossen ist, wird diese Kopie der Angebotsbeschreibung hinzugefügt.",
  "Überprüfen Sie die Kopie und kopieren Sie sie dann in Ihren Eintrag.",
  "Kopieren",
  "Kopiert",
  "Generierte Objektbeschreibung",
  "Ihre polierte Kopie erscheint hier",
  "Wählen Sie einen Stil und erstellen Sie eine Beschreibung aus den bestätigten Immobiliendaten.",
  "Proprofessionell",
  "Klar und vertrauenswürdig",
  "Luxus",
  "Erhaben und ehrgeizig",
  "Kurz",
  "Perfekt für Karten",
  "SEO-optimiert",
  "Suchfreundliche Kopie",
  "Soziale Medien",
  "Ansprechend und teilbar",
  "Möbliert",
  "Teilmöbliert",
  "Unmöbliert",
  "Die Beschreibung konnte nicht generiert werden.",
  "AI Listing Writer ist für Pro und Business verfügbar.",
  "Geben Sie Ihre Kopie Ihres Eintrags weiter",
  "Erreichen Sie Käufer überall dort, wo sie Zeit verbringen.",
  "Kanäle hinzufügen",
  "Weitere Sharing-Kanäle",
  "Wählen Sie eine Plattform, um die generierte Eintragskopie zu teilen. Einige Kanäle kopieren zuerst die Bildunterschrift, sodass Sie Fotos hinzufügen und auf natürliche Weise veröffentlichen können.",
  "WhatsApp",
  "An einen Kontakt oder eine Gruppe senden",
  "Facebook",
  "Teilen Sie es in Ihrem Feed",
  "Instagram",
  "Bildunterschrift kopieren und Instagram öffnen",
  "X",
  "Posten Sie es auf Ihrer Chronik",
  "LinkedIn",
  "Teilen Sie es mit Ihrem Netzwerk",
  "Telegram",
  "An einen Chat oder Kanal senden",
  "Pinterest",
  "Bildunterschrift kopieren und Pinterest öffnen",
  "Reddit",
  "An eine Community senden",
  "Threads",
  "Bildunterschrift kopieren und Threads öffnen",
  "TikTok",
  "Bildunterschrift kopieren und TikTok öffnen",
  "YouTube",
  "Bildunterschrift kopieren und YouTube öffnen",
  "Snapchat",
  "Bildunterschrift kopieren und Snapchat öffnen",
  "E-Mail",
  "Öffnen Sie Ihre E-Mail-App",
  "Textnachricht",
  "Als Textnachricht senden",
  "ProImmobilieneintrag",
  "Beschreibung des Eintrags",
  "Beschreiben Sie das Licht, die Aufteilung, die Ausstattung und die Gründe, warum Sie diese Immobilie lieben …",
  "Bilder konnten der Beschreibung nicht hinzugefügt werden.",
  "Videos konnten der Beschreibung nicht hinzugefügt werden.",
  "Entwurf",
  "Aktiv",
  "Im Angebot",
  "Verkauft",
  "Archiviert",
  "Zu verkaufen",
  "Zu vermieten",
  "Zu vermieten",
  "Haus",
  "Wohnung",
  "Eigentumswohnung",
  "Stadthaus",
  "Land",
  "Büro",
  "Einzelhandel",
  "Industriell",
  "Mischnutzung",
  "Andere",
  "Quadratfuß",
  "Quadratmeter",
  "Hektar",
  "Neu",
  "Gut",
  "Renovierungsbedürftig",
  "Eigentum",
  "Pacht",
  "Monatlich",
  "Jährlich",
  "Quadratmeter",
  "Hektar",
  "Neu",
  "Gut",
  "Renovierungsbedürftig",
  "Eigentum",
  "Pacht",
  "Monatlich",
  "Jährlich",
  "English",
  "中文",
  "हिन्दी",
  "Español",
  "العربية",
  "Français",
  "বাংলা",
  "Português",
  "Русский",
  "اردو",
  "Bahasa Indonesia",
  "Deutsch",
  "日本語",
  "Kiswahili",
  "Türkçe",
  "한국어",
  "Tiếng Việt",
  "Italiano",
  "ไทย",
  "Polski",
]);
