import { zip } from "../zip";

export const es = zip([
  "EstateAI",
  "Espacio de trabajo de listado",
  "Descripción general",
  "Listados",
  "AI Listing Writer",
  "Analítica",
  "Guía",
  "Precios",
  "Configuración",
  "Solicitudes de cotización",
  "Espacio de trabajo",
  "Proinventario de propiedad",
  "Estudio de contenido",
  "Gestión de clientes potenciales",
  "Inteligencia de cartera",
  "Empezando",
  "Planes",
  "Preferencias de espacio de trabajo",
  "Alternar navegación",
  "Póngase en contacto con el desarrollador de la aplicación",
  "juicio",
  "Wix",
  "Planificar",
  "Listados ilimitados son visibles en el sitio.",
  "{visible} de {cap} listados son visibles en el sitio.",
  "Iniciar prueba gratuita",
  "Ver planos",
  "bueno verte",
  "Tu espacio de trabajo inmobiliario",
  "Mantenga su inventario organizado, detecte movimientos rápidamente y prepare cada anuncio para su publicación asistida. ¿Nuevo aquí? Siga el {guide}.",
  "guía del espacio de trabajo",
  "Agregar listado",
  "Reintentar",
  "No pudimos cargar su descripción general. Verifique los permisos de la colección y vuelva a intentarlo.",
  "listados totales",
  "En todo tu espacio de trabajo",
  "Activo",
  "Actualmente disponible",
  "Bajo oferta",
  "Avanzando a través de un trato",
  "Vendido",
  "Transacciones completadas",
  "Listados recientes",
  "Las últimas propiedades agregadas o actualizadas en su espacio de trabajo.",
  "Ver todo",
  "Su inventario está listo para su primera publicación.",
  "Agregue una propiedad para comenzar a rastrear su cartera y desbloquear análisis.",
  "Listados abiertos",
  "Ubicación no establecida",
  "Siguiente enfoque",
  "Convierta los detalles en impulso",
  "Convierta los datos confirmados de su propiedad en un texto profesional, de lujo, breve, SEO o listo para redes sociales en segundos.",
  "Abierto AI writer",
  "Desbloquear AI writer",
  "Gestión de inventario",
  "Todos los listados",
  "Busque, organice y mantenga cada propiedad lista para su siguiente etapa.",
  "El sitio en vivo muestra los {visible} listados activos actualizados más recientemente de su límite de plan {cap}.",
  "Proinventario de propiedad",
  "{count} listado en este espacio de trabajo",
  "{count} listados en este espacio de trabajo",
  "Buscar título o ciudad",
  "Buscar listados",
  "Filtrar por estado",
  "Filtrar por tipo de propiedad",
  "Estado",
  "Protipo de propiedad",
  "Todos los estados",
  "Todos los tipos",
  "Pagina anterior",
  "Página siguiente",
  "Página {current} de {total}",
  "Acciones para {title}",
  "Editar",
  "Visitantes únicos",
  "Eliminar",
  "No pudimos cargar listados. Verifique los permisos de la colección y vuelva a intentarlo.",
  "Ningún listado coincide con estos filtros.",
  "Crea tu primer anuncio o ajusta la búsqueda y los filtros.",
  "Cargando listados",
  "Todo tipo de propiedad",
  "Imagen de portada",
  "Imagen {n}",
  "Ingrese un título para este listado.",
  "Utilice un código de moneda de tres letras.",
  "Introduzca un precio válido.",
  "Ingrese un área válida.",
  "Seleccione un país.",
  "Seleccione un estado o región.",
  "Ingrese la ciudad o localidad.",
  "Introduzca la dirección de la calle.",
  "Ingrese una dirección de correo electrónico válida.",
  "Ingrese un número de teléfono válido.",
  "Introduzca un número válido.",
  "Introduzca un número entero.",
  "El país donde se encuentra la propiedad.",
  "El estado, provincia o región donde se encuentra la propiedad.",
  "La unidad utilizada para medir el área de la propiedad.",
  "No se pudieron cargar los países.",
  "No se pudieron cargar los estados.",
  "No se pudieron cargar las ciudades.",
  "Las vistas hasta ahora provienen de visitantes no registrados, por lo que no se pueden enumerar usuarios únicos.",
  "Casa contemporánea de 3 dormitorios en Austin, TX",
  "<p>Casa amplia y luminosa con acabados modernos, excelente luz natural y garaje para dos autos. Ubicado cerca de tiendas, restaurantes y las principales rutas de cercanías.</p><p>Ideal para profesionales o una familia en crecimiento que busca un hogar cómodo en un vecindario bien comunicado.</p>",
  "Piscina, Gimnasio, Garaje, Aire central",
  "Visitantes únicos",
  "Las personas que vieron “{title}”, contaron una vez cada una.",
  "Cargando visitantes únicos",
  "No se pudieron cargar visitantes únicos. Intentar otra vez.",
  "Nadie ha visto este anuncio todavía.",
  "{count} visitante único",
  "{count} visitantes únicos",
  "{count} vista sin firmar",
  "{count} vistas sin firmar",
  "{count} ver",
  "{count} vistas",
  "último {when}",
  "Visitante registrado",
  "¿Eliminar este listado?",
  "\"{title}\" se eliminará de los listados activos. Aún puedes verlo cuando los listados archivados estén habilitados.",
  "Cancelar",
  "Eliminar listado",
  "Propropiedad",
  "Tipo",
  "Precio",
  "Estado",
  "Vistas",
  "Actualizado",
  "Acciones",
  "Estudio de contenido",
  "Escribe anuncios que llamen la atención",
  "Agregue los datos de la propiedad una vez y deje que la IA los convierta en un texto de marketing pulido. Revisa cada detalle antes de publicar.",
  "AI Listing Writer está en Pro y Business",
  "Actualice para generar una copia del listado profesional a partir de los datos de su propiedad.",
  "Inteligencia de cartera",
  "Análisis avanzado",
  "Comprenda la combinación de su inventario, la actividad y la preparación del contenido a partir de los datos que ya tiene.",
  "Actualizar",
  "Analytics está en Pro y Business",
  "Actualice para ver la combinación de inventario, la actividad y la preparación del contenido.",
  "No pudimos calcular la analítica. Verifique los permisos de la colección y vuelva a intentarlo.",
  "Inventario rastreado",
  "Anuncios en la colección",
  "Contenido AI-ready",
  "Listados con campos AI completos",
  "Ciudades activas",
  "Las cinco ciudades principales se muestran a continuación",
  "señal de actividad",
  "Anuncios agregados en los últimos seis meses",
  "Actividad de listado",
  "Nuevos registros creados durante los últimos seis meses calendario.",
  "Ciudades principales",
  "Agregue ubicaciones para ver la concentración geográfica.",
  "Promezcla de propiedad",
  "Inventario agrupado por tipo de propiedad.",
  "Agregue listados para ver su combinación de propiedades.",
  "Precio medio de venta",
  "Agrupados por moneda para que las comparaciones sigan siendo significativas.",
  "Agregue listados para ver señales de precios.",
  "Listado {count}",
  "{count} listados",
  "Estado del listado",
  "El desglose de su estado aparecerá una vez que se agreguen los listados.",
  "Mezcla de transacciones",
  "Su combinación de transacciones aparecerá una vez que se agreguen los listados.",
  "Los análisis se calculan a partir de la colección de listados actuales y se actualizan según demanda.",
  "Aún no hay datos de listado",
  "Distribución actual en todo su inventario.",
  "Planes de aplicaciones",
  "Elige el plan que se ajuste a tu inventario",
  "Su prueba gratuita incluye todas las funciones de Business. Una vez finalizado, el sitio en vivo y las herramientas cerradas siguen su plan activo.",
  "Comience el Basic para publicar listados y recopilar cotizaciones. Actualice a Pro o Business cuando necesite copia de IA, recorridos de 360°, análisis y más herramientas de marketing.",
  "plan actual",
  "Prueba gratuita",
  "mas popular",
  "Comparación de características",
  "Qué está incluido en Basic, Pro y Business.",
  "Característica",
  "Incluido",
  "No incluido",
  "Basic",
  "Pro",
  "Business",
  "Gratis",
  "Incluido con la aplicación",
  "por mes",
  "Publicar un pequeño inventario y recoger consultas del sitio.",
  "Copia de IA, recorridos 360°, información sobre los visitantes y análisis de cartera.",
  "Listados ilimitados, asistente de inteligencia artificial en el sitio y herramientas de marketing completas.",
  "Listados activos",
  "hasta 10",
  "hasta 50",
  "Ilimitado",
  "Listados y widgets de detalles de propiedades",
  "Contacto del propietario en las páginas del listado",
  "Formulario de solicitud de cotización",
  "Propiedades guardadas para miembros",
  "AI Listing Writer",
  "360° visita virtual",
  "Información única sobre los visitantes",
  "Análisis de cartera",
  "Compartir en redes sociales en páginas de listados",
  "Notificaciones por correo electrónico de solicitud de cotización",
  "Asistente de IA de propiedad en el sitio",
  "Anuncios relacionados en páginas de propiedades",
  "Múltiples escenas de gira de 360°",
  "Apoyo prioritario",
  "Preferencias de espacio de trabajo",
  "Configuración",
  "Establezca valores predeterminados sensatos para nuevos listados y mantenga el espacio de trabajo enfocado en los registros que su equipo administra activamente.",
  "Listado de valores predeterminados",
  "Estas preferencias completan previamente los nuevos listados. Los registros existentes no se modifican.",
  "Moneda predeterminada",
  "La moneda preseleccionada para los nuevos precios de cotización.",
  "Elija de la lista completa de monedas ISO 4217.",
  "Unidad de área predeterminada",
  "La unidad de medida preseleccionada para nuevas áreas de listado.",
  "Aplicado al campo de área en nuevos registros.",
  "Estado de listado predeterminado",
  "El estado del flujo de trabajo asignado a los nuevos listados.",
  "Se abren nuevos listados con esta etapa del flujo de trabajo.",
  "Incluir listados archivados",
  "Cuando está habilitado, los listados archivados aparecen en la vista Listados de forma predeterminada.",
  "Mantenga los registros archivados visibles en la vista Listados de forma predeterminada.",
  "Idioma del panel",
  "Elija el idioma para este espacio de trabajo o siga el idioma de la cuenta Wix.",
  "Auto (Wix account language)",
  "Guardado localmente para este navegador",
  "Los cambios aún no se guardan",
  "Reiniciar",
  "Guardar configuración",
  "Configuración del espacio de trabajo guardada.",
  "La configuración no se pudo guardar en este navegador.",
  "Lanzador Saved Properties",
  "Incruste o restaure el botón y el cajón de propiedades guardadas de los miembros en su sitio en vivo.",
  "Es seguro ejecutarlo más de una vez.",
  "Insertar lanzador",
  "Incrustando…",
  "El lanzador Saved Properties está activo en el sitio.",
  "No se pudo incrustar el lanzador.",
  "Ayuda: {hint}",
  "Gestión de clientes potenciales",
  "Solicitudes de cotización",
  "Revisar las consultas sobre propiedades y mantener actualizado el estado del seguimiento.",
  "Solicitudes entrantes",
  "Solicitud {count}",
  "{count} solicitudes",
  "Buscar propiedad",
  "Buscar solicitudes de cotización",
  "Filtrar solicitudes de cotización por estado",
  "Actualizar solicitudes de cotización",
  "No se pudieron cargar las solicitudes de cotización.",
  "La solicitud no se pudo actualizar.",
  "Ninguna solicitud de cotización coincide con estos filtros.",
  "No se proporcionó ningún mensaje.",
  "Notas internas",
  "Notas para {title}",
  "Estado de {title}",
  "Archivo",
  "Página {current}",
  "Anterior",
  "Siguiente",
  "Nuevo",
  "Contactado",
  "citado",
  "Cerrado",
  "Empezando",
  "Cómo utilizar este espacio de trabajo",
  "Cree listados aquí, publíquelos con los widgets del sitio y luego realice un seguimiento de las solicitudes de cotización y la actividad de los visitantes desde este panel.",
  "Ruta recomendada",
  "Agregue al menos una lista activa, coloque los widgets en su sitio y luego verifique las Solicitudes de cotización después de que un visitante envíe una consulta.",
  "Paso {n}",
  "Crear y administrar listados",
  "Mantenga todas las propiedades en un solo inventario.",
  "Agregue un listado con ubicación, precio, imágenes y un recorrido opcional 360°.",
  "El contacto del agente/propietario lo completa el propietario del sitio y se puede editar por listado.",
  "Utilice el menú de acciones del listado para editar, revisar visitantes únicos o eliminar.",
  "Sólo los listados activos aparecen en el sitio en vivo.",
  "Publicar listados en el sitio.",
  "Muestre el inventario y los detalles de la propiedad a los visitantes.",
  "Agregue el widget de listados de propiedades a una página como /properties.",
  "Agregue el widget de detalles de propiedad a una página como /property-details.",
  "En el editor, active o desactive Contacto, solicitud de cotización, compartir y listados relacionados.",
  "Incruste el iniciador Saved Properties desde Configuración para que los miembros puedan marcar casas como favoritos.",
  "Abrir configuración",
  "Atender las consultas de los visitantes",
  "Deje que los compradores se comuniquen con usted sin salir del anuncio.",
  "Los visitantes ven el nombre, el teléfono y el correo electrónico del propietario en la página de propiedad cuando el Contacto está habilitado.",
  "Solicitar una cotización recopila nombre, correo electrónico, teléfono y un mensaje formateado.",
  "Las nuevas solicitudes aparecen aquí con estado, notas y archivo.",
  "Las notificaciones de cotización utilizan el correo electrónico del agente de cotización y el correo electrónico del propietario del sitio.",
  "Solicitudes de cotización abiertas",
  "Escribir copia de listado con IA",
  "Convierta los hechos en descripciones listas para marketing.",
  "Abra AI Listing Writer o use Escribir con IA dentro del editor de listado.",
  "Revise la copia generada y luego guárdela en el listado antes de publicarla.",
  "Utilice Analytics para ver qué listados atraen más visitas.",
  "Necesito más ayuda",
  "Valores predeterminados y soporte del espacio de trabajo",
  "Establezca la moneda, la unidad de área y el estado predeterminados en Configuración. Comuníquese con el desarrollador de la aplicación desde la barra lateral si falta un widget o una colección después de la instalación.",
  "Agregar listado",
  "Editar listado",
  "Mantenga la información de su propiedad precisa y lista para publicar.",
  "No se puede abrir este listado",
  "Volver a listados",
  "No se pudo encontrar este listado.",
  "Este listado no se pudo cargar.",
  "{title} fue actualizado.",
  "Se agregó {title}.",
  "No se pudo guardar el listado.",
  "{title} fue archivado.",
  "No se pudo archivar el listado.",
  "Crear un nuevo listado",
  "Editar detalles del listado",
  "Prohistoria de propiedad",
  "Utilice el editor para agregar una descripción estructurada y pulida.",
  "Título",
  "Un nombre conciso que identifique esta propiedad.",
  "Casa luminosa de 3 dormitorios en Austin, TX",
  "Descripción",
  "Describa la propiedad, distribución, acabados y puntos de venta.",
  "Escribe con IA",
  "AI writer (Pro)",
  "Cargando editor…",
  "Dirección",
  "Ingrese la dirección de la calle o los detalles de la ubicación de la propiedad.",
  "Dirección o barrio",
  "ciudad",
  "Elija una ciudad sugerida o ingrese una manualmente.",
  "Ingresa o selecciona una ciudad",
  "País",
  "Estado / región",
  "Listado de imágenes",
  "Elija imágenes de Wix Media Manager; La primera imagen es la portada.",
  "La primera imagen se utiliza como portada de las tarjetas y de la página de propiedades.",
  "Elige imágenes",
  "Agregar imágenes",
  "Aún no hay imágenes seleccionadas.",
  "Eliminar imagen {n}",
  "360° visita virtual",
  "Agregue fotos 360° equirectangulares para el visor interactivo Three.js. Los visitantes pueden alternar entre habitaciones y miradores.",
  " Los recorridos virtuales están incluidos en Pro y Business; Las imágenes adicionales permanecen en el panel si las agrega ahora.",
  " Los sitios Pro muestran la primera escena; escenas adicionales se publicarán en Business.",
  "360° imágenes panorámicas",
  "Elija imágenes 360° equirectangulares para el visor interactivo Three.js. Los visitantes pueden cambiar entre escenas.",
  "Opcional. Cada imagen debe ser una fotografía 360° equirectangular.",
  "No se seleccionaron panoramas 360°.",
  "Quitar panorama {n}",
  "Escena {n}",
  "Listado de hechos",
  "Estos campos potencian los filtros y el análisis de cartera.",
  "Tipo de transacción",
  "Si la propiedad está en venta, alquiler o arrendamiento.",
  "La categoría que mejor describe la propiedad.",
  "La etapa actual del flujo de trabajo para este listado.",
  "Procondición de propiedad",
  "El estado físico actual de la propiedad.",
  "Estado del mobiliario",
  "Si la propiedad está sin muebles, parcialmente amueblada o amueblada.",
  "Tenencia",
  "El acuerdo de propiedad o arrendamiento de la propiedad.",
  "Frecuencia de alquiler",
  "Con qué frecuencia se espera el alquiler para los listados de alquiler o arrendamiento.",
  "Precio",
  "El precio de cotización en la moneda seleccionada.",
  "Moneda",
  "La moneda de tres letras utilizada para el precio de cotización.",
  "Área",
  "El tamaño de la propiedad en la unidad de área seleccionada.",
  "unidad de área",
  "Servicios",
  "Enumere las características notables separadas por comas.",
  "Piscina, gimnasio, seguridad 24/7",
  "Fecha de disponibilidad",
  "La fecha en que la propiedad esté disponible.",
  "Contacto agente/propietario",
  "Nombre",
  "El agente o propietario responsable de este listado.",
  "Nombre del agente o propietario",
  "Teléfono",
  "Un número de teléfono para consultas sobre listados.",
  "Número de teléfono internacional",
  "Correo electrónico",
  "Una dirección de correo electrónico para consultas sobre listados.",
  "Ubicación del mapa",
  "Latitud",
  "Latitud de la propiedad utilizada para la ubicación del mapa.",
  "longitud",
  "La longitud de la propiedad utilizada para la ubicación del mapa.",
  "Guardar listado",
  "Guardando…",
  "AI writer",
  "Los datos de este listado se completan para usted. Cuando finaliza la escritura, la descripción en el formulario se actualiza automáticamente.",
  "La descripción del listado fue actualizada.",
  "No se pudo abrir el Media Manager.",
  "Seleccione {label}",
  "Valor {label} opcional para este listado.",
  "Opcional",
  "Dormitorios",
  "Baños",
  "Año de construcción",
  "Plazas de aparcamiento",
  "Cargo por servicio",
  "Depósito de seguridad",
  "Requerido",
  "Añade un título.",
  "Añade una dirección.",
  "Añade una ciudad.",
  "Añade un precio.",
  "Añade un área.",
  "Corrija los campos resaltados antes de guardar.",
  "No se pudieron cargar las sugerencias de ubicación. Aún puedes escribir valores.",
  "Proconceptos básicos de propiedad",
  "¿Qué debería decir la descripción?",
  "Ubicación",
  "Austin, Texas",
  "$875,000",
  "Piscina, gimnasio, parking.",
  "Estilo de escritura",
  "Generar descripción",
  "Escribiendo tu descripción…",
  "Descripción generada",
  "Cuando finaliza la redacción, esta copia se agrega a la descripción del listado.",
  "Revise la copia y luego cópiela en su listado.",
  "Copiar",
  "Copiado",
  "Descripción de propiedad generada",
  "Su copia pulida aparecerá aquí",
  "Elija un estilo y genere una descripción a partir de los datos de propiedad confirmados.",
  "Proprofesional",
  "Claro y confiable",
  "lujo",
  "Elevado y aspiracional",
  "corto",
  "Perfecto para tarjetas",
  "SEO optimizado",
  "Copia fácil de buscar",
  "redes sociales",
  "Atractivo y compartible",
  "Amueblado",
  "Semi-amueblado",
  "Sin muebles",
  "No se pudo generar la descripción.",
  "AI Listing Writer está disponible en Pro y Business.",
  "Comparte la copia de tu listado",
  "Llegue a los compradores dondequiera que pasen su tiempo.",
  "Agregar canales",
  "Más canales para compartir",
  "Elija una plataforma para compartir la copia del listado generado. Algunos canales copian primero el título para que puedas agregar fotos y publicarlas de forma natural.",
  "WhatsApp",
  "Enviar a un contacto o grupo",
  "Facebook",
  "Comparte en tu feed",
  "Instagram",
  "Copie el título y abra Instagram",
  "x",
  "Publica en tu línea de tiempo",
  "LinkedIn",
  "Comparte con tu red",
  "Telegram",
  "Enviar a un chat o canal",
  "Pinterest",
  "Copie el título y abra Pinterest",
  "Reddit",
  "Enviar a una comunidad",
  "Threads",
  "Copie el título y abra Threads",
  "TikTok",
  "Copie el título y abra TikTok",
  "YouTube",
  "Copie el título y abra YouTube",
  "Snapchat",
  "Copie el título y abra Snapchat",
  "Correo electrónico",
  "Abre tu aplicación de correo electrónico",
  "mensaje de texto",
  "Enviar como mensaje de texto",
  "Prolistado de propiedad",
  "Descripción del listado",
  "Describe la luz, el diseño, los acabados y las razones para amar esta propiedad...",
  "No se pudieron agregar imágenes a la descripción.",
  "No se pudieron agregar videos a la descripción.",
  "Borrador",
  "Activo",
  "Bajo oferta",
  "Vendido",
  "Archivado",
  "En venta",
  "En alquiler",
  "En arrendamiento",
  "casa",
  "Apartamento",
  "condominio",
  "Casa adosada",
  "Tierra",
  "Oficina",
  "Venta al por menor",
  "industriales",
  "Uso mixto",
  "Otro",
  "Pies cuadrados",
  "Metros cuadrados",
  "acres",
  "Nuevo",
  "bueno",
  "Necesita renovación",
  "dominio absoluto",
  "arrendamiento",
  "Mensual",
  "Anual",
  "Metros cuadrados",
  "acres",
  "Nuevo",
  "bueno",
  "Necesita renovación",
  "dominio absoluto",
  "arrendamiento",
  "Mensual",
  "Anual",
  "English",
  "中文",
  "हिन्दी",
  "Español",
  "العربية",
  "Français",
  "বাংলা",
  "Português",
  "Русский",
  "اردو",
  "Bahasa Indonesia",
  "Deutsch",
  "日本語",
  "Kiswahili",
  "Türkçe",
  "한국어",
  "Tiếng Việt",
  "Italiano",
  "ไทย",
  "Polski",
]);
