import { zip } from "../zip";

export const fr = zip([
  "EstateAI",
  "Espace de travail de liste",
  "Aperçu",
  "Annonces",
  "AI Listing Writer",
  "Analyse",
  "Guider",
  "Tarifs",
  "Paramètres",
  "Demandes de devis",
  "Espace de travail",
  "Proinventaire de propriété",
  "Studio de contenu",
  "Gestion des leads",
  "Intelligence du portefeuille",
  "Commencer",
  "Forfaits",
  "Préférences de l'espace de travail",
  "Basculer la navigation",
  "Contacter le développeur de l'application",
  "Essai",
  "Wix",
  "Planifier",
  "Des annonces illimitées sont visibles sur le site.",
  "{visible} des {cap} annonces sont visibles sur le site.",
  "Commencer l'essai gratuit",
  "Voir les forfaits",
  "Content de te voir",
  "Votre espace de travail immobilier",
  "Gardez votre inventaire organisé, repérez rapidement les mouvements et préparez chaque annonce pour la publication assistée. Nouveau ici ? Suivez le {guide}.",
  "guide de l'espace de travail",
  "Ajouter une annonce",
  "Réessayer",
  "Nous n'avons pas pu charger votre aperçu. Vérifiez les autorisations de collecte et réessayez.",
  "Total des annonces",
  "Dans votre espace de travail",
  "Actif",
  "Actuellement disponible",
  "Sous offre",
  "Passer par un accord",
  "Vendu",
  "Transactions terminées",
  "Annonces récentes",
  "Les dernières propriétés ajoutées ou mises à jour dans votre espace de travail.",
  "Voir tout",
  "Votre inventaire est prêt pour sa première mise en vente",
  "Ajoutez une propriété pour commencer à suivre votre portefeuille et débloquer des analyses.",
  "Annonces ouvertes",
  "Emplacement non défini",
  "Focus suivant",
  "Transformez les détails en élan",
  "Transformez vos informations immobilières confirmées en une copie professionnelle, de luxe, courte, SEO ou prête pour les réseaux sociaux en quelques secondes.",
  "Ouvrir AI writer",
  "Débloquez AI writer",
  "Gestion des stocks",
  "Toutes les annonces",
  "Recherchez, organisez et gardez chaque propriété prête pour sa prochaine étape.",
  "Le site en direct affiche les {visible} inscriptions actives les plus récemment mises à jour de votre plafond de plan {cap}.",
  "Proinventaire de propriété",
  "Liste {count} dans cet espace de travail",
  "Listes {count} dans cet espace de travail",
  "Rechercher un titre ou une ville",
  "Rechercher des annonces",
  "Filtrer par statut",
  "Filtrer par type de propriété",
  "Statut",
  "Protype de propriété",
  "Tous les statuts",
  "Tous types",
  "Page précédente",
  "Page suivante",
  "Page {current} de {total}",
  "Actions pour {title}",
  "Modifier",
  "Visiteurs uniques",
  "Supprimer",
  "Nous n'avons pas pu charger les annonces. Vérifiez les autorisations de collecte et réessayez.",
  "Aucune annonce ne correspond à ces filtres.",
  "Créez votre première annonce ou ajustez la recherche et les filtres.",
  "Chargement des annonces",
  "Tous types de biens",
  "Image de couverture",
  "Image {n}",
  "Entrez un titre pour cette annonce.",
  "Utilisez un code de devise à trois lettres.",
  "Entrez un prix valide.",
  "Entrez une zone valide.",
  "Sélectionnez un pays.",
  "Sélectionnez un état ou une région.",
  "Entrez la ville ou la localité.",
  "Entrez l'adresse postale.",
  "Entrez une adresse e-mail valide.",
  "Entrez un numéro de téléphone valide.",
  "Entrez un numéro valide.",
  "Entrez un nombre entier.",
  "Le pays où se trouve la propriété.",
  "L'état, la province ou la région où se trouve la propriété.",
  "Unité utilisée pour mesurer la superficie d'une propriété.",
  "Les pays n'ont pas pu être chargés.",
  "Les états n'ont pas pu être chargés.",
  "Les villes n'ont pas pu être chargées.",
  "Jusqu'à présent, les vues proviennent de visiteurs non signés, les utilisateurs uniques ne peuvent donc pas être répertoriés.",
  "Maison contemporaine de 3 chambres à Austin, Texas",
  "<p>Maison lumineuse et spacieuse avec des finitions modernes, une excellente lumière naturelle et un garage pour deux voitures. Situé à proximité des commerces, des restaurants et des principaux axes de transport.</p><p>Idéal pour les professionnels ou une famille grandissante à la recherche d'une maison confortable dans un quartier bien desservi.</p>",
  "Piscine, Gym, Garage, Climatisation centrale",
  "Visiteurs uniques",
  "Les personnes qui ont regardé « {title} » ont compté une fois chacune.",
  "Chargement de visiteurs uniques",
  "Les visiteurs uniques n'ont pas pu être chargés. Essayer à nouveau.",
  "Personne n'a encore consulté cette annonce.",
  "{count} visiteur unique",
  "{count} visiteurs uniques",
  "{count} vue non signée",
  "{count} vues non signées",
  "Vue {count}",
  "{count} vues",
  "dernier {when}",
  "Visiteur connecté",
  "Supprimer cette annonce ?",
  "« {title} » sera supprimé des annonces actives. Vous pouvez toujours le consulter lorsque les listes archivées sont activées.",
  "Annuler",
  "Supprimer l'annonce",
  "Propropriété",
  "Tapez",
  "Prix",
  "Statut",
  "Vues",
  "Mis à jour",
  "Actions",
  "Studio de contenu",
  "Rédigez des annonces qui se font remarquer",
  "Ajoutez les informations sur la propriété une fois et laissez l'IA les transformer en une copie marketing soignée. Examinez chaque détail avant de publier.",
  "AI Listing Writer est sur Pro et Business",
  "Mettez à niveau pour générer une copie de liste professionnelle à partir des faits de votre propriété.",
  "Intelligence du portefeuille",
  "Analyses avancées",
  "Comprenez la composition de vos stocks, votre activité et l'état de préparation de votre contenu à partir des données dont vous disposez déjà.",
  "Actualiser",
  "Analytics est disponible sur Pro et Business",
  "Effectuez la mise à niveau pour voir la composition des stocks, l'activité et l'état de préparation du contenu.",
  "Nous n'avons pas pu calculer les analyses. Vérifiez les autorisations de collecte et réessayez.",
  "Inventaire suivi",
  "Inscriptions dans la collection",
  "Contenu AI-ready",
  "Annonces avec des champs AI renseignés",
  "Villes actives",
  "Les cinq principales villes indiquées ci-dessous",
  "Signal d'activité",
  "Annonces ajoutées au cours des six derniers mois",
  "Activité d'inscription",
  "Nouveaux enregistrements créés au cours des six derniers mois civils.",
  "Principales villes",
  "Ajoutez des emplacements pour voir la concentration géographique.",
  "Promélange de propriétés",
  "Inventaire regroupé par type de propriété.",
  "Ajoutez des annonces pour voir la composition de votre propriété.",
  "Prix moyen demandé",
  "Regroupés par devise pour que les comparaisons restent significatives.",
  "Ajoutez des annonces pour voir les signaux de tarification.",
  "Liste {count}",
  "Annonces {count}",
  "Statut de l'annonce",
  "La répartition de votre statut apparaîtra une fois les annonces ajoutées.",
  "Composition des transactions",
  "Votre combinaison de transactions apparaîtra une fois les annonces ajoutées.",
  "Les analyses sont calculées à partir de la collection d'annonces actuelle et actualisées à la demande.",
  "Aucune donnée d'annonce pour l'instant",
  "Répartition actuelle dans votre inventaire.",
  "Forfaits d'applications",
  "Choisissez le plan qui correspond à votre inventaire",
  "Votre essai gratuit inclut toutes les fonctionnalités Business. Une fois celui-ci terminé, le site en direct et les outils fermés suivent votre plan actif.",
  "Commencez le Basic pour publier des annonces et collecter des devis. Passez à Pro ou Business lorsque vous avez besoin d'une copie IA, de visites 360°, d'analyses et d'autres outils marketing.",
  "Forfait actuel",
  "Essai gratuit",
  "Le plus populaire",
  "Comparaison des fonctionnalités",
  "Ce qui est inclus sur Basic, Pro et Business.",
  "Caractéristique",
  "Inclus",
  "Non inclus",
  "Basic",
  "Pro",
  "Business",
  "Gratuit",
  "Inclus avec l'application",
  "par mois",
  "Publiez un petit inventaire et collectez les demandes de renseignements sur le site.",
  "Copie IA, visites 360°, informations sur les visiteurs et analyses de portefeuille.",
  "Annonces illimitées, assistant IA sur site et outils marketing complets.",
  "Annonces actives",
  "Jusqu'à 10",
  "Jusqu'à 50",
  "Illimité",
  "Widgets d’annonces et de détails de propriété",
  "Contact du propriétaire sur les pages d'annonces",
  "Formulaire de demande de devis",
  "Propriétés enregistrées pour les membres",
  "AI Listing Writer",
  "360° visite virtuelle",
  "Informations uniques sur les visiteurs",
  "Analyse de portefeuille",
  "Partage social sur les pages de liste",
  "Notifications par e-mail de demande de devis",
  "Assistant IA immobilier sur site",
  "Annonces associées sur les pages de propriétés",
  "Plusieurs scènes de tournée 360°",
  "Assistance prioritaire",
  "Préférences de l'espace de travail",
  "Paramètres",
  "Définissez des valeurs par défaut raisonnables pour les nouvelles inscriptions et gardez l'espace de travail concentré sur les enregistrements que votre équipe gère activement.",
  "Liste des valeurs par défaut",
  "Ces préférences pré-remplissent les nouvelles annonces. Les enregistrements existants ne sont pas modifiés.",
  "Devise par défaut",
  "Devise présélectionnée pour les nouveaux prix de mise en vente.",
  "Choisissez parmi la liste complète des devises ISO 4217.",
  "Unité de surface par défaut",
  "L'unité de mesure présélectionnée pour les nouvelles zones de référencement.",
  "Appliqué au champ zone sur les nouveaux enregistrements.",
  "Statut d'annonce par défaut",
  "Le statut du flux de travail attribué aux nouvelles annonces.",
  "De nouvelles listes s'ouvrent avec cette étape du flux de travail.",
  "Inclure les annonces archivées",
  "Lorsqu'elles sont activées, les listes archivées apparaissent par défaut dans la vue Listes.",
  "Conservez les enregistrements archivés visibles dans la vue Listes par défaut.",
  "Langue du tableau de bord",
  "Choisissez la langue de cet espace de travail ou suivez la langue du compte Wix.",
  "Auto (Wix account language)",
  "Enregistré localement pour ce navigateur",
  "Les modifications ne sont pas encore enregistrées",
  "Réinitialiser",
  "Enregistrer les paramètres",
  "Paramètres de l'espace de travail enregistrés.",
  "Les paramètres n'ont pas pu être enregistrés dans ce navigateur.",
  "Lanceur Saved Properties",
  "Intégrez ou restaurez le bouton et le tiroir des propriétés enregistrées des membres sur votre site en ligne.",
  "Exécuter plusieurs fois en toute sécurité.",
  "Lanceur d'intégration",
  "Intégration…",
  "Le lanceur Saved Properties est actif sur le site.",
  "Le lanceur n'a pas pu être intégré.",
  "Aide : {hint}",
  "Gestion des leads",
  "Demandes de devis",
  "Examinez les demandes de propriété et maintenez le statut du suivi à jour.",
  "Demandes entrantes",
  "Demande {count}",
  "Requêtes {count}",
  "Rechercher une propriété",
  "Rechercher des demandes de devis",
  "Filtrer les demandes de devis par statut",
  "Actualiser les demandes de devis",
  "Les demandes de devis n'ont pas pu être chargées.",
  "La demande n'a pas pu être mise à jour.",
  "Aucune demande de devis ne correspond à ces filtres.",
  "Aucun message fourni.",
  "Notes internes",
  "Remarques pour {title}",
  "Statut pour {title}",
  "Archiver",
  "Page {current}",
  "Précédent",
  "Suivant",
  "Nouveau",
  "Contacté",
  "Cité",
  "Fermé",
  "Commencer",
  "Comment utiliser cet espace de travail",
  "Créez ici des annonces, publiez-les avec les widgets du site, puis suivez les demandes de devis et l'activité des visiteurs depuis ce tableau de bord.",
  "Chemin recommandé",
  "Ajoutez au moins une annonce active, placez les widgets sur votre site, puis vérifiez les demandes de devis après qu'un visiteur a soumis une demande.",
  "Étape {n}",
  "Créer et gérer des annonces",
  "Conservez chaque propriété dans un seul inventaire.",
  "Ajoutez une annonce avec l'emplacement, le prix, des images et une visite facultative 360°.",
  "Le contact agent/propriétaire est renseigné par le propriétaire du site et peut être modifié par annonce.",
  "Utilisez le menu des actions de liste pour modifier, examiner les visiteurs uniques ou supprimer.",
  "Seules les annonces actives apparaissent sur le site en direct.",
  "Publier des annonces sur le site",
  "Montrez l’inventaire et les détails de la propriété aux visiteurs.",
  "Ajoutez le widget de listes de propriétés à une page telle que /properties.",
  "Ajoutez le widget de détail de propriété à une page telle que /property-details.",
  "Dans l'éditeur, activez ou désactivez les contacts, les demandes de devis, les partages et les listes associées.",
  "Intégrez le lanceur Saved Properties à partir des paramètres afin que les membres puissent ajouter leurs maisons à leurs favoris.",
  "Ouvrir les paramètres",
  "Gérer les demandes des visiteurs",
  "Laissez les acheteurs vous contacter sans quitter l’annonce.",
  "Les visiteurs voient le nom, le téléphone et l'adresse e-mail du propriétaire sur la page de propriété lorsque Contact est activé.",
  "Demander un devis collecte le nom, l'e-mail, le téléphone et un message formaté.",
  "Les nouvelles demandes apparaissent ici avec leur statut, leurs notes et leurs archives.",
  "Les notifications de devis utilisent l’e-mail de l’agent inscripteur et l’e-mail du propriétaire du site.",
  "Demandes de devis ouvertes",
  "Rédiger une copie de la liste avec l'IA",
  "Transformez les faits en descriptions prêtes à être commercialisées.",
  "Ouvrez AI Listing Writer ou utilisez Write with AI dans l'éditeur de liste.",
  "Vérifiez la copie générée, puis enregistrez-la dans la liste avant de la publier.",
  "Utilisez Analytics pour voir quelles annonces attirent le plus de vues.",
  "Besoin de plus d'aide",
  "Paramètres par défaut et prise en charge de l'espace de travail",
  "Définissez la devise, l'unité de zone et le statut par défaut dans Paramètres. Contactez le développeur de l'application depuis la barre latérale si un widget ou une collection manque après l'installation.",
  "Ajouter une annonce",
  "Modifier la fiche",
  "Gardez les informations de votre propriété exactes et prêtes à être publiées.",
  "Impossible d'ouvrir cette annonce",
  "Retour aux annonces",
  "Cette liste est introuvable.",
  "Cette liste n'a pas pu être chargée.",
  "{title} a été mis à jour.",
  "{title} a été ajouté.",
  "La liste n'a pas pu être enregistrée.",
  "{title} a été archivé.",
  "La liste n'a pas pu être archivée.",
  "Créer une nouvelle annonce",
  "Modifier les détails de l'annonce",
  "Prohistoire de propriété",
  "Utilisez l'éditeur pour ajouter une description soignée et structurée.",
  "Titre",
  "Un nom concis qui identifie cette propriété.",
  "Maison lumineuse de 3 chambres à Austin, Texas",
  "Descriptif",
  "Décrivez la propriété, l'aménagement, les finitions et les arguments de vente.",
  "Écrire avec l'IA",
  "AI writer (Pro)",
  "Chargement de l'éditeur…",
  "Adresse",
  "Entrez l'adresse postale ou les détails de l'emplacement de la propriété.",
  "Adresse postale ou quartier",
  "Ville",
  "Choisissez une ville suggérée ou saisissez-en une manuellement.",
  "Entrez ou sélectionnez une ville",
  "Pays",
  "État/région",
  "Liste des images",
  "Choisissez des images parmi Wix Media Manager ; la première image est la couverture.",
  "La première image est utilisée comme couverture sur les cartes et comme page de propriétés.",
  "Choisissez des images",
  "Ajouter des images",
  "Aucune image sélectionnée pour l'instant.",
  "Supprimer l'image {n}",
  "360° visite virtuelle",
  "Ajoutez des photos 360° équirectangulaires pour la visionneuse interactive Three.js. Les visiteurs peuvent basculer entre les salles et les points de vue.",
  " Les visites virtuelles sont incluses sur Pro et Business ; les images supplémentaires restent dans le tableau de bord si vous les ajoutez maintenant.",
  " Les sites Pro montrent la première scène ; des scènes supplémentaires seront mises en ligne sur Business.",
  "Images panoramiques 360°",
  "Choisissez des images 360° équirectangulaires pour la visionneuse interactive Three.js. Les visiteurs peuvent basculer entre les scènes.",
  "Facultatif. Chaque image doit être une photo 360° équirectangulaire.",
  "Aucun panorama 360° sélectionné.",
  "Supprimer le panorama {n}",
  "Scène {n}",
  "Liste des faits",
  "Ces champs alimentent les filtres et les analyses de portefeuille.",
  "Type d'opération",
  "Que le bien soit à vendre, à louer ou à louer.",
  "La catégorie qui décrit le mieux la propriété.",
  "Étape actuelle du flux de travail pour cette liste.",
  "Proétat de propriété",
  "L'état physique actuel de la propriété.",
  "Statut d'ameublement",
  "Que le bien soit non meublé, partiellement meublé ou meublé.",
  "Mandat",
  "Le régime de propriété ou de location de la propriété.",
  "Fréquence de location",
  "À quelle fréquence le loyer est-il attendu pour les annonces de location ou de location.",
  "Prix",
  "Le prix affiché dans la devise sélectionnée.",
  "Devise",
  "La devise à trois lettres utilisée pour le prix d'inscription.",
  "Zone",
  "Taille de la propriété dans l'unité de zone sélectionnée.",
  "Unité de surface",
  "Commodités",
  "Répertoriez les fonctionnalités notables séparées par des virgules.",
  "Piscine, salle de sport, sécurité 24h/24 et 7j/7",
  "Date de disponibilité",
  "La date à laquelle le bien devient disponible.",
  "Contact agent/propriétaire",
  "Nom",
  "L'agent ou le propriétaire responsable de cette annonce.",
  "Nom de l'agent ou du propriétaire",
  "Téléphone",
  "Un numéro de téléphone pour les demandes de renseignements.",
  "Numéro de téléphone international",
  "Courriel",
  "Une adresse e-mail pour les demandes de renseignements.",
  "Emplacement sur la carte",
  "Latitude",
  "La latitude de la propriété utilisée pour le placement de la carte.",
  "Longitude",
  "Longitude de la propriété utilisée pour le placement de la carte.",
  "Enregistrer l'annonce",
  "Sauvegarde…",
  "AI writer",
  "Les faits de cette liste sont remplis pour vous. Une fois la rédaction terminée, la description sur le formulaire est automatiquement mise à jour.",
  "La description de l'annonce a été mise à jour.",
  "Le Media Manager n'a pas pu être ouvert.",
  "Sélectionnez {label}",
  "Valeur {label} facultative pour cette annonce.",
  "Facultatif",
  "Chambres",
  "Salles de bains",
  "Année de construction",
  "Places de parking",
  "Frais de service",
  "Dépôt de garantie",
  "Obligatoire",
  "Ajoutez un titre.",
  "Ajoutez une adresse.",
  "Ajoutez une ville.",
  "Ajoutez un prix.",
  "Ajoutez une zone.",
  "Corrigez les champs en surbrillance avant de sauvegarder.",
  "Les suggestions de localisation n'ont pas pu être chargées. Vous pouvez toujours saisir des valeurs.",
  "Probases de propriété",
  "Que doit dire la description ?",
  "Emplacement",
  "Austin, Texas",
  "875 000 $",
  "Piscine, salle de sport, parking",
  "Style d'écriture",
  "Générer une description",
  "Rédiger votre description…",
  "Description générée",
  "Une fois la rédaction terminée, cette copie est ajoutée à la description de l'annonce.",
  "Vérifiez la copie, puis copiez-la dans votre annonce.",
  "Copier",
  "Copié",
  "Description de la propriété générée",
  "Votre copie soignée apparaîtra ici",
  "Choisissez un style et générez une description à partir des faits de propriété confirmés.",
  "Proprofessionnel",
  "Clair et fiable",
  "Luxe",
  "Élevé et ambitieux",
  "Court",
  "Parfait pour les cartes",
  "SEO optimisé",
  "Copie conviviale pour la recherche",
  "Médias sociaux",
  "Engageant et partageable",
  "Meublé",
  "Semi-meublé",
  "Non meublé",
  "La description n'a pas pu être générée.",
  "AI Listing Writer est disponible sur Pro et Business.",
  "Partagez votre copie d'annonce",
  "Touchez les acheteurs partout où ils passent du temps.",
  "Ajouter des chaînes",
  "Plus de canaux de partage",
  "Choisissez une plate-forme pour partager la copie de liste générée. Certaines chaînes copient d'abord la légende afin que vous puissiez ajouter des photos et la publier naturellement.",
  "WhatsApp",
  "Envoyer à un contact ou à un groupe",
  "Facebook",
  "Partager sur votre flux",
  "Instagram",
  "Copiez la légende et ouvrez Instagram",
  "X",
  "Publier sur votre timeline",
  "LinkedIn",
  "Partagez avec votre réseau",
  "Telegram",
  "Envoyer à un chat ou à une chaîne",
  "Pinterest",
  "Copiez la légende et ouvrez Pinterest",
  "Reddit",
  "Soumettre à une communauté",
  "Threads",
  "Copiez la légende et ouvrez Threads",
  "TikTok",
  "Copiez la légende et ouvrez TikTok",
  "YouTube",
  "Copiez la légende et ouvrez YouTube",
  "Snapchat",
  "Copiez la légende et ouvrez Snapchat",
  "Courriel",
  "Ouvrez votre application de messagerie",
  "SMS",
  "Envoyer sous forme de message texte",
  "Proliste de propriétés",
  "Description de l'annonce",
  "Décrivez la lumière, l'agencement, les finitions et les raisons d'aimer cette propriété…",
  "Les images n'ont pas pu être ajoutées à la description.",
  "Les vidéos n'ont pas pu être ajoutées à la description.",
  "Brouillon",
  "Actif",
  "Sous offre",
  "Vendu",
  "Archivé",
  "À vendre",
  "À louer",
  "À louer",
  "Maison",
  "Appartement",
  "Copropriété",
  "Maison de ville",
  "Terrain",
  "Bureau",
  "Vente au détail",
  "Industriel",
  "Usage mixte",
  "Autre",
  "Pieds carrés",
  "Mètres carrés",
  "Acres",
  "Nouveau",
  "Bien",
  "A besoin de rénovation",
  "Pleine propriété",
  "Propriété à bail",
  "Mensuel",
  "Annuel",
  "Mètres carrés",
  "Acres",
  "Nouveau",
  "Bien",
  "A besoin de rénovation",
  "Pleine propriété",
  "Propriété à bail",
  "Mensuel",
  "Annuel",
  "English",
  "中文",
  "हिन्दी",
  "Español",
  "العربية",
  "Français",
  "বাংলা",
  "Português",
  "Русский",
  "اردو",
  "Bahasa Indonesia",
  "Deutsch",
  "日本語",
  "Kiswahili",
  "Türkçe",
  "한국어",
  "Tiếng Việt",
  "Italiano",
  "ไทย",
  "Polski",
]);
