import { zip } from "../zip";

export const id = zip([
  "EstateAI",
  "Daftar ruang kerja",
  "Ikhtisar",
  "Daftar",
  "AI Listing Writer",
  "Analisis",
  "Panduan",
  "Harga",
  "Pengaturan",
  "Permintaan penawaran",
  "Ruang kerja",
  "Propersediaan perti",
  "Studio konten",
  "Manajemen pimpinan",
  "Kecerdasan portofolio",
  "Memulai",
  "Rencana",
  "Preferensi ruang kerja",
  "Alihkan navigasi",
  "Hubungi pengembang aplikasi",
  "Percobaan",
  "Wix",
  "Rencana",
  "Daftar tak terbatas terlihat di situs.",
  "Daftar {visible} dari {cap} terlihat di situs.",
  "Mulai uji coba gratis",
  "Lihat rencana",
  "Senang bertemu denganmu",
  "Ruang kerja real estat Anda",
  "Jaga agar inventaris Anda tetap teratur, lihat pergerakan dengan cepat, dan persiapkan setiap listingan untuk penerbitan berbantuan. Baru di sini? Ikuti {guide}.",
  "panduan ruang kerja",
  "Tambahkan daftar",
  "Coba lagi",
  "Kami tidak dapat memuat ikhtisar Anda. Periksa izin pengumpulan dan coba lagi.",
  "Daftar total",
  "Di seberang ruang kerja Anda",
  "Aktif",
  "Saat ini tersedia",
  "Di bawah penawaran",
  "Bergerak melalui kesepakatan",
  "Terjual",
  "Transaksi selesai",
  "Daftar terbaru",
  "Properti terbaru ditambahkan atau diperbarui di ruang kerja Anda.",
  "Lihat semua",
  "Inventaris Anda siap untuk dicantumkan pertama kali",
  "Tambahkan properti untuk mulai melacak portofolio Anda dan membuka analitik.",
  "Buka daftar",
  "Lokasi tidak disetel",
  "Fokus selanjutnya",
  "Ubah detail menjadi momentum",
  "Ubah fakta properti Anda yang telah dikonfirmasi menjadi salinan profesional, mewah, pendek, SEO, atau sosial dalam hitungan detik.",
  "Buka AI writer",
  "Buka kunci AI writer",
  "Manajemen inventaris",
  "Semua daftar",
  "Cari, atur, dan persiapkan setiap properti untuk tahap selanjutnya.",
  "Situs langsung menampilkan {visible} daftar aktif yang paling baru diperbarui dari batas paket {cap} Anda.",
  "Propersediaan perti",
  "{count} terdaftar di ruang kerja ini",
  "{count} terdaftar di ruang kerja ini",
  "Cari judul atau kota",
  "Daftar pencarian",
  "Saring berdasarkan status",
  "Filter menurut jenis properti",
  "Status",
  "Pro tipe perti",
  "Semua status",
  "Semua tipe",
  "Halaman sebelumnya",
  "Halaman berikutnya",
  "Halaman {current} dari {total}",
  "Tindakan untuk {title}",
  "Sunting",
  "Pengunjung unik",
  "Hapus",
  "Kami tidak dapat memuat daftar. Periksa izin pengumpulan dan coba lagi.",
  "Tidak ada listingan yang cocok dengan filter ini.",
  "Buat listingan pertama Anda atau sesuaikan pencarian dan filter.",
  "Memuat daftar",
  "Semua tipe properti",
  "Gambar sampul",
  "Gambar {n}",
  "Masukkan judul untuk listing ini.",
  "Gunakan kode mata uang tiga huruf.",
  "Masukkan harga yang valid.",
  "Masukkan area yang valid.",
  "Pilih negara.",
  "Pilih negara bagian atau wilayah.",
  "Masukkan kota atau wilayah.",
  "Masukkan alamat jalan.",
  "Masukkan alamat email yang valid.",
  "Masukkan nomor telepon yang valid.",
  "Masukkan nomor yang valid.",
  "Masukkan bilangan bulat.",
  "Negara tempat properti berada.",
  "Negara bagian, provinsi, atau wilayah tempat properti berada.",
  "Satuan yang digunakan untuk mengukur luas properti.",
  "Negara tidak dapat dimuat.",
  "Serikat tidak dapat dimuat.",
  "Kota tidak dapat dimuat.",
  "Penayangan sejauh ini berasal dari pengunjung yang tidak memiliki tanda tangan, sehingga pengguna unik tidak dapat dicantumkan.",
  "Rumah 3 kamar tidur kontemporer di Austin, TX",
  "<p>Rumah cerah dan luas dengan finishing modern, cahaya alami yang sangat baik, dan garasi dua mobil. Terletak dekat dengan pertokoan, restoran, dan jalur komuter utama.</p><p>Ideal untuk para profesional atau keluarga yang sedang berkembang yang mencari rumah nyaman di lingkungan yang terhubung dengan baik.</p>",
  "Kolam renang, Gym, Garasi, Udara sentral",
  "Pengunjung unik",
  "Orang yang melihat “{title}”, masing-masing dihitung satu kali.",
  "Memuat pengunjung unik",
  "Pengunjung unik tidak dapat dimuat. Coba lagi.",
  "Belum ada yang melihat daftar ini.",
  "{count} pengunjung unik",
  "{count} pengunjung unik",
  "{count} tampilan tidak bertanda tangan",
  "{count} penayangan tanpa tanda tangan",
  "tampilan {count}",
  "{count} penayangan",
  "{when} terakhir",
  "Pengunjung yang masuk",
  "Hapus daftar ini?",
  "“{title}” akan dihapus dari daftar aktif. Anda masih dapat melihatnya ketika daftar yang diarsipkan diaktifkan.",
  "Batalkan",
  "Hapus daftar",
  "Properti",
  "Ketik",
  "Harga",
  "Status",
  "Tampilan",
  "Diperbarui",
  "Tindakan",
  "Studio konten",
  "Tulis daftar yang mendapat perhatian",
  "Tambahkan fakta properti satu kali dan biarkan AI mengubahnya menjadi salinan pemasaran yang sempurna. Tinjau setiap detail sebelum dipublikasikan.",
  "AI Listing Writer ada di Pro dan Business",
  "Tingkatkan versi untuk menghasilkan salinan daftar profesional dari fakta properti Anda.",
  "Kecerdasan portofolio",
  "Analisis tingkat lanjut",
  "Pahami campuran inventaris, aktivitas, dan kesiapan konten Anda dari data yang sudah Anda miliki.",
  "Segarkan",
  "Analytics ada di Pro dan Business",
  "Tingkatkan versi untuk melihat campuran inventaris, aktivitas, dan kesiapan konten.",
  "Kami tidak dapat menghitung analitik. Periksa izin pengumpulan dan coba lagi.",
  "Inventaris terlacak",
  "Daftar dalam koleksi",
  "AI-ready konten",
  "Daftar dengan bidang AI terisi",
  "Kota yang aktif",
  "Lima kota teratas ditunjukkan di bawah ini",
  "Sinyal aktivitas",
  "Daftar ditambahkan dalam enam bulan terakhir",
  "Aktivitas pencatatan",
  "Rekor baru dibuat selama enam bulan kalender terakhir.",
  "Kota-kota teratas",
  "Tambahkan lokasi untuk melihat konsentrasi geografis.",
  "Procampuran perty",
  "Inventaris dikelompokkan berdasarkan jenis properti.",
  "Tambahkan listing untuk melihat campuran properti Anda.",
  "Harga rata-rata yang diminta",
  "Dikelompokkan berdasarkan mata uang agar perbandingan tetap bermakna.",
  "Tambahkan listingan untuk melihat sinyal harga.",
  "daftar {count}",
  "daftar {count}",
  "Status daftar",
  "Perincian status Anda akan muncul setelah listingan ditambahkan.",
  "Campuran transaksi",
  "Campuran transaksi Anda akan muncul setelah listing ditambahkan.",
  "Analytics dihitung dari kumpulan listingan saat ini dan disegarkan sesuai permintaan.",
  "Belum ada data daftar",
  "Distribusi saat ini di seluruh inventaris Anda.",
  "Paket aplikasi",
  "Pilih paket yang sesuai dengan inventaris Anda",
  "Uji coba gratis Anda mencakup setiap fitur Business. Setelah berakhir, situs langsung dan alat yang terjaga keamanannya mengikuti rencana aktif Anda.",
  "Mulai di Basic untuk mempublikasikan daftar dan mengumpulkan penawaran. Tingkatkan ke Pro atau Business saat Anda memerlukan salinan AI, tur 360°, analitik, dan alat pemasaran lainnya.",
  "Rencana saat ini",
  "Uji coba gratis",
  "Paling populer",
  "Perbandingan fitur",
  "Apa yang termasuk dalam Basic, Pro, dan Business.",
  "Fitur",
  "Termasuk",
  "Tidak termasuk",
  "Basic",
  "Pro",
  "Business",
  "Gratis",
  "Termasuk dengan aplikasi",
  "per bulan",
  "Publikasikan inventaris kecil dan kumpulkan pertanyaan dari situs.",
  "Salinan AI, tur 360°, wawasan pengunjung, dan analisis portofolio.",
  "Daftar tak terbatas, asisten AI di tempat, dan alat pemasaran lengkap.",
  "Daftar aktif",
  "Hingga 10",
  "Hingga 50",
  "Tidak terbatas",
  "Widget daftar dan detail properti",
  "Kontak pemilik di halaman daftar",
  "Formulir permintaan penawaran",
  "Properti tersimpan untuk anggota",
  "AI Listing Writer",
  "360° tur virtual",
  "Wawasan pengunjung yang unik",
  "Analisis portofolio",
  "Berbagi sosial di halaman daftar",
  "Notifikasi email permintaan penawaran harga",
  "Asisten AI properti di tempat",
  "Daftar terkait di halaman properti",
  "Beberapa adegan tur 360°",
  "Dukungan prioritas",
  "Preferensi ruang kerja",
  "Pengaturan",
  "Tetapkan default yang masuk akal untuk listingan baru dan jaga agar ruang kerja tetap fokus pada catatan yang dikelola secara aktif oleh tim Anda.",
  "Daftar default",
  "Preferensi ini mengisi daftar baru terlebih dahulu. Catatan yang ada tidak diubah.",
  "Mata uang bawaan",
  "Mata uang yang dipilih sebelumnya untuk harga listing baru.",
  "Pilih dari daftar mata uang ISO 4217 lengkap.",
  "Satuan luas bawaan",
  "Unit pengukuran telah dipilih sebelumnya untuk area listing baru.",
  "Diterapkan ke bidang area pada catatan baru.",
  "Status daftar bawaan",
  "Status alur kerja yang ditetapkan ke listingan baru.",
  "Daftar baru dibuka dengan tahap alur kerja ini.",
  "Sertakan daftar yang diarsipkan",
  "Jika diaktifkan, daftar yang diarsipkan akan muncul di tampilan Daftar secara default.",
  "Jaga agar catatan yang diarsipkan tetap terlihat di tampilan Daftar secara default.",
  "Bahasa dasbor",
  "Pilih bahasa untuk ruang kerja ini, atau ikuti bahasa akun Wix.",
  "Auto (Wix account language)",
  "Disimpan secara lokal untuk browser ini",
  "Perubahan belum disimpan",
  "Setel ulang",
  "Simpan pengaturan",
  "Pengaturan ruang kerja disimpan.",
  "Setelan tidak dapat disimpan di browser ini.",
  "peluncur Saved Properties",
  "Sematkan atau pulihkan tombol dan laci properti tersimpan anggota di situs langsung Anda.",
  "Aman untuk dijalankan lebih dari sekali.",
  "Sematkan peluncur",
  "Menyematkan…",
  "Peluncur Saved Properties aktif di situs.",
  "Peluncur tidak dapat disematkan.",
  "Bantuan: {hint}",
  "Manajemen pimpinan",
  "Permintaan penawaran",
  "Tinjau pertanyaan properti dan terus perbarui status tindak lanjut.",
  "Permintaan masuk",
  "permintaan {count}",
  "{count} permintaan",
  "Cari properti",
  "Permintaan penawaran pencarian",
  "Filter permintaan penawaran berdasarkan status",
  "Segarkan permintaan penawaran harga",
  "Permintaan penawaran harga tidak dapat dimuat.",
  "Permintaan tidak dapat diperbarui.",
  "Tidak ada permintaan penawaran harga yang cocok dengan filter ini.",
  "Tidak ada pesan yang diberikan.",
  "Catatan dalaman",
  "Catatan untuk {title}",
  "Status untuk {title}",
  "Arsip",
  "Halaman {current}",
  "Sebelumnya",
  "Selanjutnya",
  "Baru",
  "Dihubungi",
  "Dikutip",
  "Tertutup",
  "Memulai",
  "Cara menggunakan ruang kerja ini",
  "Buat daftar di sini, publikasikan dengan widget situs, lalu tindak lanjuti permintaan penawaran harga dan aktivitas pengunjung dari dasbor ini.",
  "Jalur yang direkomendasikan",
  "Tambahkan setidaknya satu daftar aktif, tempatkan widget di situs Anda, lalu centang Permintaan penawaran setelah pengunjung mengajukan pertanyaan.",
  "Langkah {n}",
  "Membuat dan mengelola daftar",
  "Simpan setiap properti dalam satu inventaris.",
  "Tambahkan daftar dengan lokasi, harga, gambar, dan tur 360° opsional.",
  "Kontak agen/pemilik diisi dari pemilik situs dan dapat diedit per listing.",
  "Gunakan menu tindakan daftar untuk mengedit, meninjau pengunjung unik, atau menghapus.",
  "Hanya daftar aktif yang muncul di situs langsung.",
  "Publikasikan daftar di situs",
  "Tampilkan inventaris dan detail properti kepada pengunjung.",
  "Tambahkan widget daftar properti ke halaman seperti /properties.",
  "Tambahkan widget detail properti ke halaman seperti /property-details.",
  "Di editor, aktifkan atau nonaktifkan Kontak, permintaan penawaran harga, berbagi, dan daftar terkait.",
  "Sematkan peluncur Saved Properties dari Pengaturan sehingga anggota dapat menandai rumah.",
  "Buka pengaturan",
  "Menangani pertanyaan pengunjung",
  "Biarkan pembeli menghubungi Anda tanpa meninggalkan daftar.",
  "Pengunjung melihat nama pemilik, telepon, dan email di halaman properti ketika Kontak diaktifkan.",
  "Permintaan penawaran mengumpulkan nama, email, telepon, dan pesan yang diformat.",
  "Permintaan baru muncul di sini dengan status, catatan, dan arsip.",
  "Notifikasi penawaran menggunakan email agen listing dan email pemilik situs.",
  "Buka permintaan penawaran",
  "Tulis salinan daftar dengan AI",
  "Ubah fakta menjadi deskripsi yang siap dipasarkan.",
  "Buka AI Listing Writer atau gunakan Tulis dengan AI di dalam editor daftar.",
  "Tinjau salinan yang dihasilkan, lalu simpan di daftar sebelum dipublikasikan.",
  "Gunakan Analytics untuk melihat listingan mana yang paling banyak dilihat.",
  "Butuh bantuan lebih lanjut",
  "Default dan dukungan ruang kerja",
  "Tetapkan mata uang default, satuan area, dan status di Pengaturan. Hubungi pengembang aplikasi dari sidebar jika widget atau koleksi hilang setelah instalasi.",
  "Tambahkan daftar",
  "Sunting daftar",
  "Jaga keakuratan informasi properti Anda dan siap dipublikasikan.",
  "Tidak dapat membuka daftar ini",
  "Kembali ke daftar",
  "Daftar ini tidak dapat ditemukan.",
  "Daftar ini tidak dapat dimuat.",
  "{title} telah diperbarui.",
  "{title} telah ditambahkan.",
  "Daftar tidak dapat disimpan.",
  "{title} telah diarsipkan.",
  "Daftar tidak dapat diarsipkan.",
  "Buat daftar baru",
  "Edit detail daftar",
  "Procerita penting",
  "Gunakan editor untuk menambahkan deskripsi yang halus dan terstruktur.",
  "Judul",
  "Nama ringkas yang mengidentifikasi properti ini.",
  "Rumah 3 kamar tidur penuh cahaya di Austin, TX",
  "Deskripsi",
  "Jelaskan properti, tata letak, hasil akhir, dan nilai jual.",
  "Menulis dengan AI",
  "AI writer (Pro)",
  "Memuat editor…",
  "Alamat",
  "Masukkan alamat jalan atau detail lokasi properti.",
  "Alamat jalan atau lingkungan",
  "Kota",
  "Pilih kota yang disarankan atau masukkan kota secara manual.",
  "Masukkan atau pilih kota",
  "Negara",
  "Negara bagian / wilayah",
  "Daftar gambar",
  "Pilih gambar dari Wix Media Manager; gambar pertama adalah sampulnya.",
  "Gambar pertama digunakan sebagai sampul kartu dan halaman properti.",
  "Pilih gambar",
  "Tambahkan gambar",
  "Belum ada gambar yang dipilih.",
  "Hapus gambar {n}",
  "360° tur virtual",
  "Tambahkan foto 360° berbentuk persegi panjang untuk penampil Three.js interaktif. Pengunjung dapat beralih antara ruangan dan sudut pandang.",
  " Tur virtual disertakan di Pro dan Business; gambar tambahan tetap ada di dasbor jika Anda menambahkannya sekarang.",
  " Situs Pro menampilkan adegan pertama; adegan tambahan ditayangkan di Business.",
  "360° gambar panorama",
  "Pilih gambar 360° berbentuk persegi panjang untuk penampil Three.js interaktif. Pengunjung dapat beralih antar adegan.",
  "Opsional. Setiap gambar harus berupa foto 360° berbentuk persegi panjang.",
  "Tidak ada panorama 360° yang dipilih.",
  "Hapus panorama {n}",
  "Adegan {n}",
  "Daftar fakta",
  "Bidang-bidang ini mendukung filter dan analisis portofolio.",
  "Jenis transaksi",
  "Apakah properti itu untuk dijual, disewakan, atau disewakan.",
  "Kategori yang paling menggambarkan properti.",
  "Tahap alur kerja saat ini untuk listingan ini.",
  "Prokondisi bagus",
  "Kondisi fisik properti saat ini.",
  "Status perabotan",
  "Apakah properti tersebut tidak berperabotan, berperabot sebagian, atau berperabotan.",
  "Kepemilikan",
  "Pengaturan kepemilikan atau sewa atas properti.",
  "Frekuensi sewa",
  "Seberapa sering sewa diharapkan untuk daftar sewa atau sewa.",
  "Harga",
  "Harga listing dalam mata uang yang dipilih.",
  "Mata uang",
  "Mata uang tiga huruf yang digunakan untuk harga listing.",
  "Daerah",
  "Ukuran properti dalam satuan luas yang dipilih.",
  "Satuan luas",
  "Fasilitas",
  "Buat daftar fitur penting yang dipisahkan dengan koma.",
  "Kolam renang, gym, keamanan 24/7",
  "Tanggal ketersediaan",
  "Tanggal ketika properti tersedia.",
  "Kontak agen/pemilik",
  "Nama",
  "Agen atau pemilik yang bertanggung jawab atas listing ini.",
  "Nama agen atau pemilik",
  "Telepon",
  "Nomor telepon untuk pertanyaan daftar.",
  "Nomor telepon internasional",
  "Surel",
  "Alamat email untuk pertanyaan daftar.",
  "Penempatan peta",
  "Lintang",
  "Properti garis lintang yang digunakan untuk penempatan peta.",
  "Garis bujur",
  "Garis bujur properti yang digunakan untuk penempatan peta.",
  "Simpan daftar",
  "Menyimpan…",
  "AI writer",
  "Fakta dari daftar ini diisi untuk Anda. Ketika penulisan selesai, deskripsi pada formulir diperbarui secara otomatis.",
  "Deskripsi daftar telah diperbarui.",
  "Media Manager tidak dapat dibuka.",
  "Pilih {label}",
  "Nilai {label} opsional untuk listingan ini.",
  "Opsional",
  "Kamar tidur",
  "Kamar mandi",
  "Tahun dibangun",
  "Tempat parkir",
  "Biaya layanan",
  "Uang jaminan",
  "Diperlukan",
  "Tambahkan judul.",
  "Tambahkan alamat.",
  "Tambahkan kota.",
  "Tambahkan harga.",
  "Tambahkan area.",
  "Perbaiki bidang yang disorot sebelum menyimpan.",
  "Saran lokasi tidak dapat dimuat. Anda masih bisa mengetikkan nilai.",
  "Property dasar-dasar",
  "Apa yang seharusnya dijelaskan dalam deskripsi tersebut?",
  "Lokasi",
  "Austin, Texas",
  "$875.000",
  "Kolam renang, gym, parkir",
  "Gaya penulisan",
  "Hasilkan deskripsi",
  "Menulis deskripsi Anda…",
  "Deskripsi yang dihasilkan",
  "Ketika penulisan selesai, salinan ini ditambahkan ke deskripsi daftar.",
  "Tinjau salinannya, lalu salin ke daftar Anda.",
  "Salin",
  "Disalin",
  "Deskripsi properti yang dihasilkan",
  "Salinan Anda yang telah dipoles akan muncul di sini",
  "Pilih gaya dan buat deskripsi dari fakta properti yang dikonfirmasi.",
  "Proprofesional",
  "Jelas dan dapat dipercaya",
  "Kemewahan",
  "Tinggi dan aspiratif",
  "Pendek",
  "Sempurna untuk kartu",
  "SEO dioptimalkan",
  "Salinan yang ramah pencarian",
  "media sosial",
  "Menarik dan dapat dibagikan",
  "Dilengkapi",
  "Semi-perabotan",
  "Tanpa perabotan",
  "Deskripsi tidak dapat dibuat.",
  "AI Listing Writer tersedia di Pro dan Business.",
  "Bagikan salinan daftar Anda",
  "Jangkau pembeli di mana pun mereka menghabiskan waktu.",
  "Tambahkan saluran",
  "Lebih banyak saluran berbagi",
  "Pilih platform untuk membagikan salinan daftar yang dihasilkan. Beberapa saluran menyalin keterangannya terlebih dahulu sehingga Anda dapat menambahkan foto dan mempublikasikannya secara alami.",
  "WhatsApp",
  "Kirim ke kontak atau grup",
  "Facebook",
  "Bagikan ke umpan Anda",
  "Instagram",
  "Salin keterangan dan buka Instagram",
  "X",
  "Posting ke timeline Anda",
  "LinkedIn",
  "Bagikan dengan jaringan Anda",
  "Telegram",
  "Kirim ke obrolan atau saluran",
  "Pinterest",
  "Salin keterangan dan buka Pinterest",
  "Reddit",
  "Kirim ke komunitas",
  "Threads",
  "Salin keterangan dan buka Threads",
  "TikTok",
  "Salin keterangan dan buka TikTok",
  "YouTube",
  "Salin keterangan dan buka YouTube",
  "Snapchat",
  "Salin keterangan dan buka Snapchat",
  "Surel",
  "Buka aplikasi email Anda",
  "Pesan teks",
  "Kirim sebagai pesan teks",
  "Prodaftar perti",
  "Deskripsi daftar",
  "Jelaskan pencahayaan, tata letak, penyelesaian akhir, dan alasan menyukai properti ini…",
  "Gambar tidak dapat ditambahkan ke deskripsi.",
  "Video tidak dapat ditambahkan ke deskripsi.",
  "Draf",
  "Aktif",
  "Di bawah penawaran",
  "Terjual",
  "Diarsipkan",
  "Dijual",
  "Disewakan",
  "Untuk disewakan",
  "Rumah",
  "Apartemen",
  "Kondominium",
  "rumah kota",
  "Tanah",
  "Kantor",
  "Ritel",
  "Industri",
  "Penggunaan campuran",
  "Lainnya",
  "Kaki persegi",
  "Meter persegi",
  "hektar",
  "Baru",
  "Bagus",
  "Perlu renovasi",
  "Hak Milik",
  "Hak Sewa",
  "Bulanan",
  "Tahunan",
  "Meter persegi",
  "hektar",
  "Baru",
  "Bagus",
  "Perlu renovasi",
  "Hak Milik",
  "Hak Sewa",
  "Bulanan",
  "Tahunan",
  "English",
  "中文",
  "हिन्दी",
  "Español",
  "العربية",
  "Français",
  "বাংলা",
  "Português",
  "Русский",
  "اردو",
  "Bahasa Indonesia",
  "Deutsch",
  "日本語",
  "Kiswahili",
  "Türkçe",
  "한국어",
  "Tiếng Việt",
  "Italiano",
  "ไทย",
  "Polski",
]);
