import { zip } from "../zip";

export const it = zip([
  "EstateAI",
  "Area di lavoro per l'elenco",
  "Panoramica",
  "Annunci",
  "AI Listing Writer",
  "Analitica",
  "Guida",
  "Prezzi",
  "Impostazioni",
  "Richieste di preventivo",
  "Spazio di lavoro",
  "Proinventario di proprietà",
  "Studio dei contenuti",
  "Gestione dei lead",
  "Intelligenza del portafoglio",
  "Iniziare",
  "Piani",
  "Preferenze dell'area di lavoro",
  "Attiva/disattiva la navigazione",
  "Contatta lo sviluppatore dell'app",
  "Prova",
  "Wix",
  "Piano",
  "Sul sito sono visibili elenchi illimitati.",
  "{visible} di {cap} elenchi sono visibili sul sito.",
  "Inizia la prova gratuita",
  "Visualizza i piani",
  "È bello vederti",
  "Il tuo spazio di lavoro immobiliare",
  "Mantieni organizzato il tuo inventario, individua rapidamente i movimenti e prepara ogni inserzione per la pubblicazione assistita. Nuovo qui? Segui il {guide}.",
  "guida allo spazio di lavoro",
  "Aggiungi elenco",
  "Riprova",
  "Non è stato possibile caricare la panoramica. Controlla i permessi di raccolta e riprova.",
  "Elenchi totali",
  "In tutto il tuo spazio di lavoro",
  "Attivo",
  "Attualmente disponibile",
  "In offerta",
  "Affrontare un accordo",
  "Venduto",
  "Transazioni completate",
  "Elenchi recenti",
  "Le ultime proprietà aggiunte o aggiornate nell'area di lavoro.",
  "Visualizza tutto",
  "Il tuo inventario è pronto per la prima inserzione",
  "Aggiungi una proprietà per iniziare a monitorare il tuo portafoglio e sbloccare l'analisi.",
  "Annunci aperti",
  "Posizione non impostata",
  "Prossimo focus",
  "Trasforma i dettagli in slancio",
  "Trasforma i tuoi dati immobiliari confermati in testi professionali, di lusso, brevi, SEO o social-ready in pochi secondi.",
  "Apri AI writer",
  "Sblocca AI writer",
  "Gestione dell'inventario",
  "Tutti gli elenchi",
  "Cerca, organizza e mantieni ogni proprietà pronta per la fase successiva.",
  "Il sito attivo mostra le {visible} inserzioni attive aggiornate più di recente del limite del tuo piano {cap}.",
  "Proinventario di proprietà",
  "{count} elenco in questa area di lavoro",
  "{count} elenchi in quest'area di lavoro",
  "Cerca titolo o città",
  "Cerca elenchi",
  "Filtra per stato",
  "Filtra per tipologia di immobile",
  "Stato",
  "Protipo di proprietà",
  "Tutti gli stati",
  "Tutti i tipi",
  "Pagina precedente",
  "Pagina successiva",
  "Pagina {current} di {total}",
  "Azioni per {title}",
  "Modifica",
  "Visitatori unici",
  "Elimina",
  "Non è stato possibile caricare le inserzioni. Controlla i permessi di raccolta e riprova.",
  "Nessun annuncio corrisponde a questi filtri.",
  "Crea la tua prima inserzione o modifica la ricerca e i filtri.",
  "Caricamento elenchi",
  "Tutti i tipi di proprietà",
  "Immagine di copertina",
  "Immagine {n}",
  "Inserisci un titolo per questa inserzione.",
  "Utilizza un codice valuta di tre lettere.",
  "Inserisci un prezzo valido.",
  "Inserisci un'area valida.",
  "Seleziona un paese.",
  "Seleziona uno stato o una regione.",
  "Inserisci la città o la località.",
  "Inserisci l'indirizzo stradale.",
  "Inserisci un indirizzo email valido.",
  "Inserisci un numero di telefono valido.",
  "Inserisci un numero valido.",
  "Inserisci un numero intero.",
  "Il paese in cui si trova l'immobile.",
  "Lo stato, la provincia o la regione in cui si trova l'immobile.",
  "L'unità utilizzata per misurare la superficie della proprietà.",
  "Impossibile caricare i paesi.",
  "Impossibile caricare gli stati.",
  "Impossibile caricare le città.",
  "Le visualizzazioni finora provengono da visitatori non firmati, pertanto non è possibile elencare utenti unici.",
  "Casa contemporanea con 3 camere da letto ad Austin, Texas",
  "<p>Casa luminosa e spaziosa con finiture moderne, ottima luce naturale e garage per due auto. Situato vicino a negozi, ristoranti e alle principali rotte dei pendolari.</p><p>Ideale per professionisti o una famiglia in crescita che cerca una casa confortevole in un quartiere ben collegato.</p>",
  "Piscina, palestra, garage, aria centrale",
  "Visitatori unici",
  "Le persone che hanno visualizzato \"{title}\" sono state contate una volta ciascuna.",
  "Caricamento visitatori unici",
  "Impossibile caricare i visitatori unici. Riprova.",
  "Nessuno ha ancora visualizzato questa inserzione.",
  "{count} visitatore unico",
  "{count} visitatori unici",
  "{count} vista non firmata",
  "{count} visualizzazioni non firmate",
  "{count} vista",
  "{count} visualizzazioni",
  "ultimo {when}",
  "Visitatore registrato",
  "Eliminare questa inserzione?",
  "\"{title}\" verrà rimosso dalle inserzioni attive. Puoi ancora visualizzarlo quando le inserzioni archiviate sono abilitate.",
  "Annulla",
  "Elimina l'elenco",
  "Property",
  "Digitare",
  "Prezzo",
  "Stato",
  "Viste",
  "Aggiornato",
  "Azioni",
  "Studio dei contenuti",
  "Scrivi inserzioni che vengano notate",
  "Aggiungi i dati relativi alla proprietà una volta e lascia che l'intelligenza artificiale li trasformi in una copia di marketing raffinata. Rivedi ogni dettaglio prima di pubblicare.",
  "AI Listing Writer è su Pro e Business",
  "Esegui l'upgrade per generare una copia dell'elenco professionale dai dati della tua proprietà.",
  "Intelligenza del portafoglio",
  "Analisi avanzata",
  "Comprendi il mix di inventario, l'attività e la disponibilità dei contenuti in base ai dati che già disponi.",
  "Aggiorna",
  "Analytics è attivo su Pro e Business",
  "Esegui l'upgrade per visualizzare la combinazione di inventario, l'attività e la disponibilità dei contenuti.",
  "Non è stato possibile calcolare l'analisi. Controlla i permessi di raccolta e riprova.",
  "Inventario monitorato",
  "Elenchi nella collezione",
  "AI-ready contenuto",
  "Elenchi con campi AI popolati",
  "Città attive",
  "Le prime cinque città mostrate di seguito",
  "Segnale di attività",
  "Annunci aggiunti negli ultimi sei mesi",
  "Attività di quotazione",
  "Nuovi record creati negli ultimi sei mesi di calendario.",
  "Le migliori città",
  "Aggiungi località per vedere la concentrazione geografica.",
  "Property mix",
  "Inventario raggruppato per tipo di proprietà.",
  "Aggiungi annunci per vedere il mix delle tue proprietà.",
  "Prezzo medio richiesto",
  "Raggruppati per valuta per mantenere i confronti significativi.",
  "Aggiungi inserzioni per visualizzare i segnali di prezzo.",
  "{count} elenco",
  "{count} elenchi",
  "Stato dell'elenco",
  "Il dettaglio del tuo stato verrà visualizzato una volta aggiunte le inserzioni.",
  "Mix di transazioni",
  "Il tuo mix di transazioni verrà visualizzato una volta aggiunte le inserzioni.",
  "Le analisi vengono calcolate dalla raccolta di elenchi corrente e aggiornate su richiesta.",
  "Nessun dato dell'elenco ancora",
  "Distribuzione attuale nel tuo inventario.",
  "Piani dell'app",
  "Scegli il piano adatto al tuo inventario",
  "La tua prova gratuita include tutte le funzionalità di Business. Al termine, il sito live e gli strumenti controllati seguono il tuo piano attivo.",
  "Inizia il Basic per pubblicare inserzioni e raccogliere preventivi. Esegui l'upgrade a Pro o Business quando hai bisogno di testi AI, tour 360°, analisi e altri strumenti di marketing.",
  "Piano attuale",
  "Prova gratuita",
  "Il più popolare",
  "Confronto delle funzionalità",
  "Cosa è incluso in Basic, Pro e Business.",
  "Caratteristica",
  "Incluso",
  "Non incluso",
  "Basic",
  "Pro",
  "Business",
  "Gratuito",
  "Incluso con l'app",
  "al mese",
  "Pubblica un piccolo inventario e raccogli le richieste dal sito.",
  "Copia AI, tour 360°, approfondimenti sui visitatori e analisi del portafoglio.",
  "Elenchi illimitati, assistente AI in loco e strumenti di marketing completi.",
  "Elenchi attivi",
  "Fino a 10",
  "Fino a 50",
  "Illimitato",
  "Annunci e widget dei dettagli delle proprietà",
  "Contatto del proprietario nelle pagine dell'elenco",
  "Modulo richiesta preventivo",
  "Proprietà salvate per i membri",
  "AI Listing Writer",
  "360° tour virtuale",
  "Informazioni dettagliate sui visitatori unici",
  "Analisi del portafoglio",
  "Condivisione social sulle pagine degli elenchi",
  "Notifiche email per richieste di preventivo",
  "Assistente AI della proprietà in loco",
  "Elenchi correlati sulle pagine delle proprietà",
  "Molteplici scene del tour 360°",
  "Supporto prioritario",
  "Preferenze dell'area di lavoro",
  "Impostazioni",
  "Imposta impostazioni predefinite sensate per i nuovi elenchi e mantieni lo spazio di lavoro concentrato sui record che il tuo team sta gestendo attivamente.",
  "Impostazioni predefinite dell'elenco",
  "Queste preferenze precompilano i nuovi elenchi. I record esistenti non vengono modificati.",
  "Valuta predefinita",
  "La valuta preselezionata per i nuovi prezzi di quotazione.",
  "Scegli dall'elenco completo delle valute ISO 4217.",
  "Unità di area predefinita",
  "L'unità di misura preselezionata per le nuove aree dell'elenco.",
  "Applicato al campo area sui nuovi record.",
  "Stato dell'elenco predefinito",
  "Lo stato del flusso di lavoro assegnato alle nuove inserzioni.",
  "I nuovi elenchi si aprono con questa fase del flusso di lavoro.",
  "Includi elenchi archiviati",
  "Se abilitate, le inserzioni archiviate appaiono nella visualizzazione delle inserzioni per impostazione predefinita.",
  "Mantieni i record archiviati visibili nella vista Elenchi per impostazione predefinita.",
  "Lingua del dashboard",
  "Scegli la lingua per quest'area di lavoro o segui la lingua dell'account Wix.",
  "Auto (Wix account language)",
  "Salvato localmente per questo browser",
  "Le modifiche non sono ancora state salvate",
  "Ripristina",
  "Salva impostazioni",
  "Impostazioni dell'area di lavoro salvate.",
  "Impossibile salvare le impostazioni in questo browser.",
  "Saved Properties programma di avvio",
  "Incorpora o ripristina il pulsante e il drawer delle proprietà salvate dei membri sul tuo sito live.",
  "Sicuro da eseguire più di una volta.",
  "Incorpora il programma di avvio",
  "Incorporamento...",
  "Il launcher Saved Properties è attivo sul sito.",
  "Non è stato possibile incorporare il launcher.",
  "Aiuto: {hint}",
  "Gestione dei lead",
  "Richieste di preventivo",
  "Esamina le richieste di informazioni sulle proprietà e mantieni aggiornato lo stato di follow-up.",
  "Richieste in arrivo",
  "{count} richiesta",
  "{count} richieste",
  "Cerca proprietà",
  "Cerca richieste di preventivo",
  "Filtra le richieste di preventivo per stato",
  "Aggiorna le richieste di preventivo",
  "Impossibile caricare le richieste di preventivo.",
  "Impossibile aggiornare la richiesta.",
  "Nessuna richiesta di preventivo corrisponde a questi filtri.",
  "Nessun messaggio fornito.",
  "Note interne",
  "Note per {title}",
  "Stato per {title}",
  "Archivio",
  "Pagina {current}",
  "Precedente",
  "Avanti",
  "Nuovo",
  "Contattato",
  "Citato",
  "Chiuso",
  "Iniziare",
  "Come utilizzare questo spazio di lavoro",
  "Crea elenchi qui, pubblicali con i widget del sito, quindi segui le richieste di preventivo e l'attività dei visitatori da questa dashboard.",
  "Percorso consigliato",
  "Aggiungi almeno un elenco attivo, posiziona i widget sul tuo sito, quindi controlla Richieste di preventivo dopo che un visitatore ha inviato una richiesta.",
  "Passaggio {n}",
  "Creare e gestire inserzioni",
  "Conserva ogni proprietà in un unico inventario.",
  "Aggiungi un annuncio con posizione, prezzo, immagini e un tour 360° opzionale.",
  "Il contatto dell'agente/proprietario viene compilato dal proprietario del sito e può essere modificato per elenco.",
  "Utilizza il menu delle azioni dell'elenco per modificare, rivedere i visitatori unici o eliminare.",
  "Sul sito live vengono visualizzati solo gli annunci attivi.",
  "Pubblica annunci sul sito",
  "Mostra i dettagli dell'inventario e della proprietà ai visitatori.",
  "Aggiungi il widget degli annunci immobiliari a una pagina come /properties.",
  "Aggiungi il widget dei dettagli della proprietà a una pagina come /property-details.",
  "Nell'editor, attiva o disattiva Contatto, richiesta di preventivo, condivisione ed elenchi correlati.",
  "Incorpora il launcher Saved Properties da Impostazioni in modo che i membri possano aggiungere case ai preferiti.",
  "Apri le impostazioni",
  "Gestire le richieste dei visitatori",
  "Consenti agli acquirenti di contattarti senza uscire dall'inserzione.",
  "I visitatori vedono il nome, il telefono e l'e-mail del proprietario nella pagina delle proprietà quando Contatto è abilitato.",
  "Richiedi un preventivo raccoglie nome, email, telefono e un messaggio formattato.",
  "Le nuove richieste vengono visualizzate qui con stato, note e archivio.",
  "Le notifiche di preventivo utilizzano l'e-mail dell'agente di quotazione e l'e-mail del proprietario del sito.",
  "Apri richieste di preventivo",
  "Scrivi la copia dell'elenco con AI",
  "Trasforma i fatti in descrizioni pronte per il marketing.",
  "Apri AI Listing Writer o utilizza Scrivi con AI all'interno dell'editor delle inserzioni.",
  "Esamina la copia generata, quindi salvala nell'elenco prima della pubblicazione.",
  "Utilizza Analytics per vedere quali inserzioni attirano il maggior numero di visualizzazioni.",
  "Hai bisogno di più aiuto",
  "Impostazioni predefinite e supporto dell'area di lavoro",
  "Imposta la valuta, l'unità di zona e lo stato predefiniti in Impostazioni. Contatta lo sviluppatore dell'app dalla barra laterale se un widget o una raccolta mancano dopo l'installazione.",
  "Aggiungi elenco",
  "Modifica elenco",
  "Mantieni le informazioni sulla tua proprietà accurate e pronte per la pubblicazione.",
  "Impossibile aprire questa inserzione",
  "Ritorna agli elenchi",
  "Impossibile trovare questo elenco.",
  "Impossibile caricare questa inserzione.",
  "{title} è stato aggiornato.",
  "{title} è stato aggiunto.",
  "Impossibile salvare l'elenco.",
  "{title} è stato archiviato.",
  "Impossibile archiviare l'elenco.",
  "Crea una nuova inserzione",
  "Modifica i dettagli dell'annuncio",
  "Probella storia",
  "Utilizza l'editor per aggiungere una descrizione chiara e strutturata.",
  "Titolo",
  "Un nome conciso che identifica questa proprietà.",
  "Casa luminosa con 3 camere da letto ad Austin, Texas",
  "Descrizione",
  "Descrivi la proprietà, la disposizione, le finiture e i punti di forza.",
  "Scrivi con l'intelligenza artificiale",
  "AI writer (Pro)",
  "Caricamento editor…",
  "Indirizzo",
  "Inserisci l'indirizzo o i dettagli sulla posizione della proprietà.",
  "Indirizzo o quartiere",
  "Città",
  "Scegli una città suggerita o inseriscine una manualmente.",
  "Inserisci o seleziona una città",
  "Paese",
  "Stato/regione",
  "Elenco immagini",
  "Scegli le immagini da Wix Media Manager; la prima immagine è la copertina.",
  "La prima immagine viene utilizzata come copertina sulle schede e sulla pagina delle proprietà.",
  "Scegli le immagini",
  "Aggiungi immagini",
  "Nessuna immagine ancora selezionata.",
  "Rimuovi immagine {n}",
  "360° tour virtuale",
  "Aggiungi foto equirettangolari 360° per il visualizzatore interattivo Three.js. I visitatori possono passare da una stanza all'altra e da un punto di vista all'altro.",
  " I tour virtuali sono inclusi su Pro e Business; le immagini extra rimangono nella dashboard se le aggiungi ora.",
  " I siti Pro mostrano la prima scena; scene aggiuntive verranno pubblicate su Business.",
  "360° immagini panoramiche",
  "Scegli immagini 360° equirettangolari per il visualizzatore interattivo Three.js. I visitatori possono passare da una scena all'altra.",
  "Facoltativo. Ogni immagine deve essere una foto 360° equirettangolare.",
  "Nessun panorama 360° selezionato.",
  "Rimuovi panorama {n}",
  "Scena {n}",
  "Elenco dei fatti",
  "Questi campi alimentano i filtri e l'analisi del portafoglio.",
  "Tipo di transazione",
  "Se l'immobile è in vendita, in affitto o in locazione.",
  "La categoria che meglio descrive l'immobile.",
  "La fase attuale del flusso di lavoro per questa inserzione.",
  "Properfette condizioni",
  "Lo stato fisico attuale dell'immobile.",
  "Stato dell'arredamento",
  "Indica se l'immobile è non arredato, parzialmente arredato o arredato.",
  "Mandato",
  "Il contratto di proprietà o di locazione dell'immobile.",
  "Frequenza del noleggio",
  "La frequenza con cui è previsto l'affitto per gli annunci di noleggio o locazione.",
  "Prezzo",
  "Il prezzo di inserzione nella valuta selezionata.",
  "Valuta",
  "La valuta di tre lettere utilizzata per il prezzo di quotazione.",
  "Zona",
  "La dimensione della proprietà nell'unità di area selezionata.",
  "Unità di zona",
  "Servizi",
  "Elenca le caratteristiche notevoli separate da virgole.",
  "Piscina, palestra, sicurezza 24 ore su 24, 7 giorni su 7",
  "Data di disponibilità",
  "La data in cui l'immobile diventa disponibile.",
  "Contatto agente/proprietario",
  "Nome",
  "L'agente o il proprietario responsabile di questa inserzione.",
  "Nome dell'agente o del proprietario",
  "Telefono",
  "Un numero di telefono per richieste di annunci.",
  "Numero di telefono internazionale",
  "E-mail",
  "Un indirizzo email per le richieste di quotazione.",
  "Posizionamento sulla mappa",
  "Latitudine",
  "La latitudine della proprietà utilizzata per il posizionamento sulla mappa.",
  "Longitudine",
  "La longitudine della proprietà utilizzata per il posizionamento sulla mappa.",
  "Salva l'elenco",
  "Salvataggio…",
  "AI writer",
  "I fatti di questo elenco sono compilati per te. Al termine della scrittura, la descrizione sul modulo si aggiorna automaticamente.",
  "La descrizione dell'annuncio è stata aggiornata.",
  "Impossibile aprire Media Manager.",
  "Seleziona {label}",
  "Valore {label} facoltativo per questa scheda.",
  "Facoltativo",
  "Camere da letto",
  "Bagni",
  "Anno di costruzione",
  "Parcheggi",
  "Costo del servizio",
  "Deposito cauzionale",
  "Obbligatorio",
  "Aggiungi un titolo.",
  "Aggiungi un indirizzo.",
  "Aggiungi una città.",
  "Aggiungi un prezzo.",
  "Aggiungi un'area.",
  "Correggi i campi evidenziati prima di salvare.",
  "Impossibile caricare i suggerimenti sulla posizione. È ancora possibile digitare valori.",
  "Property nozioni di base",
  "Cosa dovrebbe dire la descrizione?",
  "Posizione",
  "Austin, Texas",
  "$ 875.000",
  "Piscina, palestra, parcheggio",
  "Stile di scrittura",
  "Genera descrizione",
  "Scrivendo la tua descrizione...",
  "Descrizione generata",
  "Al termine della scrittura, questa copia viene aggiunta alla descrizione dell'inserzione.",
  "Controlla la copia, quindi copiala nella tua inserzione.",
  "Copia",
  "Copiato",
  "Descrizione della proprietà generata",
  "La tua copia raffinata apparirà qui",
  "Scegli uno stile e genera una descrizione dai fatti confermati della proprietà.",
  "Proprofessionale",
  "Chiaro e affidabile",
  "Lusso",
  "Elevato e ambizioso",
  "Breve",
  "Perfetto per le carte",
  "Ottimizzato SEO",
  "Copia facilmente ricercabile",
  "Mezzi sociali",
  "Coinvolgente e condivisibile",
  "Arredato",
  "Semiarredato",
  "Non arredato",
  "Impossibile generare la descrizione.",
  "AI Listing Writer è disponibile su Pro e Business.",
  "Condividi la copia della tua inserzione",
  "Raggiungi gli acquirenti ovunque trascorrano del tempo.",
  "Aggiungi canali",
  "Più canali di condivisione",
  "Scegli una piattaforma per condividere la copia dell'inserzione generata. Alcuni canali copiano prima la didascalia in modo da poter aggiungere foto e pubblicarla in modo naturale.",
  "WhatsApp",
  "Invia a un contatto o un gruppo",
  "Facebook",
  "Condividi sul tuo feed",
  "Instagram",
  "Copia didascalia e apri Instagram",
  "X",
  "Pubblica sulla tua cronologia",
  "LinkedIn",
  "Condividi con la tua rete",
  "Telegram",
  "Invia a una chat o un canale",
  "Pinterest",
  "Copia la didascalia e apri Pinterest",
  "Reddit",
  "Invia a una comunità",
  "Threads",
  "Copia didascalia e apri Threads",
  "TikTok",
  "Copia la didascalia e apri TikTok",
  "YouTube",
  "Copia la didascalia e apri YouTube",
  "Snapchat",
  "Copia la didascalia e apri Snapchat",
  "E-mail",
  "Apri l'app di posta elettronica",
  "Messaggio di testo",
  "Invia come messaggio di testo",
  "Proelenco proprietà",
  "Descrizione dell'elenco",
  "Descrivi la luce, la disposizione, le finiture e i motivi per amare questa proprietà...",
  "Impossibile aggiungere immagini alla descrizione.",
  "Impossibile aggiungere video alla descrizione.",
  "Bozza",
  "Attivo",
  "In offerta",
  "Venduto",
  "Archiviato",
  "In vendita",
  "In affitto",
  "Per locazione",
  "Casa",
  "Appartamento",
  "Condominio",
  "Casa a schiera",
  "Terra",
  "Ufficio",
  "Vendita al dettaglio",
  "Industriale",
  "Uso misto",
  "Altro",
  "Piedi quadrati",
  "Metri quadrati",
  "Acri",
  "Nuovo",
  "Bene",
  "Necessita di ristrutturazione",
  "Proprietà libera",
  "Beni di locazione",
  "Mensile",
  "Annuale",
  "Metri quadrati",
  "Acri",
  "Nuovo",
  "Bene",
  "Necessita di ristrutturazione",
  "Proprietà libera",
  "Beni di locazione",
  "Mensile",
  "Annuale",
  "English",
  "中文",
  "हिन्दी",
  "Español",
  "العربية",
  "Français",
  "বাংলা",
  "Português",
  "Русский",
  "اردو",
  "Bahasa Indonesia",
  "Deutsch",
  "日本語",
  "Kiswahili",
  "Türkçe",
  "한국어",
  "Tiếng Việt",
  "Italiano",
  "ไทย",
  "Polski",
]);
