import { zip } from "../zip";

export const pl = zip([
  "EstateAI",
  "Obszar roboczy aukcji",
  "Przegląd",
  "Oferty",
  "AI Listing Writer",
  "Analityka",
  "Przewodnik",
  "Ceny",
  "Ustawienia",
  "Prośby o wycenę",
  "Obszar roboczy",
  "Proinwentarz nieruchomości",
  "Studio treści",
  "Zarządzanie leadami",
  "Inteligencja portfelowa",
  "Rozpoczęcie",
  "Plany",
  "Preferencje obszaru roboczego",
  "Przełącz nawigację",
  "Skontaktuj się z twórcą aplikacji",
  "Próba",
  "Wix",
  "Planuj",
  "Na stronie widoczne są nieograniczone oferty.",
  "{visible} z {cap} wpisów jest widocznych w witrynie.",
  "Rozpocznij bezpłatny okres próbny",
  "Zobacz plany",
  "Miło cię widzieć",
  "Twoje miejsce do pracy w branży nieruchomości",
  "Utrzymuj porządek w swoim ekwipunku, szybko wykrywaj zmiany i przygotowuj każdą aukcję do wspomaganego publikowania. Nowy tutaj? Postępuj zgodnie z {guide}.",
  "przewodnik po obszarze roboczym",
  "Dodaj listę",
  "Spróbuj ponownie",
  "Nie mogliśmy załadować Twojego przeglądu. Sprawdź uprawnienia do zbierania i spróbuj ponownie.",
  "Łączna liczba ofert",
  "W całym obszarze roboczym",
  "Aktywny",
  "Obecnie dostępne",
  "W ramach oferty",
  "Przechodzenie przez umowę",
  "Sprzedane",
  "Zakończone transakcje",
  "Najnowsze zestawienia",
  "Najnowsze właściwości dodane lub zaktualizowane w Twoim obszarze roboczym.",
  "Zobacz wszystkie",
  "Twój ekwipunek jest gotowy na pierwszą aukcję",
  "Dodaj usługę, aby rozpocząć śledzenie swojego portfolio i odblokować analitykę.",
  "Otwórz oferty",
  "Lokalizacja nie została ustawiona",
  "Następne skupienie",
  "Zamień szczegóły w dynamikę",
  "Zamień potwierdzone fakty dotyczące nieruchomości w profesjonalną, luksusową, krótką kopię, SEO lub gotową do użytku społecznościowego w ciągu kilku sekund.",
  "Otwórz AI writer",
  "Odblokuj AI writer",
  "Zarządzanie zapasami",
  "Wszystkie zestawienia",
  "Wyszukuj, organizuj i dbaj o to, aby każda nieruchomość była gotowa na kolejny etap.",
  "Aktywna witryna wyświetla {visible} ostatnio zaktualizowane aktywne wykazy Twojego planu {cap}.",
  "Proinwentarz nieruchomości",
  "{count} wpis w tym obszarze roboczym",
  "{count} wpisy w tym obszarze roboczym",
  "Wyszukaj tytuł lub miasto",
  "Przeszukaj oferty",
  "Filtruj według stanu",
  "Filtruj według typu nieruchomości",
  "Stan",
  "Protyp właściwości",
  "Wszystkie statusy",
  "Wszystkie typy",
  "Poprzednia strona",
  "Następna strona",
  "Strona {current} z {total}",
  "Działania dla {title}",
  "Edytuj",
  "Wyjątkowi goście",
  "Usuń",
  "Nie udało się wczytać ofert. Sprawdź uprawnienia do zbierania i spróbuj ponownie.",
  "Żadne oferty nie pasują do tych filtrów.",
  "Utwórz swój pierwszy wpis lub dostosuj wyszukiwanie i filtry.",
  "Ładowanie aukcji",
  "Wszystkie typy nieruchomości",
  "Obraz na okładce",
  "Obraz {n}",
  "Wpisz tytuł tej aukcji.",
  "Użyj trzyliterowego kodu waluty.",
  "Wprowadź prawidłową cenę.",
  "Wprowadź prawidłowy obszar.",
  "Wybierz kraj.",
  "Wybierz stan lub region.",
  "Wpisz miasto lub miejscowość.",
  "Wprowadź adres ulicy.",
  "Wpisz prawidłowy adres e-mail.",
  "Wpisz prawidłowy numer telefonu.",
  "Wprowadź prawidłowy numer.",
  "Wprowadź liczbę całkowitą.",
  "Kraj, w którym znajduje się nieruchomość.",
  "Stan, prowincja lub region, w którym znajduje się nieruchomość.",
  "Jednostka używana do pomiaru powierzchni nieruchomości.",
  "Nie udało się wczytać krajów.",
  "Nie udało się wczytać stanów.",
  "Nie udało się wczytać miast.",
  "Dotychczasowe wyświetlenia pochodzą od niepodpisanych użytkowników, dlatego nie można wyświetlić listy unikalnych użytkowników.",
  "Współczesny dom z 3 sypialniami w Austin w Teksasie",
  "<p>Jasny i przestronny dom z nowoczesnymi wykończeniami, doskonałym naturalnym światłem i garażem na dwa samochody. Położony w pobliżu sklepów, restauracji i głównych tras dojazdowych.</p><p>Idealny dla profesjonalistów lub rosnącej rodziny szukającej wygodnego domu w dobrze skomunikowanej okolicy.</p>",
  "Basen, siłownia, garaż, centralne powietrze",
  "Wyjątkowi goście",
  "Osoby, które obejrzały „{title}”, liczyły się raz.",
  "Ładowanie unikalnych gości",
  "Nie można załadować unikalnych gości. Spróbuj ponownie.",
  "Nikt jeszcze nie przeglądał tego ogłoszenia.",
  "{count} unikalny gość",
  "{count} unikalnych gości",
  "{count} widok bez znaku",
  "{count} niepodpisane widoki",
  "Widok {count}",
  "{count} wyświetleń",
  "ostatni {when}",
  "Zalogowany gość",
  "Usunąć tę ofertę?",
  "„{title}” zostanie usunięty z aktywnych aukcji. Nadal możesz je przeglądać, gdy włączone są zarchiwizowane aukcje.",
  "Anuluj",
  "Usuń wpis",
  "Prowłaściwość",
  "Wpisz",
  "Cena",
  "Stan",
  "Widoki",
  "Zaktualizowano",
  "Działania",
  "Studio treści",
  "Napisz ogłoszenia, które zostaną zauważone",
  "Dodaj raz fakty dotyczące nieruchomości i pozwól sztucznej inteligencji przekształcić je w dopracowaną kopię marketingową. Przed publikacją przejrzyj każdy szczegół.",
  "AI Listing Writer jest na Pro i Business",
  "Uaktualnij, aby wygenerować profesjonalną kopię ogłoszenia na podstawie faktów dotyczących nieruchomości.",
  "Inteligencja portfelowa",
  "Zaawansowana analityka",
  "Zrozum swój asortyment zasobów, aktywność i gotowość do treści na podstawie danych, które już posiadasz.",
  "Odśwież",
  "Analityka jest dostępna w Pro i Business",
  "Uaktualnij, aby zobaczyć asortyment, aktywność i gotowość treści.",
  "Nie mogliśmy obliczyć danych analitycznych. Sprawdź uprawnienia do zbierania i spróbuj ponownie.",
  "Śledzone zasoby",
  "Oferty w kolekcji",
  "AI-ready treść",
  "Oferty z wypełnionymi polami AI",
  "Aktywne miasta",
  "Poniżej pięć najlepszych miast",
  "Sygnał aktywności",
  "Oferty dodane w ciągu ostatnich sześciu miesięcy",
  "Aktywność aukcji",
  "Nowe rekordy utworzone w ciągu ostatnich sześciu miesięcy kalendarzowych.",
  "Najlepsze miasta",
  "Dodaj lokalizacje, aby zobaczyć koncentrację geograficzną.",
  "Properfekcyjna mieszanka",
  "Zasoby pogrupowane według typu nieruchomości.",
  "Dodaj oferty, aby zobaczyć zestawienie swoich nieruchomości.",
  "Średnia cena wywoławcza",
  "Pogrupowane według waluty, aby porównania były sensowne.",
  "Dodaj oferty, aby zobaczyć sygnały cenowe.",
  "{count} wpis",
  "{count} wpisy",
  "Stan aukcji",
  "Po dodaniu ofert pojawi się zestawienie Twojego statusu.",
  "Mieszanka transakcyjna",
  "Twój zestaw transakcji pojawi się po dodaniu ofert.",
  "Analizy są obliczane na podstawie aktualnej kolekcji ofert i odświeżane na żądanie.",
  "Nie ma jeszcze danych o aukcji",
  "Bieżąca dystrybucja w Twoim magazynie.",
  "Plany aplikacji",
  "Wybierz plan, który pasuje do Twojego ekwipunku",
  "Twój bezpłatny okres próbny obejmuje każdą funkcję Business. Po jego zakończeniu działająca witryna i narzędzia z bramkami będą działać zgodnie z Twoim aktywnym planem.",
  "Zacznij od Basic, aby publikować oferty i zbierać wyceny. Przejdź na Pro lub Business, jeśli potrzebujesz kopii AI, wycieczek 360°, analiz i innych narzędzi marketingowych.",
  "Aktualny plan",
  "Bezpłatny okres próbny",
  "Najpopularniejszy",
  "Porównanie funkcji",
  "Co obejmuje Basic, Pro i Business.",
  "Funkcja",
  "Uwzględnione",
  "Nieuwzględnione",
  "Basic",
  "Pro",
  "Business",
  "Bezpłatny",
  "Dołączone do aplikacji",
  "miesięcznie",
  "Publikuj niewielki asortyment i zbieraj zapytania z witryny.",
  "Kopia AI, wycieczki 360°, spostrzeżenia odwiedzających i analizy portfolio.",
  "Nieograniczone oferty, asystent AI na miejscu i pełne narzędzia marketingowe.",
  "Aktywne oferty",
  "Do 10",
  "Do 50",
  "Nieograniczony",
  "Oferty i widżety szczegółów nieruchomości",
  "Kontakt z właścicielem na stronach aukcji",
  "Formularz zapytania ofertowego",
  "Zapisane właściwości członków",
  "AI Listing Writer",
  "360° wirtualny spacer",
  "Unikalne spostrzeżenia odwiedzających",
  "Analityka portfelowa",
  "Udostępnianie społecznościowe na stronach z listami",
  "Powiadomienia e-mail z prośbą o wycenę",
  "Asystent AI nieruchomości na miejscu",
  "Powiązane wpisy na stronach nieruchomości",
  "Wiele scen z trasy 360°",
  "Wsparcie priorytetowe",
  "Preferencje obszaru roboczego",
  "Ustawienia",
  "Ustaw rozsądne ustawienia domyślne dla nowych wpisów i skup obszar roboczy na rekordach, którymi aktywnie zarządza Twój zespół.",
  "Domyślne ustawienia aukcji",
  "Te preferencje wstępnie wypełniają nowe aukcje. Istniejące zapisy nie ulegają zmianie.",
  "Domyślna waluta",
  "Waluta wybrana dla nowych cen ofertowych.",
  "Wybierz z pełnej listy walut ISO 4217.",
  "Domyślna jednostka powierzchni",
  "Jednostka miary wybrana wstępnie dla nowych obszarów ofert.",
  "Zastosowano do pola obszaru w przypadku nowych rekordów.",
  "Domyślny stan aukcji",
  "Status przepływu pracy przypisany do nowych ofert.",
  "Nowe oferty otwierają się na tym etapie przepływu pracy.",
  "Uwzględnij zarchiwizowane oferty",
  "Po włączeniu zarchiwizowane aukcje domyślnie pojawiają się w widoku Oferty.",
  "Domyślnie przechowuj zarchiwizowane rekordy w widoku Listy.",
  "Język panelu",
  "Wybierz język tego obszaru roboczego lub zastosuj język konta Wix.",
  "Auto (Wix account language)",
  "Zapisane lokalnie dla tej przeglądarki",
  "Zmiany nie zostały jeszcze zapisane",
  "Zresetuj",
  "Zapisz ustawienia",
  "Ustawienia obszaru roboczego zostały zapisane.",
  "Nie można zapisać ustawień w tej przeglądarce.",
  "Program uruchamiający Saved Properties",
  "Umieść lub przywróć przycisk i szufladę zapisanych właściwości członków w działającej witrynie.",
  "Bezpieczne uruchomienie więcej niż raz.",
  "Umieść program uruchamiający",
  "Osadzanie…",
  "Program uruchamiający Saved Properties jest aktywny na stronie.",
  "Nie można osadzić programu uruchamiającego.",
  "Pomoc: {hint}",
  "Zarządzanie leadami",
  "Prośby o wycenę",
  "Przeglądaj zapytania dotyczące nieruchomości i aktualizuj na bieżąco ich status.",
  "Przychodzące żądania",
  "{count} żądanie",
  "Żądania {count}",
  "Wyszukaj nieruchomość",
  "Wyszukaj prośby o wycenę",
  "Filtruj zapytania ofertowe według statusu",
  "Odśwież prośby o wycenę",
  "Nie można wczytać próśb o wycenę.",
  "Nie udało się zaktualizować żądania.",
  "Żadne prośby o wycenę nie pasują do tych filtrów.",
  "Brak wiadomości.",
  "Notatki wewnętrzne",
  "Notatki dla {title}",
  "Stan dla {title}",
  "Archiwum",
  "Strona {current}",
  "Poprzedni",
  "Następny",
  "Nowy",
  "Skontaktowano się",
  "Cytowane",
  "Zamknięte",
  "Rozpoczęcie",
  "Jak korzystać z tego obszaru roboczego",
  "Twórz tutaj oferty, publikuj je za pomocą widżetów witryny, a następnie śledź prośby o wycenę i aktywność odwiedzających z tego pulpitu nawigacyjnego.",
  "Zalecana ścieżka",
  "Dodaj co najmniej jedną aktywną ofertę, umieść widżety na swojej stronie, a następnie sprawdź Zapytania ofertowe po tym, jak odwiedzający prześle zapytanie.",
  "Krok {n}",
  "Twórz oferty i zarządzaj nimi",
  "Trzymaj każdą nieruchomość w jednym ekwipunku.",
  "Dodaj ogłoszenie z lokalizacją, ceną, zdjęciami i opcjonalną wycieczką 360°.",
  "Kontakt agenta/właściciela jest wypełniany przez właściciela witryny i można go edytować w każdym wpisie.",
  "Użyj menu działań na liście, aby edytować, przeglądać unikalnych gości lub usuwać.",
  "W aktywnej witrynie pojawiają się tylko aktywne oferty.",
  "Publikuj ogłoszenia na stronie",
  "Pokaż odwiedzającym szczegóły inwentarza i nieruchomości.",
  "Dodaj widżet ofert nieruchomości do strony takiej jak /properties.",
  "Dodaj widżet szczegółów właściwości do strony takiej jak /property-details.",
  "W edytorze włącz lub wyłącz opcję Kontakt, Zapytanie o wycenę, Udostępnianie i powiązane oferty.",
  "Umieść program uruchamiający Saved Properties w Ustawieniach, aby członkowie mogli dodawać do zakładek domy.",
  "Otwórz ustawienia",
  "Obsługuj zapytania gości",
  "Pozwól kupującym kontaktować się z Tobą bez opuszczania aukcji.",
  "Gdy włączona jest opcja Kontakt, odwiedzający widzą nazwę właściciela, telefon i adres e-mail na stronie obiektu.",
  "Zapytanie o wycenę zbiera imię i nazwisko, adres e-mail, telefon i sformatowaną wiadomość.",
  "Tutaj pojawiają się nowe prośby ze statusem, notatkami i archiwum.",
  "Powiadomienia o wycenach wysyłane są na adres e-mail agenta aukcji i adres e-mail właściciela witryny.",
  "Otwórz prośby o wycenę",
  "Napisz kopię aukcji za pomocą AI",
  "Zamień fakty w gotowe opisy marketingowe.",
  "Otwórz AI Listing Writer lub użyj funkcji Write with AI w edytorze aukcji.",
  "Przejrzyj wygenerowaną kopię, a następnie zapisz ją na aukcji przed publikacją.",
  "Użyj Analytics, aby zobaczyć, które oferty przyciągają najwięcej wyświetleń.",
  "Potrzebujesz dalszej pomocy",
  "Domyślne ustawienia obszaru roboczego i obsługa",
  "Ustaw domyślną walutę, jednostkę powierzchni i status w Ustawieniach. Jeśli po instalacji brakuje widżetu lub kolekcji, skontaktuj się z twórcą aplikacji na pasku bocznym.",
  "Dodaj listę",
  "Edytuj listę",
  "Zadbaj o to, aby informacje o Twojej nieruchomości były dokładne i gotowe do publikacji.",
  "Nie można otworzyć tej aukcji",
  "Wróć do zestawień",
  "Nie udało się znaleźć tego wpisu.",
  "Nie można załadować tego wpisu.",
  "{title} został zaktualizowany.",
  "Dodano {title}.",
  "Nie udało się zapisać wpisu.",
  "{title} został zarchiwizowany.",
  "Nie udało się zarchiwizować wpisu.",
  "Utwórz nowy wpis",
  "Edytuj szczegóły aukcji",
  "Proprzepiękna historia",
  "Użyj edytora, aby dodać dopracowany, uporządkowany opis.",
  "Tytuł",
  "Zwięzła nazwa identyfikująca tę właściwość.",
  "Wypełniony światłem dom z 3 sypialniami w Austin w Teksasie",
  "Opis",
  "Opisz nieruchomość, układ, wykończenia i zalety.",
  "Pisz z AI",
  "AI writer (Pro)",
  "Ładowanie edytora…",
  "Adres",
  "Wprowadź adres lub szczegóły lokalizacji nieruchomości.",
  "Adres ulicy lub okolica",
  "Miasto",
  "Wybierz sugerowane miasto lub wprowadź je ręcznie.",
  "Wpisz lub wybierz miasto",
  "Kraj",
  "Stan/region",
  "Lista obrazów",
  "Wybierz obrazy z Wix Media Manager; pierwsze zdjęcie to okładka.",
  "Pierwszy obraz służy jako okładka kart i strony nieruchomości.",
  "Wybierz obrazy",
  "Dodaj obrazy",
  "Nie wybrano jeszcze żadnych obrazów.",
  "Usuń obraz {n}",
  "360° wirtualny spacer",
  "Dodaj równoprostokątne zdjęcia 360° do interaktywnej przeglądarki Three.js. Odwiedzający mogą przełączać się między pokojami i punktami widokowymi.",
  " Wirtualne wycieczki są dostępne w Pro i Business; dodatkowe obrazy pozostaną w panelu, jeśli dodasz je teraz.",
  " Strony Pro przedstawiają pierwszą scenę; dodatkowe sceny zostaną wyemitowane w Business.",
  "360° obrazy panoramiczne",
  "Wybierz obrazy równoprostokątne 360° dla interaktywnej przeglądarki Three.js. Zwiedzający mogą przełączać się między scenami.",
  "Opcjonalne. Każde zdjęcie powinno być zdjęciem równoprostokątnym 360°.",
  "Nie wybrano panoram 360°.",
  "Usuń panoramę {n}",
  "Scena {n}",
  "Lista faktów",
  "Pola te zasilają filtry i analizę portfela.",
  "Typ transakcji",
  "Niezależnie od tego, czy nieruchomość jest na sprzedaż, do wynajęcia czy w dzierżawę.",
  "Kategoria, która najlepiej opisuje nieruchomość.",
  "Bieżący etap przepływu pracy dla tej aukcji.",
  "Prostan własności",
  "Aktualny stan fizyczny nieruchomości.",
  "Stan umeblowania",
  "Czy nieruchomość jest nieumeblowana, częściowo umeblowana czy umeblowana.",
  "Kadencja",
  "Umowa własności lub dzierżawy nieruchomości.",
  "Częstotliwość wynajmu",
  "Jak często spodziewany jest czynsz w przypadku ofert wynajmu lub dzierżawy.",
  "Cena",
  "Cena ofertowa w wybranej walucie.",
  "Waluta",
  "Trzyliterowa waluta używana w cenie ofertowej.",
  "Obszar",
  "Rozmiar nieruchomości w wybranej jednostce powierzchni.",
  "Jednostka powierzchni",
  "Udogodnienia",
  "Wymień ważne funkcje oddzielone przecinkami.",
  "Basen, siłownia, całodobowa ochrona",
  "Data dostępności",
  "Data, w której nieruchomość staje się dostępna.",
  "Kontakt z agentem/właścicielem",
  "Imię",
  "Agent lub właściciel odpowiedzialny za tę ofertę.",
  "Imię agenta lub właściciela",
  "Telefon",
  "Numer telefonu do zapytań o aukcję.",
  "Międzynarodowy numer telefonu",
  "E-mail",
  "Adres e-mail do zapytań o aukcję.",
  "Umiejscowienie mapy",
  "Szerokość geograficzna",
  "Szerokość geograficzna właściwości używana do umieszczania mapy.",
  "Długość geograficzna",
  "Długość geograficzna nieruchomości używana do umieszczania mapy.",
  "Zapisz listę",
  "Zapisuję…",
  "AI writer",
  "Fakty z tego zestawienia są wypełnione za Ciebie. Po zakończeniu pisania opis w formularzu zostanie automatycznie zaktualizowany.",
  "Opis aukcji został zaktualizowany.",
  "Nie można otworzyć Media Manager.",
  "Wybierz {label}",
  "Opcjonalna wartość {label} dla tego wpisu.",
  "Opcjonalne",
  "Sypialnie",
  "Łazienki",
  "Rok budowy",
  "Miejsca parkingowe",
  "Opłata za usługę",
  "Kaucja zabezpieczająca",
  "Wymagane",
  "Dodaj tytuł.",
  "Dodaj adres.",
  "Dodaj miasto.",
  "Dodaj cenę.",
  "Dodaj obszar.",
  "Napraw podświetlone pola przed zapisaniem.",
  "Nie udało się wczytać sugestii lokalizacji. Nadal możesz wpisywać wartości.",
  "Propodstawy własności",
  "Co powinien zawierać opis?",
  "Lokalizacja",
  "Austin, Teksas",
  "875 000 dolarów",
  "Basen, siłownia, parking",
  "Styl pisania",
  "Wygeneruj opis",
  "Piszę opis…",
  "Wygenerowany opis",
  "Po zakończeniu pisania ta kopia zostanie dodana do opisu aukcji.",
  "Przejrzyj kopię, a następnie skopiuj ją do swojej aukcji.",
  "Kopiuj",
  "Skopiowano",
  "Wygenerowany opis nieruchomości",
  "Twoja dopracowana kopia pojawi się tutaj",
  "Wybierz styl i wygeneruj opis na podstawie potwierdzonych faktów dotyczących nieruchomości.",
  "Profesjonalny",
  "Jasne i godne zaufania",
  "Luksus",
  "Podniosły i aspirujący",
  "Krótkie",
  "Idealny do kartek",
  "Zoptymalizowane pod kątem SEO",
  "Kopia przyjazna dla wyszukiwania",
  "Media społecznościowe",
  "Angażujące i dające się dzielić",
  "Umeblowane",
  "Częściowo umeblowane",
  "Nieumeblowane",
  "Nie udało się wygenerować opisu.",
  "AI Listing Writer jest dostępny na Pro i Business.",
  "Udostępnij kopię swojej aukcji",
  "Docieraj do kupujących, gdziekolwiek spędzają czas.",
  "Dodaj kanały",
  "Więcej kanałów udostępniania",
  "Wybierz platformę, na której chcesz udostępnić wygenerowaną kopię aukcji. Niektóre kanały najpierw kopiują podpis, aby móc dodać zdjęcia i opublikować je w naturalny sposób.",
  "WhatsApp",
  "Wyślij do kontaktu lub grupy",
  "Facebook",
  "Udostępnij na swoim kanale",
  "Instagram",
  "Skopiuj podpis i otwórz Instagram",
  "X",
  "Opublikuj na swojej osi czasu",
  "LinkedIn",
  "Udostępnij w swojej sieci",
  "Telegram",
  "Wyślij na czat lub kanał",
  "Pinterest",
  "Skopiuj podpis i otwórz Pinterest",
  "Reddit",
  "Prześlij do społeczności",
  "Threads",
  "Skopiuj podpis i otwórz Threads",
  "TikTok",
  "Skopiuj podpis i otwórz TikTok",
  "YouTube",
  "Skopiuj podpis i otwórz YouTube",
  "Snapchat",
  "Skopiuj podpis i otwórz Snapchat",
  "E-mail",
  "Otwórz aplikację e-mail",
  "Wiadomość tekstowa",
  "Wyślij jako wiadomość tekstową",
  "Prolista nieruchomości",
  "Opis aukcji",
  "Opisz światło, układ, wykończenia i powody, dla których warto pokochać tę nieruchomość…",
  "Nie można dodać zdjęć do opisu.",
  "Nie udało się dodać filmów do opisu.",
  "Wersja robocza",
  "Aktywny",
  "W ramach oferty",
  "Sprzedane",
  "Zarchiwizowane",
  "Na sprzedaż",
  "Do wynajęcia",
  "Do wynajęcia",
  "Dom",
  "Mieszkanie",
  "Mieszkanie",
  "Kamienica",
  "Ziemia",
  "Biuro",
  "Detal",
  "Przemysłowe",
  "Mieszanego zastosowania",
  "Inne",
  "Stopy kwadratowe",
  "Metrów kwadratowych",
  "akry",
  "Nowy",
  "Dobrze",
  "Wymaga renowacji",
  "Własność",
  "Dzierżawa",
  "Miesięcznie",
  "Rocznie",
  "Metrów kwadratowych",
  "akry",
  "Nowy",
  "Dobrze",
  "Wymaga renowacji",
  "Własność",
  "Dzierżawa",
  "Miesięcznie",
  "Rocznie",
  "English",
  "中文",
  "हिन्दी",
  "Español",
  "العربية",
  "Français",
  "বাংলা",
  "Português",
  "Русский",
  "اردو",
  "Bahasa Indonesia",
  "Deutsch",
  "日本語",
  "Kiswahili",
  "Türkçe",
  "한국어",
  "Tiếng Việt",
  "Italiano",
  "ไทย",
  "Polski",
]);
