import { zip } from "../zip";

export const pt = zip([
  "EstateAI",
  "Listagem do espaço de trabalho",
  "Visão geral",
  "Listagens",
  "AI Listing Writer",
  "Análise",
  "Guia",
  "Preços",
  "Configurações",
  "Solicitações de cotação",
  "Espaço de trabalho",
  "Proinventário de propriedade",
  "Estúdio de conteúdo",
  "Gerenciamento de leads",
  "Inteligência de portfólio",
  "Primeiros passos",
  "Planos",
  "Preferências do espaço de trabalho",
  "Alternar navegação",
  "Entre em contato com o desenvolvedor do aplicativo",
  "Teste",
  "Wix",
  "Plano",
  "Listagens ilimitadas são visíveis no site.",
  "{visible} de {cap} listagens estão visíveis no site.",
  "Iniciar teste gratuito",
  "Ver planos",
  "Que bom ver você",
  "Seu espaço de trabalho imobiliário",
  "Mantenha seu inventário organizado, identifique movimentos rapidamente e prepare cada listagem para publicação assistida. Novo aqui? Siga o {guide}.",
  "guia do espaço de trabalho",
  "Adicionar listagem",
  "Tentar novamente",
  "Não foi possível carregar sua visão geral. Verifique as permissões de coleta e tente novamente.",
  "Listagens totais",
  "Em todo o seu espaço de trabalho",
  "Ativo",
  "Atualmente disponível",
  "Em oferta",
  "Movendo-se através de um acordo",
  "Vendido",
  "Transações concluídas",
  "Listagens recentes",
  "As propriedades mais recentes adicionadas ou atualizadas no seu espaço de trabalho.",
  "Ver tudo",
  "Seu inventário está pronto para a primeira listagem",
  "Adicione uma propriedade para começar a monitorar seu portfólio e desbloquear análises.",
  "Listagens abertas",
  "Local não definido",
  "Próximo foco",
  "Transforme detalhes em impulso",
  "Transforme seus fatos imobiliários confirmados em cópias profissionais, luxuosas, curtas, SEO ou prontas para redes sociais em segundos.",
  "Abra AI writer",
  "Desbloquear AI writer",
  "Gerenciamento de estoque",
  "Todas as listagens",
  "Pesquise, organize e mantenha todas as propriedades prontas para a próxima etapa.",
  "O site ao vivo mostra as listagens ativas {visible} atualizadas mais recentemente do limite do seu plano {cap}.",
  "Proinventário de propriedade",
  "{count} listagem neste espaço de trabalho",
  "{count} listagens neste espaço de trabalho",
  "Pesquise título ou cidade",
  "Listagens de pesquisa",
  "Filtrar por status",
  "Filtrar por tipo de propriedade",
  "Estado",
  "Protipo de propriedade",
  "Todos os status",
  "Todos os tipos",
  "Página anterior",
  "Próxima página",
  "Página {current} de {total}",
  "Ações para {title}",
  "Editar",
  "Visitantes únicos",
  "Excluir",
  "Não foi possível carregar listagens. Verifique as permissões de coleta e tente novamente.",
  "Nenhuma listagem corresponde a esses filtros.",
  "Crie sua primeira listagem ou ajuste a pesquisa e os filtros.",
  "Carregando listagens",
  "Todos os tipos de propriedade",
  "Imagem da capa",
  "Imagem {n}",
  "Insira um título para esta listagem.",
  "Use um código de moeda de três letras.",
  "Insira um preço válido.",
  "Insira uma área válida.",
  "Selecione um país.",
  "Selecione um estado ou região.",
  "Insira a cidade ou localidade.",
  "Digite o endereço.",
  "Insira um endereço de e-mail válido.",
  "Insira um número de telefone válido.",
  "Insira um número válido.",
  "Insira um número inteiro.",
  "O país onde a propriedade está localizada.",
  "O estado, província ou região onde a propriedade está localizada.",
  "A unidade usada para medir a área da propriedade.",
  "Não foi possível carregar os países.",
  "Os estados não puderam ser carregados.",
  "Não foi possível carregar as cidades.",
  "As visualizações até agora são de visitantes não assinados, portanto, usuários únicos não podem ser listados.",
  "Casa contemporânea de 3 quartos em Austin, TX",
  "<p>Moradia luminosa e espaçosa com acabamentos modernos, excelente luz natural e garagem para dois carros. Localizado perto de lojas, restaurantes e das principais rotas de transporte regional.</p><p>Ideal para profissionais ou uma família em crescimento que procura uma casa confortável em um bairro com boas conexões.</p>",
  "Piscina, Ginásio, Garagem, Ar central",
  "Visitantes únicos",
  "Pessoas que visualizaram “{title}”, contaram uma vez cada.",
  "Carregando visitantes únicos",
  "Não foi possível carregar visitantes únicos. Tente novamente.",
  "Ninguém viu esta listagem ainda.",
  "{count} visitante único",
  "{count} visitantes únicos",
  "{count} visualização não assinada",
  "{count} visualizações não assinadas",
  "{count} visualização",
  "{count} visualizações",
  "último {when}",
  "Visitante conectado",
  "Excluir esta listagem?",
  "“{title}” será removido das listagens ativas. Você ainda poderá visualizá-lo quando as listagens arquivadas estiverem ativadas.",
  "Cancelar",
  "Excluir listagem",
  "Propropriedade",
  "Tipo",
  "Preço",
  "Estado",
  "Visualizações",
  "Atualizado",
  "Ações",
  "Estúdio de conteúdo",
  "Escreva listagens que sejam notadas",
  "Adicione os fatos da propriedade uma vez e deixe a IA transformá-los em textos de marketing sofisticados. Revise todos os detalhes antes de publicar.",
  "AI Listing Writer está em Pro e Business",
  "Atualize para gerar uma cópia profissional da listagem a partir dos dados de sua propriedade.",
  "Inteligência de portfólio",
  "Análise avançada",
  "Entenda seu mix de inventário, atividade e disponibilidade de conteúdo a partir dos dados que você já possui.",
  "Atualizar",
  "A análise está em Pro e Business",
  "Atualize para ver o mix de inventário, a atividade e a disponibilidade de conteúdo.",
  "Não foi possível calcular análises. Verifique as permissões de coleta e tente novamente.",
  "Inventário rastreado",
  "Listagens na coleção",
  "AI-ready conteúdo",
  "Listagens com campos de IA preenchidos",
  "Cidades ativas",
  "As cinco principais cidades mostradas abaixo",
  "Sinal de atividade",
  "Listagens adicionadas nos últimos seis meses",
  "Atividade de listagem",
  "Novos registros criados nos últimos seis meses civis.",
  "Principais cidades",
  "Adicione locais para ver a concentração geográfica.",
  "Property mix",
  "Inventário agrupado por tipo de propriedade.",
  "Adicione listagens para ver seu mix de propriedades.",
  "Preço médio pedido",
  "Agrupados por moeda para manter as comparações significativas.",
  "Adicione listagens para ver sinais de preços.",
  "Listagem {count}",
  "{count} listagens",
  "Status da listagem",
  "Seu detalhamento de status aparecerá assim que as listagens forem adicionadas.",
  "Combinação de transações",
  "Seu mix de transações aparecerá assim que as listagens forem adicionadas.",
  "As análises são calculadas a partir da coleção de listagens atuais e atualizadas sob demanda.",
  "Ainda não há dados de listagem",
  "Distribuição atual em seu inventário.",
  "Planos de aplicativos",
  "Escolha o plano que se adapta ao seu inventário",
  "Sua avaliação gratuita inclui todos os recursos do Business. Após o término, o site ativo e as ferramentas fechadas seguem seu plano ativo.",
  "Comece em Basic para publicar listagens e coletar cotações. Atualize para Pro ou Business quando precisar de cópia de IA, tours 360°, análises e mais ferramentas de marketing.",
  "Plano atual",
  "Teste grátis",
  "Mais popular",
  "Comparação de recursos",
  "O que está incluído em Basic, Pro e Business.",
  "Recurso",
  "Incluído",
  "Não incluído",
  "Basic",
  "Pro",
  "Business",
  "Grátis",
  "Incluído com o aplicativo",
  "por mês",
  "Publique um pequeno inventário e colete consultas do site.",
  "Cópia de IA, tours 360°, insights de visitantes e análises de portfólio.",
  "Listagens ilimitadas, assistente de IA no local e ferramentas de marketing completas.",
  "Listagens ativas",
  "Até 10",
  "Até 50",
  "Ilimitado",
  "Listagens e widgets de detalhes de propriedades",
  "Contato do proprietário nas páginas do anúncio",
  "Formulário de solicitação de orçamento",
  "Propriedades salvas para membros",
  "AI Listing Writer",
  "360° tour virtual",
  "Insights exclusivos de visitantes",
  "Análise de portfólio",
  "Compartilhamento social nas páginas de listagem",
  "Notificações por e-mail de solicitação de cotação",
  "Assistente de IA de propriedade no local",
  "Listagens relacionadas em páginas de propriedades",
  "Várias cenas da turnê 360°",
  "Suporte prioritário",
  "Preferências do espaço de trabalho",
  "Configurações",
  "Defina padrões sensatos para novas listagens e mantenha o espaço de trabalho focado nos registros que sua equipe está gerenciando ativamente.",
  "Listando padrões",
  "Essas preferências preenchem previamente novas listagens. Os registros existentes não são alterados.",
  "Moeda padrão",
  "A moeda pré-selecionada para novos preços de listagem.",
  "Escolha na lista completa de moedas ISO 4217.",
  "Unidade de área padrão",
  "A unidade de medida pré-selecionada para novas áreas de listagem.",
  "Aplicado ao campo de área em novos registros.",
  "Status de listagem padrão",
  "O status do fluxo de trabalho atribuído a novas listagens.",
  "Novas listagens são abertas com esta etapa do fluxo de trabalho.",
  "Incluir listagens arquivadas",
  "Quando ativado, as listagens arquivadas aparecem na visualização Listagens por padrão.",
  "Mantenha os registros arquivados visíveis na visualização Listagens por padrão.",
  "Idioma do painel",
  "Escolha o idioma para este espaço de trabalho ou siga o idioma da conta Wix.",
  "Auto (Wix account language)",
  "Salvo localmente para este navegador",
  "As alterações ainda não foram salvas",
  "Redefinir",
  "Salvar configurações",
  "Configurações do espaço de trabalho salvas.",
  "Não foi possível salvar as configurações neste navegador.",
  "Saved Properties lançador",
  "Incorpore ou restaure o botão e a gaveta de propriedades salvas dos membros em seu site ativo.",
  "É seguro executar mais de uma vez.",
  "Incorporar iniciador",
  "Incorporando…",
  "O lançador Saved Properties está ativo no site.",
  "O iniciador não pôde ser incorporado.",
  "Ajuda: {hint}",
  "Gerenciamento de leads",
  "Solicitações de cotação",
  "Revise as consultas sobre propriedades e mantenha o status de acompanhamento atualizado.",
  "Solicitações recebidas",
  "{count} solicitação",
  "{count} solicitações",
  "Pesquisar propriedade",
  "Pesquisar solicitações de cotação",
  "Filtrar solicitações de cotação por status",
  "Atualizar solicitações de cotação",
  "Não foi possível carregar as solicitações de cotação.",
  "Não foi possível atualizar a solicitação.",
  "Nenhuma solicitação de orçamento corresponde a esses filtros.",
  "Nenhuma mensagem fornecida.",
  "Notas internas",
  "Notas para {title}",
  "Status para {title}",
  "Arquivo",
  "Página {current}",
  "Anterior",
  "Próximo",
  "Novo",
  "Contatado",
  "Citado",
  "Fechado",
  "Primeiros passos",
  "Como usar este espaço de trabalho",
  "Crie listagens aqui, publique-as com os widgets do site e acompanhe as solicitações de orçamento e a atividade dos visitantes neste painel.",
  "Caminho recomendado",
  "Adicione pelo menos uma listagem ativa, coloque os widgets em seu site e marque Solicitações de orçamento depois que um visitante enviar uma consulta.",
  "Etapa {n}",
  "Crie e gerencie listagens",
  "Mantenha todas as propriedades em um inventário.",
  "Adicione uma listagem com localização, preço, imagens e um tour opcional 360°.",
  "O contato do agente/proprietário é preenchido pelo proprietário do site e pode ser editado por listagem.",
  "Use o menu de ações da listagem para editar, revisar visitantes únicos ou excluir.",
  "Apenas listagens ativas aparecem no site ativo.",
  "Publicar listagens no site",
  "Mostre o inventário e detalhes da propriedade aos visitantes.",
  "Adicione o widget de listagens de propriedades a uma página como /properties.",
  "Adicione o widget de detalhes da propriedade a uma página como /property-details.",
  "No editor, ative ou desative Contato, solicitação de orçamento, compartilhamento e listagens relacionadas.",
  "Incorpore o iniciador Saved Properties em Configurações para que os membros possam marcar casas como favoritos.",
  "Abrir configurações",
  "Lidar com consultas de visitantes",
  "Deixe os compradores entrarem em contato com você sem sair da listagem.",
  "Os visitantes veem o nome do proprietário, telefone e e-mail na página da propriedade quando o Contato está ativado.",
  "Solicitar um orçamento coleta nome, e-mail, telefone e uma mensagem formatada.",
  "Novas solicitações aparecem aqui com status, notas e arquivo.",
  "As notificações de cotação usam o e-mail do agente de listagem e o e-mail do proprietário do site.",
  "Abrir solicitações de cotação",
  "Escreva uma cópia da listagem com IA",
  "Transforme fatos em descrições prontas para marketing.",
  "Abra AI Listing Writer ou use Write with AI dentro do editor de listagem.",
  "Revise a cópia gerada e salve-a na listagem antes de publicar.",
  "Use o Analytics para ver quais listagens atraem mais visualizações.",
  "Precisa de mais ajuda",
  "Padrões e suporte do espaço de trabalho",
  "Defina a moeda padrão, a unidade de área e o status em Configurações. Entre em contato com o desenvolvedor do aplicativo na barra lateral se um widget ou coleção estiver faltando após a instalação.",
  "Adicionar listagem",
  "Editar listagem",
  "Mantenha as informações da sua propriedade precisas e prontas para publicação.",
  "Não foi possível abrir esta listagem",
  "Voltar às listagens",
  "Esta listagem não foi encontrada.",
  "Não foi possível carregar esta listagem.",
  "{title} foi atualizado.",
  "{title} foi adicionado.",
  "Não foi possível salvar a listagem.",
  "{title} foi arquivado.",
  "Não foi possível arquivar a listagem.",
  "Crie uma nova listagem",
  "Editar detalhes da listagem",
  "Prohistória de propriedade",
  "Use o editor para adicionar uma descrição estruturada e refinada.",
  "Título",
  "Um nome conciso que identifica esta propriedade.",
  "Casa iluminada de 3 quartos em Austin, TX",
  "Descrição",
  "Descreva o imóvel, layout, acabamentos e pontos de venda.",
  "Escreva com IA",
  "AI writer (Pro)",
  "Carregando editor…",
  "Endereço",
  "Insira o endereço ou detalhes da localização da propriedade.",
  "Endereço ou bairro",
  "Cidade",
  "Escolha uma cidade sugerida ou insira uma manualmente.",
  "Insira ou selecione uma cidade",
  "País",
  "Estado/região",
  "Listando imagens",
  "Escolha imagens de Wix Media Manager; a primeira imagem é a capa.",
  "A primeira imagem é usada como capa dos cartões e da página de propriedades.",
  "Escolha imagens",
  "Adicionar imagens",
  "Nenhuma imagem selecionada ainda.",
  "Remover imagem {n}",
  "360° tour virtual",
  "Adicione fotos 360° equirretangulares para o visualizador Three.js interativo. Os visitantes podem alternar entre salas e mirantes.",
  " Passeios virtuais estão incluídos em Pro e Business; imagens extras permanecerão no painel se você adicioná-las agora.",
  " Sites Pro mostram a primeira cena; cenas adicionais vão ao vivo em Business.",
  "360° imagens panorâmicas",
  "Escolha imagens 360° equirretangulares para o visualizador Three.js interativo. Os visitantes podem alternar entre as cenas.",
  "Opcional. Cada imagem deve ser uma foto 360° equirretangular.",
  "Nenhum panorama 360° selecionado.",
  "Remover panorama {n}",
  "Cena {n}",
  "Listando fatos",
  "Esses campos potencializam filtros e análises de portfólio.",
  "Tipo de transação",
  "Se o imóvel está à venda, aluguel ou arrendamento.",
  "A categoria que melhor descreve a propriedade.",
  "O estágio atual do fluxo de trabalho para esta listagem.",
  "Procondição de propriedade",
  "A condição física atual do imóvel.",
  "Estado do mobiliário",
  "Se o imóvel está sem mobília, parcialmente mobiliado ou mobiliado.",
  "Posse",
  "O acordo de propriedade ou arrendamento da propriedade.",
  "Frequência de aluguel",
  "Com que frequência o aluguel é esperado para listagens de aluguel ou arrendamento.",
  "Preço",
  "O preço de listagem na moeda selecionada.",
  "Moeda",
  "A moeda de três letras usada para o preço de listagem.",
  "Área",
  "O tamanho da propriedade na unidade de área selecionada.",
  "Unidade de área",
  "Comodidades",
  "Liste recursos notáveis separados por vírgulas.",
  "Piscina, academia, segurança 24 horas por dia, 7 dias por semana",
  "Data de disponibilidade",
  "A data em que a propriedade fica disponível.",
  "Contato do agente/proprietário",
  "Nome",
  "O agente ou proprietário responsável por esta listagem.",
  "Nome do agente ou proprietário",
  "Telefone",
  "Um número de telefone para consultas de listagem.",
  "Número de telefone internacional",
  "E-mail",
  "Um endereço de e-mail para consultas de listagem.",
  "Posicionamento do mapa",
  "Latitude",
  "A latitude da propriedade usada para posicionamento do mapa.",
  "Longitude",
  "A propriedade longitude usada para posicionamento do mapa.",
  "Salvar listagem",
  "Salvando…",
  "AI writer",
  "Os fatos desta lista são preenchidos para você. Ao terminar a escrita, a descrição no formulário é atualizada automaticamente.",
  "A descrição do anúncio foi atualizada.",
  "O Media Manager não pôde ser aberto.",
  "Selecione {label}",
  "Valor opcional {label} para esta listagem.",
  "Opcional",
  "Quartos",
  "Banheiros",
  "Ano construído",
  "Vagas de estacionamento",
  "Taxa de serviço",
  "Depósito de segurança",
  "Obrigatório",
  "Adicione um título.",
  "Adicione um endereço.",
  "Adicione uma cidade.",
  "Adicione um preço.",
  "Adicione uma área.",
  "Corrija os campos destacados antes de salvar.",
  "Não foi possível carregar as sugestões de localização. Você ainda pode digitar valores.",
  "Pronoções básicas de propriedade",
  "O que a descrição deve dizer?",
  "Localização",
  "Austin, Texas",
  "US$ 875.000",
  "Piscina, academia, estacionamento",
  "Estilo de escrita",
  "Gerar descrição",
  "Escrevendo sua descrição…",
  "Descrição gerada",
  "Quando a redação terminar, esta cópia será adicionada à descrição do anúncio.",
  "Revise a cópia e copie-a em sua listagem.",
  "Copiar",
  "Copiado",
  "Descrição da propriedade gerada",
  "Sua cópia polida aparecerá aqui",
  "Escolha um estilo e gere uma descrição a partir dos fatos de propriedade confirmados.",
  "Proprofissional",
  "Claro e confiável",
  "Luxo",
  "Elevado e aspiracional",
  "Curto",
  "Perfeito para cartões",
  "Otimizado para SEO",
  "Cópia amigável para pesquisa",
  "Redes sociais",
  "Envolvente e compartilhável",
  "Mobiliado",
  "Semi-mobiliado",
  "Sem mobília",
  "A descrição não pôde ser gerada.",
  "AI Listing Writer está disponível em Pro e Business.",
  "Compartilhe a cópia da sua listagem",
  "Alcance os compradores onde quer que eles estejam.",
  "Adicionar canais",
  "Mais canais de compartilhamento",
  "Escolha uma plataforma para compartilhar a cópia da listagem gerada. Alguns canais copiam a legenda primeiro para que você possa adicionar fotos e publicá-las naturalmente.",
  "WhatsApp",
  "Enviar para um contato ou grupo",
  "Facebook",
  "Compartilhe no seu feed",
  "Instagram",
  "Copie a legenda e abra Instagram",
  "X",
  "Poste na sua linha do tempo",
  "LinkedIn",
  "Compartilhe com sua rede",
  "Telegram",
  "Enviar para um chat ou canal",
  "Pinterest",
  "Copie a legenda e abra Pinterest",
  "Reddit",
  "Enviar para uma comunidade",
  "Threads",
  "Copie a legenda e abra Threads",
  "TikTok",
  "Copie a legenda e abra TikTok",
  "YouTube",
  "Copie a legenda e abra YouTube",
  "Snapchat",
  "Copie a legenda e abra Snapchat",
  "E-mail",
  "Abra seu aplicativo de e-mail",
  "Mensagem de texto",
  "Enviar como mensagem de texto",
  "Prolista de propriedades",
  "Descrição do anúncio",
  "Descreva a luz, a disposição, os acabamentos e os motivos para adorar este imóvel…",
  "Não foi possível adicionar imagens à descrição.",
  "Não foi possível adicionar vídeos à descrição.",
  "Rascunho",
  "Ativo",
  "Em oferta",
  "Vendido",
  "Arquivado",
  "À venda",
  "Para alugar",
  "Para alugar",
  "Casa",
  "Apartamento",
  "Condomínio",
  "Moradia",
  "Terreno",
  "Escritório",
  "Varejo",
  "Industriais",
  "Uso misto",
  "Outro",
  "Pés quadrados",
  "Metros quadrados",
  "Hectares",
  "Novo",
  "Bom",
  "Precisa de renovação",
  "Propriedade perfeita",
  "Arrendamento",
  "Mensalmente",
  "Anualmente",
  "Metros quadrados",
  "Hectares",
  "Novo",
  "Bom",
  "Precisa de renovação",
  "Propriedade perfeita",
  "Arrendamento",
  "Mensalmente",
  "Anualmente",
  "English",
  "中文",
  "हिन्दी",
  "Español",
  "العربية",
  "Français",
  "বাংলা",
  "Português",
  "Русский",
  "اردو",
  "Bahasa Indonesia",
  "Deutsch",
  "日本語",
  "Kiswahili",
  "Türkçe",
  "한국어",
  "Tiếng Việt",
  "Italiano",
  "ไทย",
  "Polski",
]);
