import { zip } from "../zip";

export const ru = zip([
  "EstateAI",
  "Listing workspace",
  "Overview",
  "Listings",
  "AI Listing Writer",
  "Analytics",
  "Guide",
  "Pricing",
  "Settings",
  "Quote requests",
  "Workspace",
  "Property inventory",
  "Content studio",
  "Lead management",
  "Portfolio intelligence",
  "Getting started",
  "Plans",
  "Workspace preferences",
  "Toggle navigation",
  "Contact app developer",
  "Trial",
  "Wix",
  "Plan",
  "Unlimited listings are visible on the site.",
  "{visible} of {cap} listings are visible on the site.",
  "Start free trial",
  "View plans",
  "Good to see you",
  "Your real estate workspace",
  "Keep your inventory organized, spot movement quickly, and prepare every listing for assisted publishing. New here? Follow the {guide}.",
  "workspace guide",
  "Add listing",
  "Retry",
  "We could not load your overview. Check the collection permissions and try again.",
  "Total listings",
  "Across your workspace",
  "Active",
  "Currently available",
  "Under offer",
  "Moving through a deal",
  "Sold",
  "Completed transactions",
  "Recent listings",
  "The latest properties added or updated in your workspace.",
  "View all",
  "Your inventory is ready for its first listing",
  "Add a property to start tracking your portfolio and unlock analytics.",
  "Open listings",
  "Location not set",
  "Next focus",
  "Turn details into momentum",
  "Turn your confirmed property facts into professional, luxury, short, SEO, or social-ready copy in seconds.",
  "Open AI writer",
  "Unlock AI writer",
  "Inventory management",
  "All listings",
  "Search, organize, and keep every property ready for its next stage.",
  "The live site shows the {visible} most recently updated active listing(s) of your {cap} plan cap.",
  "Property inventory",
  "{count} listing in this workspace",
  "{count} listings in this workspace",
  "Search title or city",
  "Search listings",
  "Filter by status",
  "Filter by property type",
  "Status",
  "Property type",
  "All statuses",
  "All types",
  "Previous page",
  "Next page",
  "Page {current} of {total}",
  "Actions for {title}",
  "Edit",
  "Unique visitors",
  "Delete",
  "We could not load listings. Check the collection permissions and try again.",
  "No listings match these filters.",
  "Create your first listing or adjust the search and filters.",
  "Loading listings",
  "All property types",
  "Cover image",
  "Image {n}",
  "Enter a title for this listing.",
  "Use a three-letter currency code.",
  "Enter a valid price.",
  "Enter a valid area.",
  "Select a country.",
  "Select a state or region.",
  "Enter the city or locality.",
  "Enter the street address.",
  "Enter a valid email address.",
  "Enter a valid phone number.",
  "Enter a valid number.",
  "Enter a whole number.",
  "The country where the property is located.",
  "The state, province, or region where the property is located.",
  "The unit used to measure the property area.",
  "Countries could not be loaded.",
  "States could not be loaded.",
  "Cities could not be loaded.",
  "Views so far are from unsigned visitors, so unique users cannot be listed.",
  "Contemporary 3-bedroom house in Austin, TX",
  "<p>Bright and spacious home with modern finishes, excellent natural light, and a two-car garage. Located close to shops, restaurants, and major commuter routes.</p><p>Ideal for professionals or a growing family looking for a comfortable home in a well-connected neighborhood.</p>",
  "Swimming pool, Gym, Garage, Central air",
  "Unique visitors",
  "People who viewed “{title}”, counted once each.",
  "Loading unique visitors",
  "Unique visitors could not be loaded. Try again.",
  "No one has viewed this listing yet.",
  "{count} unique visitor",
  "{count} unique visitors",
  "{count} unsigned view",
  "{count} unsigned views",
  "{count} view",
  "{count} views",
  "last {when}",
  "Signed-in visitor",
  "Delete this listing?",
  "“{title}” will be removed from active listings. You can still view it when archived listings are enabled.",
  "Cancel",
  "Delete listing",
  "Property",
  "Type",
  "Price",
  "Status",
  "Views",
  "Updated",
  "Actions",
  "Content studio",
  "Write listings that get noticed",
  "Add the property facts once and let AI turn them into polished marketing copy. Review every detail before publishing.",
  "AI Listing Writer is on Pro and Business",
  "Upgrade to generate professional listing copy from your property facts.",
  "Portfolio intelligence",
  "Advanced analytics",
  "Understand your inventory mix, activity, and content readiness from the data you already have.",
  "Refresh",
  "Analytics is on Pro and Business",
  "Upgrade to see inventory mix, activity, and content readiness.",
  "We could not calculate analytics. Check the collection permissions and try again.",
  "Tracked inventory",
  "Listings in the collection",
  "AI-ready content",
  "Listings with AI fields populated",
  "Active cities",
  "Top five cities shown below",
  "Activity signal",
  "Listings added in the last six months",
  "Listing activity",
  "New records created over the last six calendar months.",
  "Top cities",
  "Add locations to see geographic concentration.",
  "Property mix",
  "Inventory grouped by property type.",
  "Add listings to see your property mix.",
  "Average asking price",
  "Grouped by currency to keep comparisons meaningful.",
  "Add listings to see pricing signals.",
  "{count} listing",
  "{count} listings",
  "Listing status",
  "Your status breakdown will appear once listings are added.",
  "Transaction mix",
  "Your transaction mix will appear once listings are added.",
  "Analytics are calculated from the current listings collection and refresh on demand.",
  "No listing data yet",
  "Current distribution across your inventory.",
  "App plans",
  "Choose the plan that fits your inventory",
  "Your free trial includes every Business feature. After it ends, the live site and gated tools follow your active plan.",
  "Start on Basic to publish listings and collect quotes. Upgrade to Pro or Business when you need AI copy, 360° tours, analytics, and more marketing tools.",
  "Current plan",
  "Free trial",
  "Most popular",
  "Feature comparison",
  "What is included on Basic, Pro, and Business.",
  "Feature",
  "Included",
  "Not included",
  "Basic",
  "Pro",
  "Business",
  "Free",
  "Included with the app",
  "per month",
  "Publish a small inventory and collect enquiries from the site.",
  "AI copy, 360° tours, visitor insights, and portfolio analytics.",
  "Unlimited listings, on-site AI assistant, and full marketing tools.",
  "Active listings",
  "Up to 10",
  "Up to 50",
  "Unlimited",
  "Listings and property detail widgets",
  "Owner contact on listing pages",
  "Quote request form",
  "Saved properties for members",
  "AI Listing Writer",
  "360° virtual tour",
  "Unique visitor insights",
  "Portfolio analytics",
  "Social sharing on listing pages",
  "Quote request email notifications",
  "On-site property AI assistant",
  "Related listings on property pages",
  "Multiple 360° tour scenes",
  "Priority support",
  "Workspace preferences",
  "Settings",
  "Set sensible defaults for new listings and keep the workspace focused on the records your team is actively managing.",
  "Listing defaults",
  "These preferences prefill new listings. Existing records are not changed.",
  "Default currency",
  "The currency preselected for new listing prices.",
  "Choose from the full ISO 4217 currency list.",
  "Default area unit",
  "The measurement unit preselected for new listing areas.",
  "Applied to the area field on new records.",
  "Default listing status",
  "The workflow status assigned to new listings.",
  "New listings open with this workflow stage.",
  "Include archived listings",
  "When enabled, archived listings appear in the Listings view by default.",
  "Keep archived records visible in the Listings view by default.",
  "Dashboard language",
  "Choose the language for this workspace, or follow the Wix account language.",
  "Auto (Wix account language)",
  "Saved locally for this browser",
  "Changes are not saved yet",
  "Reset",
  "Save settings",
  "Workspace settings saved.",
  "Settings could not be saved in this browser.",
  "Saved Properties launcher",
  "Embed or restore the member saved-properties button and drawer on your live site.",
  "Safe to run more than once.",
  "Embed launcher",
  "Embedding…",
  "Saved Properties launcher is active on the site.",
  "The launcher could not be embedded.",
  "Help: {hint}",
  "Lead management",
  "Quote requests",
  "Review property enquiries and keep follow-up status up to date.",
  "Incoming requests",
  "{count} request",
  "{count} requests",
  "Search property",
  "Search quote requests",
  "Filter quote requests by status",
  "Refresh quote requests",
  "Quote requests could not be loaded.",
  "The request could not be updated.",
  "No quote requests match these filters.",
  "No message provided.",
  "Internal notes",
  "Notes for {title}",
  "Status for {title}",
  "Archive",
  "Page {current}",
  "Previous",
  "Next",
  "New",
  "Contacted",
  "Quoted",
  "Closed",
  "Getting started",
  "How to use this workspace",
  "Create listings here, publish them with the site widgets, then follow up on quote requests and visitor activity from this dashboard.",
  "Recommended path",
  "Add at least one active listing, place the widgets on your site, then check Quote requests after a visitor submits an enquiry.",
  "Step {n}",
  "Create and manage listings",
  "Keep every property in one inventory.",
  "Add a listing with location, price, images, and an optional 360° tour.",
  "Agent / owner contact is filled from the site owner and can be edited per listing.",
  "Use the listing actions menu to edit, review unique visitors, or delete.",
  "Only active listings appear on the live site.",
  "Publish listings on the site",
  "Show inventory and property details to visitors.",
  "Add the property listings widget to a page such as /properties.",
  "Add the property detail widget to a page such as /property-details.",
  "In the editor, turn Contact, quote request, share, and related listings on or off.",
  "Embed the Saved Properties launcher from Settings so members can bookmark homes.",
  "Open settings",
  "Handle visitor enquiries",
  "Let buyers contact you without leaving the listing.",
  "Visitors see owner name, phone, and email on the property page when Contact is enabled.",
  "Request a quote collects name, email, phone, and a formatted message.",
  "New requests appear here with status, notes, and archive.",
  "Quote notifications use the listing agent email and the site owner email.",
  "Open quote requests",
  "Write listing copy with AI",
  "Turn facts into marketing-ready descriptions.",
  "Open AI Listing Writer or use Write with AI inside the listing editor.",
  "Review the generated copy, then save it on the listing before publishing.",
  "Use Analytics to see which listings attract the most views.",
  "Need more help",
  "Workspace defaults and support",
  "Set default currency, area unit, and status in Settings. Contact the app developer from the sidebar if a widget or collection is missing after install.",
  "Add listing",
  "Edit listing",
  "Keep your property information accurate and ready for publishing.",
  "Unable to open this listing",
  "Return to listings",
  "This listing could not be found.",
  "This listing could not be loaded.",
  "{title} was updated.",
  "{title} was added.",
  "The listing could not be saved.",
  "{title} was archived.",
  "The listing could not be archived.",
  "Create a new listing",
  "Edit listing details",
  "Property story",
  "Use the editor to add a polished, structured description.",
  "Title",
  "A concise name that identifies this property.",
  "Light-filled 3-bedroom house in Austin, TX",
  "Description",
  "Describe the property, layout, finishes, and selling points.",
  "Write with AI",
  "AI writer (Pro)",
  "Loading editor…",
  "Address",
  "Enter the street address or property location details.",
  "Street address or neighborhood",
  "City",
  "Choose a suggested city or enter one manually.",
  "Enter or select a city",
  "Country",
  "State / region",
  "Listing images",
  "Choose images from Wix Media Manager; the first image is the cover.",
  "The first image is used as the cover on cards and the property page.",
  "Choose images",
  "Add images",
  "No images selected yet.",
  "Remove image {n}",
  "360° virtual tour",
  "Add equirectangular 360° photos for the interactive Three.js viewer. Visitors can switch between rooms and viewpoints.",
  " Virtual tours are included on Pro and Business; extra images stay in the dashboard if you add them now.",
  " Pro sites show the first scene; additional scenes go live on Business.",
  "360° panorama images",
  "Choose equirectangular 360° images for the interactive Three.js viewer. Visitors can switch between scenes.",
  "Optional. Each image should be an equirectangular 360° photo.",
  "No 360° panoramas selected.",
  "Remove panorama {n}",
  "Scene {n}",
  "Listing facts",
  "These fields power filters and portfolio analytics.",
  "Transaction type",
  "Whether the property is for sale, rent, or lease.",
  "The category that best describes the property.",
  "The current workflow stage for this listing.",
  "Property condition",
  "The current physical condition of the property.",
  "Furnishing status",
  "Whether the property is unfurnished, partly furnished, or furnished.",
  "Tenure",
  "The ownership or lease arrangement for the property.",
  "Rental frequency",
  "How often rent is expected for rental or lease listings.",
  "Price",
  "The listing price in the selected currency.",
  "Currency",
  "The three-letter currency used for the listing price.",
  "Area",
  "The property size in the selected area unit.",
  "Area unit",
  "Amenities",
  "List notable features separated by commas.",
  "Swimming pool, gym, 24/7 security",
  "Availability date",
  "The date when the property becomes available.",
  "Agent / owner contact",
  "Name",
  "The agent or owner responsible for this listing.",
  "Agent or owner name",
  "Phone",
  "A phone number for listing enquiries.",
  "International phone number",
  "Email",
  "An email address for listing enquiries.",
  "Map placement",
  "Latitude",
  "The property latitude used for map placement.",
  "Longitude",
  "The property longitude used for map placement.",
  "Save listing",
  "Saving…",
  "AI writer",
  "Facts from this listing are filled in for you. When writing finishes, the description on the form updates automatically.",
  "The listing description was updated.",
  "The Media Manager could not be opened.",
  "Select {label}",
  "Optional {label} value for this listing.",
  "Optional",
  "Bedrooms",
  "Bathrooms",
  "Year built",
  "Parking spaces",
  "Service charge",
  "Security deposit",
  "Required",
  "Add a title.",
  "Add an address.",
  "Add a city.",
  "Add a price.",
  "Add an area.",
  "Fix the highlighted fields before saving.",
  "Location suggestions could not be loaded. You can still type values.",
  "Property basics",
  "What should the description say?",
  "Location",
  "Austin, Texas",
  "$875,000",
  "Swimming pool, gym, parking",
  "Writing style",
  "Generate description",
  "Writing your description…",
  "Generated description",
  "When writing finishes, this copy is added to the listing description.",
  "Review the copy, then copy it into your listing.",
  "Copy",
  "Copied",
  "Generated property description",
  "Your polished copy will appear here",
  "Choose a style and generate a description from the confirmed property facts.",
  "Professional",
  "Clear and trustworthy",
  "Luxury",
  "Elevated and aspirational",
  "Short",
  "Perfect for cards",
  "SEO optimized",
  "Search-friendly copy",
  "Social media",
  "Engaging and shareable",
  "Furnished",
  "Semi-furnished",
  "Unfurnished",
  "The description could not be generated.",
  "AI Listing Writer is available on Pro and Business.",
  "Share your listing copy",
  "Reach buyers wherever they spend time.",
  "Add channels",
  "More sharing channels",
  "Choose a platform to share the generated listing copy. Some channels copy the caption first so you can add photos and publish it naturally.",
  "WhatsApp",
  "Send to a contact or group",
  "Facebook",
  "Share to your feed",
  "Instagram",
  "Copy caption and open Instagram",
  "X",
  "Post to your timeline",
  "LinkedIn",
  "Share with your network",
  "Telegram",
  "Send to a chat or channel",
  "Pinterest",
  "Copy caption and open Pinterest",
  "Reddit",
  "Submit to a community",
  "Threads",
  "Copy caption and open Threads",
  "TikTok",
  "Copy caption and open TikTok",
  "YouTube",
  "Copy caption and open YouTube",
  "Snapchat",
  "Copy caption and open Snapchat",
  "Email",
  "Open your email app",
  "Text message",
  "Send as a text message",
  "Property listing",
  "Listing description",
  "Describe the light, layout, finishes, and reasons to love this property…",
  "Images could not be added to the description.",
  "Videos could not be added to the description.",
  "Draft",
  "Active",
  "Under offer",
  "Sold",
  "Archived",
  "For sale",
  "For rent",
  "For lease",
  "House",
  "Apartment",
  "Condo",
  "Townhouse",
  "Land",
  "Office",
  "Retail",
  "Industrial",
  "Mixed-use",
  "Other",
  "Square feet",
  "Square metres",
  "Acres",
  "New",
  "Good",
  "Needs renovation",
  "Freehold",
  "Leasehold",
  "Monthly",
  "Yearly",
  "Квадратные метры",
  "Акры",
  "Новый",
  "Хороший",
  "Требует ремонта",
  "Фригольд",
  "аренда",
  "Ежемесячно",
  "Ежегодно",
  "English",
  "中文",
  "हिन्दी",
  "Español",
  "العربية",
  "Français",
  "বাংলা",
  "Português",
  "Русский",
  "اردو",
  "Bahasa Indonesia",
  "Deutsch",
  "日本語",
  "Kiswahili",
  "Türkçe",
  "한국어",
  "Tiếng Việt",
  "Italiano",
  "ไทย",
  "Polski",
]);
