import { zip } from "../zip";

export const sw = zip([
  "EstateAI",
  "Kuorodhesha nafasi ya kazi",
  "Muhtasari",
  "Orodha",
  "AI Listing Writer",
  "Uchanganuzi",
  "Mwongozo",
  "Bei",
  "Mipangilio",
  "Maombi ya kunukuu",
  "Nafasi ya kazi",
  "Pro orodha ya mali",
  "Studio ya maudhui",
  "Usimamizi wa kiongozi",
  "Kwingineko akili",
  "Kuanza",
  "Mipango",
  "Mapendeleo ya nafasi ya kazi",
  "Geuza urambazaji",
  "Wasiliana na msanidi programu",
  "Jaribio",
  "Wix",
  "Mpango",
  "Orodha zisizo na kikomo zinaonekana kwenye tovuti.",
  "{visible} kati ya {cap} matangazo yanaonekana kwenye tovuti.",
  "Anzisha jaribio lisilolipishwa",
  "Tazama mipango",
  "Ni vizuri kukuona",
  "Nafasi yako ya kazi ya mali isiyohamishika",
  "Weka orodha yako ikiwa imepangwa, angalia harakati haraka, na uandae kila tangazo kwa uchapishaji unaosaidiwa. Mpya hapa? Fuata {guide}.",
  "mwongozo wa nafasi ya kazi",
  "Ongeza tangazo",
  "Jaribu tena",
  "Hatukuweza kupakia muhtasari wako. Angalia ruhusa za mkusanyiko na ujaribu tena.",
  "Jumla ya uorodheshaji",
  "Katika nafasi yako ya kazi",
  "Inayotumika",
  "Inapatikana kwa sasa",
  "Chini ya ofa",
  "Kupitia mpango",
  "Inauzwa",
  "Shughuli zilizokamilishwa",
  "Orodha za hivi majuzi",
  "Sifa za hivi punde zilizoongezwa au kusasishwa katika nafasi yako ya kazi.",
  "Tazama zote",
  "Orodha yako iko tayari kwa uorodheshaji wake wa kwanza",
  "Ongeza kipengele ili kuanza kufuatilia kwingineko yako na kufungua takwimu.",
  "Fungua tangazo",
  "Mahali hapajawekwa",
  "Mkazo unaofuata",
  "Badilisha maelezo kuwa kasi",
  "Geuza ukweli wako wa mali uliothibitishwa kuwa nakala za kitaalamu, anasa, fupi, SEO, au nakala iliyo tayari kwa jamii kwa sekunde.",
  "Fungua AI writer",
  "Fungua AI writer",
  "Usimamizi wa hesabu",
  "Orodha zote",
  "Tafuta, panga, na uweke kila mali tayari kwa hatua yake inayofuata.",
  "Tovuti ya moja kwa moja inaonyesha {visible} uorodheshaji amilifu uliosasishwa hivi karibuni zaidi wa {cap} upeo wa mpango wako.",
  "Pro orodha ya mali",
  "{count} kuorodheshwa katika nafasi hii ya kazi",
  "{count} matangazo katika nafasi hii ya kazi",
  "Tafuta jina au jiji",
  "Tafuta matangazo",
  "Chuja kwa hali",
  "Chuja kwa aina ya mali",
  "Hali",
  "Proaina ya perty",
  "Hali zote",
  "Aina zote",
  "Ukurasa uliotangulia",
  "Ukurasa unaofuata",
  "Ukurasa {current} kati ya {total}",
  "Vitendo vya {title}",
  "Hariri",
  "Wageni wa kipekee",
  "Futa",
  "Hatukuweza kupakia matangazo. Angalia ruhusa za mkusanyiko na ujaribu tena.",
  "Hakuna uorodheshaji unaolingana na vichujio hivi.",
  "Unda uorodheshaji wako wa kwanza au urekebishe utafutaji na vichujio.",
  "Inapakia tangazo",
  "Aina zote za mali",
  "Picha ya jalada",
  "Picha {n}",
  "Weka jina la tangazo hili.",
  "Tumia msimbo wa sarafu wa herufi tatu.",
  "Weka bei halali.",
  "Ingiza eneo halali.",
  "Chagua nchi.",
  "Chagua jimbo au eneo.",
  "Ingiza jiji au eneo.",
  "Weka anwani ya mtaani.",
  "Weka barua pepe halali.",
  "Weka nambari sahihi ya simu.",
  "Weka nambari halali.",
  "Weka nambari nzima.",
  "Nchi ambayo mali iko.",
  "Jimbo, mkoa au eneo ambalo mali iko.",
  "Sehemu inayotumika kupima eneo la mali.",
  "Nchi hazikuweza kupakiwa.",
  "Majimbo hayakuweza kupakiwa.",
  "Miji haikuweza kupakiwa.",
  "Maoni kufikia sasa ni kutoka kwa wageni ambao hawajasainiwa, kwa hivyo watumiaji wa kipekee hawawezi kuorodheshwa.",
  "Nyumba ya kisasa ya vyumba vitatu huko Austin, TX",
  "<p>Nyumba inayong'aa na pana yenye faini za kisasa, mwanga bora wa asili, na karakana ya magari mawili. Iko karibu na maduka, mikahawa na njia kuu za abiria.</p><p>Inafaa kwa wataalamu au familia inayokua inayotafuta nyumba nzuri katika mtaa uliounganishwa vyema.</p>",
  "Bwawa la kuogelea, Gym, Garage, hewa ya kati",
  "Wageni wa kipekee",
  "Watu waliotazama \"{title}\", walihesabu mara moja kila mmoja.",
  "Inapakia wageni wa kipekee",
  "Wageni wa kipekee hawakuweza kupakiwa. Jaribu tena.",
  "Bado hakuna mtu ambaye ametazama tangazo hili.",
  "{count} mgeni wa kipekee",
  "{count} wageni wa kipekee",
  "{count} mwonekano ambao haujatiwa saini",
  "{count} imetazamwa bila kusainiwa",
  "{count} imetazamwa",
  "{count} imetazamwa",
  "mwisho {when}",
  "Mgeni aliyeingia",
  "Ungependa kufuta tangazo hili?",
  "“{title}” itaondolewa kwenye uorodheshaji unaotumika. Bado unaweza kuiona wakati uorodheshaji uliohifadhiwa kwenye kumbukumbu umewashwa.",
  "Ghairi",
  "Futa uorodheshaji",
  "Property",
  "Aina",
  "Bei",
  "Hali",
  "Maoni",
  "Imesasishwa",
  "Vitendo",
  "Studio ya maudhui",
  "Andika orodha ambazo zitatambuliwa",
  "Ongeza ukweli wa mali mara moja na uruhusu AI ibadilishe kuwa nakala iliyoboreshwa ya uuzaji. Kagua kila undani kabla ya kuchapisha.",
  "AI Listing Writer iko kwenye Pro na Business",
  "Boresha ili kutoa nakala ya uorodheshaji kitaalamu kutoka kwa ukweli wa mali yako.",
  "Kwingineko akili",
  "Uchanganuzi wa hali ya juu",
  "Elewa mchanganyiko wako wa orodha, shughuli, na utayari wa maudhui kutoka kwa data ambayo tayari unayo.",
  "Onyesha upya",
  "Uchanganuzi uko kwenye Pro na Business",
  "Boresha ili uone mchanganyiko wa orodha, shughuli na utayari wa maudhui.",
  "Hatukuweza kukokotoa uchanganuzi. Angalia ruhusa za mkusanyiko na ujaribu tena.",
  "Orodha iliyofuatiliwa",
  "Orodha katika mkusanyiko",
  "AI-ready maudhui",
  "Orodha zilizo na sehemu za AI zilizojaa",
  "Miji hai",
  "Miji mitano bora iliyoonyeshwa hapa chini",
  "Ishara ya shughuli",
  "Orodha ziliongezwa katika miezi sita iliyopita",
  "Shughuli ya kuorodhesha",
  "Rekodi mpya zilizoundwa katika miezi sita iliyopita ya kalenda.",
  "Miji ya juu",
  "Ongeza maeneo ili kuona mkusanyiko wa kijiografia.",
  "Promchanganyiko mzuri",
  "Mali iliyopangwa kulingana na aina ya mali.",
  "Ongeza matangazo ili kuona mchanganyiko wa mali yako.",
  "Bei ya wastani ya kuuliza",
  "Imepangwa kulingana na sarafu ili kuweka ulinganisho kuwa wa maana.",
  "Ongeza matangazo ili kuona mawimbi ya bei.",
  "{count} uorodheshaji",
  "{count} matangazo",
  "Hali ya uorodheshaji",
  "Uchanganuzi wako wa hali utaonekana mara uorodheshaji unapoongezwa.",
  "Mchanganyiko wa shughuli",
  "Mchanganyiko wako wa ununuzi utaonekana mara uorodheshaji unapoongezwa.",
  "Uchanganuzi hukokotolewa kutoka kwa mkusanyiko wa sasa wa uorodheshaji na kuonyesha upya inapohitajika.",
  "Hakuna data ya kuorodheshwa bado",
  "Usambazaji wa sasa katika orodha yako.",
  "Mipango ya programu",
  "Chagua mpango unaolingana na hesabu yako",
  "Jaribio lako lisilolipishwa linajumuisha kila kipengele cha Business. Baada ya kukamilika, tovuti ya moja kwa moja na zana za lango hufuata mpango wako unaotumika.",
  "Anza kwenye Basic ili kuchapisha uorodheshaji na kukusanya manukuu. Pata toleo jipya la Pro au Business unapohitaji nakala ya AI, 360° ziara, uchanganuzi na zana zaidi za uuzaji.",
  "Mpango wa sasa",
  "Jaribio la bure",
  "Maarufu zaidi",
  "Ulinganisho wa kipengele",
  "Ni nini kimejumuishwa kwenye Basic, Pro, na Business.",
  "Kipengele",
  "Imejumuishwa",
  "Haijajumuishwa",
  "Basic",
  "Pro",
  "Business",
  "Bure",
  "Imejumuishwa na programu",
  "kwa mwezi",
  "Chapisha hesabu ndogo na kukusanya maswali kutoka kwa tovuti.",
  "Nakala ya AI, ziara 360°, maarifa ya wageni, na uchanganuzi wa kwingineko.",
  "Orodha zisizo na kikomo, msaidizi wa AI kwenye tovuti, na zana kamili za uuzaji.",
  "Orodha zinazotumika",
  "Hadi 10",
  "Hadi 50",
  "Bila kikomo",
  "Orodha na wijeti za maelezo ya mali",
  "Anwani ya mmiliki kwenye kurasa za kuorodhesha",
  "Fomu ya ombi la kunukuu",
  "Mali zilizohifadhiwa kwa wanachama",
  "AI Listing Writer",
  "360° ziara ya mtandaoni",
  "Maarifa ya kipekee ya wageni",
  "Uchambuzi wa kwingineko",
  "Kushiriki kijamii kwenye kurasa za kuorodhesha",
  "Arifa za barua pepe za ombi la nukuu",
  "Msaidizi wa AI wa mali kwenye tovuti",
  "Orodha zinazohusiana kwenye kurasa za mali",
  "Mandhari 360° nyingi za ziara",
  "Msaada wa kipaumbele",
  "Mapendeleo ya nafasi ya kazi",
  "Mipangilio",
  "Weka chaguo-msingi zinazofaa kwa uorodheshaji mpya na uweke nafasi ya kazi ikilenga rekodi ambazo timu yako inadhibiti kikamilifu.",
  "Chaguomsingi za kuorodhesha",
  "Mapendeleo haya hujaza uorodheshaji mpya. Rekodi zilizopo hazibadilishwa.",
  "Sarafu chaguo-msingi",
  "Sarafu iliyochaguliwa mapema kwa bei mpya za uorodheshaji.",
  "Chagua kutoka kwa orodha kamili ya ISO 4217 ya sarafu.",
  "Kitengo cha eneo chaguomsingi",
  "Kitengo cha kipimo kilichaguliwa mapema kwa maeneo mapya ya kuorodhesha.",
  "Inatumika kwa uga wa eneo kwenye rekodi mpya.",
  "Hali chaguomsingi ya uorodheshaji",
  "Hali ya mtiririko wa kazi iliyokabidhiwa kwa uorodheshaji mpya.",
  "Orodha mpya hufunguliwa kwa hatua hii ya mtiririko wa kazi.",
  "Jumuisha matangazo yaliyohifadhiwa kwenye kumbukumbu",
  "Inapowashwa, uorodheshaji uliohifadhiwa kwenye kumbukumbu huonekana katika mwonekano wa Matangazo kwa chaguomsingi.",
  "Weka rekodi zilizohifadhiwa zionekane katika mwonekano wa Matangazo kwa chaguomsingi.",
  "Lugha ya dashibodi",
  "Chagua lugha ya nafasi hii ya kazi, au ufuate Wix lugha ya akaunti.",
  "Auto (Wix account language)",
  "Imehifadhiwa ndani kwa kivinjari hiki",
  "Mabadiliko bado hayajahifadhiwa",
  "Weka upya",
  "Hifadhi mipangilio",
  "Mipangilio ya nafasi ya kazi imehifadhiwa.",
  "Mipangilio haikuweza kuhifadhiwa katika kivinjari hiki.",
  "Saved Properties kizindua",
  "Pachika au urejeshe kitufe cha vipengele vilivyohifadhiwa vya mwanachama na droo kwenye tovuti yako ya moja kwa moja.",
  "Ni salama kukimbia zaidi ya mara moja.",
  "Pachika kizindua",
  "Inapachika...",
  "Saved Properties kizindua kinatumika kwenye tovuti.",
  "Kizindua hakikuweza kupachikwa.",
  "Msaada: {hint}",
  "Usimamizi wa kiongozi",
  "Maombi ya kunukuu",
  "Kagua maswali ya mali na usasishe hali ya ufuatiliaji.",
  "Maombi yanayoingia",
  "{count} ombi",
  "{count} maombi",
  "Tafuta mali",
  "Tafuta maombi ya bei",
  "Chuja maombi ya bei kulingana na hali",
  "Onyesha upya maombi ya bei",
  "Maombi ya nukuu hayakuweza kupakiwa.",
  "Ombi halikuweza kusasishwa.",
  "Hakuna maombi ya bei yanayolingana na vichujio hivi.",
  "Hakuna ujumbe uliotolewa.",
  "Vidokezo vya ndani",
  "Vidokezo vya {title}",
  "Hali ya {title}",
  "Hifadhi",
  "Ukurasa {current}",
  "Iliyotangulia",
  "Inayofuata",
  "Mpya",
  "Umewasiliana",
  "Imenukuliwa",
  "Imefungwa",
  "Kuanza",
  "Jinsi ya kutumia nafasi hii ya kazi",
  "Unda uorodheshaji hapa, uyachapishe ukitumia wijeti za tovuti, kisha ufuatilie maombi ya bei na shughuli za wageni kutoka kwenye dashibodi hii.",
  "Njia iliyopendekezwa",
  "Ongeza angalau tangazo moja linaloendelea, weka wijeti kwenye tovuti yako, kisha uangalie maombi ya Nukuu baada ya mgeni kuwasilisha swali.",
  "Hatua {n}",
  "Unda na udhibiti uorodheshaji",
  "Weka kila mali katika hesabu moja.",
  "Ongeza tangazo lenye eneo, bei, picha, na ziara ya hiari 360°.",
  "Anwani ya wakala/mmiliki hujazwa kutoka kwa mmiliki wa tovuti na inaweza kuhaririwa kwa kila tangazo.",
  "Tumia menyu ya vitendo vya kuorodhesha kuhariri, kukagua wageni wa kipekee, au kufuta.",
  "Orodha zinazotumika pekee ndizo zinazoonekana kwenye tovuti ya moja kwa moja.",
  "Chapisha matangazo kwenye tovuti",
  "Onyesha maelezo ya hesabu na mali kwa wageni.",
  "Ongeza wijeti ya orodha za mali kwenye ukurasa kama vile /properties.",
  "Ongeza wijeti ya maelezo ya mali kwenye ukurasa kama vile /property-details.",
  "Katika kihariri, washa au zima Anwani, ombi la nukuu, shiriki na uorodheshaji husika.",
  "Pachika Saved Properties kizindua kutoka kwa Mipangilio ili wanachama waweze kualamisha nyumba.",
  "Fungua mipangilio",
  "Kushughulikia maswali ya wageni",
  "Ruhusu wanunuzi wawasiliane nawe bila kuondoka kwenye tangazo.",
  "Wageni huona jina la mmiliki, simu na barua pepe kwenye ukurasa wa mali wakati Anwani imewashwa.",
  "Ombi la bei hukusanya jina, barua pepe, simu na ujumbe ulioumbizwa.",
  "Maombi mapya yanaonekana hapa yakiwa na hali, madokezo na kumbukumbu.",
  "Arifa za nukuu hutumia barua pepe ya wakala wa kuorodhesha na barua pepe ya mmiliki wa tovuti.",
  "Fungua maombi ya bei",
  "Andika nakala ya orodha na AI",
  "Geuza ukweli kuwa maelezo tayari kwa uuzaji.",
  "Fungua AI Listing Writer au tumia Andika ukitumia AI ndani ya kihariri cha uorodheshaji.",
  "Kagua nakala iliyotolewa, kisha uihifadhi kwenye tangazo kabla ya kuichapisha.",
  "Tumia Analytics ili kuona ni tangazo zipi zinazovutia kutazamwa zaidi.",
  "Unahitaji msaada zaidi",
  "Chaguo-msingi za nafasi ya kazi na usaidizi",
  "Weka sarafu chaguo-msingi, kitengo cha eneo na hali katika Mipangilio. Wasiliana na msanidi programu kutoka kwa utepe ikiwa wijeti au mkusanyiko haupo baada ya kusakinisha.",
  "Ongeza tangazo",
  "Badilisha tangazo",
  "Weka maelezo ya mali yako kuwa sahihi na tayari kwa kuchapishwa.",
  "Imeshindwa kufungua tangazo hili",
  "Rudi kwenye matangazo",
  "Orodha hii haikuweza kupatikana.",
  "Orodha hii haikuweza kupakiwa.",
  "{title} ilisasishwa.",
  "{title} iliongezwa.",
  "Orodha haikuweza kuhifadhiwa.",
  "{title} iliwekwa kwenye kumbukumbu.",
  "Orodha haikuweza kuhifadhiwa kwenye kumbukumbu.",
  "Unda tangazo jipya",
  "Badilisha maelezo ya uorodheshaji",
  "Prohadithi nzuri",
  "Tumia kihariri kuongeza maelezo yaliyoboreshwa, yaliyopangwa.",
  "Kichwa",
  "Jina fupi linalotambulisha mali hii.",
  "Nyumba yenye vyumba vitatu iliyojaa mwanga huko Austin, TX",
  "Maelezo",
  "Eleza mali, mpangilio, faini, na sehemu za kuuza.",
  "Andika na AI",
  "AI writer (Pro)",
  "Inapakia kihariri...",
  "Anwani",
  "Ingiza anwani ya mtaa au maelezo ya eneo la mali.",
  "Anwani ya mtaa au mtaa",
  "Jiji",
  "Chagua jiji lililopendekezwa au uweke mwenyewe.",
  "Ingiza au chagua jiji",
  "Nchi",
  "Jimbo / mkoa",
  "Kuorodhesha picha",
  "Chagua picha kutoka Wix Media Manager; picha ya kwanza ni kifuniko.",
  "Picha ya kwanza inatumika kama kifuniko kwenye kadi na ukurasa wa mali.",
  "Chagua picha",
  "Ongeza picha",
  "Bado hakuna picha zilizochaguliwa.",
  "Ondoa picha {n}",
  "360° ziara ya mtandaoni",
  "Ongeza picha 360° za mstatili kwa kitazamaji Three.js shirikishi. Wageni wanaweza kubadilisha kati ya vyumba na mitazamo.",
  " Ziara za mtandaoni zimejumuishwa kwenye Pro na Business; picha za ziada hukaa kwenye dashibodi ikiwa utaziongeza sasa.",
  " Pro tovuti zinaonyesha onyesho la kwanza; matukio ya ziada yataonyeshwa moja kwa moja kwenye Business.",
  "360° picha za panorama",
  "Chagua picha 360° za mstatili kwa kitazamaji Three.js shirikishi. Wageni wanaweza kubadilisha kati ya matukio.",
  "Hiari. Kila picha inapaswa kuwa ya mstatili 360° picha.",
  "Hakuna panorama 360° zilizochaguliwa.",
  "Ondoa panorama {n}",
  "Onyesho {n}",
  "Kuorodhesha ukweli",
  "Sehemu hizi za vichujio vya nguvu na uchanganuzi wa kwingineko.",
  "Aina ya muamala",
  "Ikiwa mali hiyo inauzwa, kukodishwa, au kukodisha.",
  "Kategoria inayoelezea vyema mali.",
  "Hatua ya sasa ya utendakazi kwa uorodheshaji huu.",
  "Prohali isiyofaa",
  "Hali ya sasa ya mali hiyo.",
  "Hali ya samani",
  "Ikiwa mali hiyo haina fanicha, imetolewa kwa sehemu, au imetolewa.",
  "Umiliki",
  "Mpangilio wa umiliki au kukodisha kwa mali hiyo.",
  "Mzunguko wa kukodisha",
  "Ni mara ngapi ukodishaji unatarajiwa kwa uorodheshaji wa kukodisha au kukodisha.",
  "Bei",
  "Bei ya kuorodheshwa katika sarafu iliyochaguliwa.",
  "Sarafu",
  "Sarafu ya herufi tatu inayotumika kwa bei ya kuorodhesha.",
  "Eneo",
  "Saizi ya mali katika kitengo cha eneo kilichochaguliwa.",
  "Kitengo cha eneo",
  "Vistawishi",
  "Orodhesha vipengele mashuhuri vilivyotenganishwa na koma.",
  "Bwawa la kuogelea, ukumbi wa michezo, usalama wa 24/7",
  "Tarehe ya kupatikana",
  "Tarehe ambayo mali itapatikana.",
  "Anwani ya wakala/mmiliki",
  "Jina",
  "Wakala au mmiliki anayehusika na tangazo hili.",
  "Jina la wakala au mmiliki",
  "Simu",
  "Nambari ya simu ya kuorodhesha maswali.",
  "Nambari ya simu ya kimataifa",
  "Barua pepe",
  "Barua pepe ya maswali ya kuorodhesha.",
  "Uwekaji wa ramani",
  "Latitudo",
  "Latitudo ya mali inayotumika kwa uwekaji ramani.",
  "Longitude",
  "Longitudo ya mali inayotumika kwa uwekaji ramani.",
  "Hifadhi tangazo",
  "Inahifadhi...",
  "AI writer",
  "Ukweli kutoka kwa orodha hii hujazwa kwa ajili yako. Wakati kuandika kukamilika, maelezo kwenye fomu husasishwa kiotomatiki.",
  "Maelezo ya tangazo yalisasishwa.",
  "Media Manager haikuweza kufunguliwa.",
  "Chagua {label}",
  "Thamani ya {label} ya hiari ya uorodheshaji huu.",
  "Hiari",
  "Vyumba vya kulala",
  "Vyumba vya bafu",
  "Mwaka uliojengwa",
  "Nafasi za maegesho",
  "Malipo ya huduma",
  "Amana ya usalama",
  "Inahitajika",
  "Ongeza kichwa.",
  "Ongeza anwani.",
  "Ongeza jiji.",
  "Ongeza bei.",
  "Ongeza eneo.",
  "Rekebisha sehemu zilizoangaziwa kabla ya kuhifadhi.",
  "Mapendekezo ya eneo hayakuweza kupakiwa. Bado unaweza kuandika thamani.",
  "Promisingi ya msingi",
  "Je, maelezo yanapaswa kusema nini?",
  "Mahali",
  "Austin, Texas",
  "$875,000",
  "Bwawa la kuogelea, mazoezi, maegesho",
  "Mtindo wa kuandika",
  "Tengeneza maelezo",
  "Inaandika maelezo yako...",
  "Maelezo yaliyotolewa",
  "Wakati kuandika kukamilika, nakala hii huongezwa kwa maelezo ya tangazo.",
  "Kagua nakala, kisha uinakili kwenye tangazo lako.",
  "Nakili",
  "Imenakiliwa",
  "Maelezo ya mali inayozalishwa",
  "Nakala yako iliyoboreshwa itaonekana hapa",
  "Chagua mtindo na utoe maelezo kutoka kwa ukweli wa mali uliothibitishwa.",
  "Proya kitaalamu",
  "Wazi na wa kuaminika",
  "Anasa",
  "Imeinuliwa na yenye matarajio",
  "Mfupi",
  "Kamili kwa kadi",
  "SEO imeboreshwa",
  "Nakala ya utaftaji",
  "Mitandao ya kijamii",
  "Inashirikisha na inashirikiwa",
  "Samani",
  "Semi-furnished",
  "Isiyo na samani",
  "Maelezo hayakuweza kuzalishwa.",
  "AI Listing Writer inapatikana kwenye Pro na Business.",
  "Shiriki nakala yako ya tangazo",
  "Fikia wanunuzi popote wanapotumia muda.",
  "Ongeza vituo",
  "Vituo zaidi vya kushiriki",
  "Chagua jukwaa la kushiriki nakala ya uorodheshaji iliyotolewa. Baadhi ya vituo vinakili nukuu kwanza ili uweze kuongeza picha na kuzichapisha kawaida.",
  "WhatsApp",
  "Tuma kwa mwasiliani au kikundi",
  "Facebook",
  "Shiriki kwenye mpasho wako",
  "Instagram",
  "Nakili maelezo mafupi na ufungue Instagram",
  "X",
  "Chapisha kwenye kalenda yako ya matukio",
  "LinkedIn",
  "Shiriki na mtandao wako",
  "Telegram",
  "Tuma kwa gumzo au kituo",
  "Pinterest",
  "Nakili maelezo mafupi na ufungue Pinterest",
  "Reddit",
  "Wasilisha kwa jumuiya",
  "Threads",
  "Nakili maelezo mafupi na ufungue Threads",
  "TikTok",
  "Nakili maelezo mafupi na ufungue TikTok",
  "YouTube",
  "Nakili maelezo mafupi na ufungue YouTube",
  "Snapchat",
  "Nakili maelezo mafupi na ufungue Snapchat",
  "Barua pepe",
  "Fungua programu yako ya barua pepe",
  "Ujumbe wa maandishi",
  "Tuma kama ujumbe wa maandishi",
  "Proorodha ya watu wengine",
  "Maelezo ya uorodheshaji",
  "Eleza mwanga, mpangilio, faini, na sababu za kupenda mali hii…",
  "Picha hazikuweza kuongezwa kwa maelezo.",
  "Video hazikuweza kuongezwa kwa maelezo.",
  "Rasimu",
  "Inayotumika",
  "Chini ya ofa",
  "Inauzwa",
  "Imehifadhiwa",
  "Inauzwa",
  "Kwa kukodisha",
  "Kwa kukodisha",
  "Nyumba",
  "Ghorofa",
  "Condo",
  "Nyumba ya jiji",
  "Ardhi",
  "Ofisi",
  "Rejareja",
  "Viwandani",
  "Mchanganyiko wa matumizi",
  "Nyingine",
  "Miguu ya mraba",
  "Mita za mraba",
  "Ekari",
  "Mpya",
  "Nzuri",
  "Inahitaji ukarabati",
  "Bure",
  "Ukodishaji",
  "Kila mwezi",
  "Kila mwaka",
  "Mita za mraba",
  "Ekari",
  "Mpya",
  "Nzuri",
  "Inahitaji ukarabati",
  "Bure",
  "Ukodishaji",
  "Kila mwezi",
  "Kila mwaka",
  "English",
  "中文",
  "हिन्दी",
  "Español",
  "العربية",
  "Français",
  "বাংলা",
  "Português",
  "Русский",
  "اردو",
  "Bahasa Indonesia",
  "Deutsch",
  "日本語",
  "Kiswahili",
  "Türkçe",
  "한국어",
  "Tiếng Việt",
  "Italiano",
  "ไทย",
  "Polski",
]);
