import { zip } from "../zip";

export const tr = zip([
  "EstateAI",
  "Çalışma alanı listeleniyor",
  "Genel Bakış",
  "İlanlar",
  "AI Listing Writer",
  "Analitik",
  "Rehber",
  "Fiyatlandırma",
  "Ayarlar",
  "Fiyat teklifi istekleri",
  "Çalışma alanı",
  "Promülk envanteri",
  "İçerik stüdyosu",
  "Potansiyel müşteri yönetimi",
  "Portföy zekası",
  "Başlarken",
  "Planlar",
  "Çalışma alanı tercihleri",
  "Gezinmeyi değiştir",
  "Uygulama geliştiricisiyle iletişime geçin",
  "Deneme",
  "Wix",
  "Planı",
  "Sitede sınırsız sayıda liste görülebilir.",
  "{visible} / {cap} listeleri sitede görünüyor.",
  "Ücretsiz denemeyi başlat",
  "Planları görüntüle",
  "seni görmek güzel",
  "Gayrimenkul çalışma alanınız",
  "Envanterinizi düzenli tutun, hareketi hızlı bir şekilde tespit edin ve her listeyi destekli yayınlamaya hazırlayın. Burada yeni misin? {guide}'yi takip edin.",
  "çalışma alanı kılavuzu",
  "Liste ekle",
  "Yeniden dene",
  "Genel bakışınızı yükleyemedik. Toplama izinlerini kontrol edin ve tekrar deneyin.",
  "Toplam listeler",
  "Çalışma alanınızın genelinde",
  "Aktif",
  "Şu anda mevcut",
  "Teklif altında",
  "Bir anlaşmaya varmak",
  "Satıldı",
  "Tamamlanan işlemler",
  "Son listeler",
  "Çalışma alanınıza eklenen veya güncellenen en son özellikler.",
  "Tümünü görüntüle",
  "Envanteriniz ilk listelenmeye hazır",
  "Portföyünüzü izlemeye başlamak ve analizlerin kilidini açmak için bir mülk ekleyin.",
  "Listeleri aç",
  "Konum ayarlanmadı",
  "Sonraki odak",
  "Ayrıntıları ivmeye dönüştürün",
  "Onaylanmış mülk bilgilerinizi saniyeler içinde profesyonel, lüks, kısa, SEO veya sosyal kullanıma hazır kopyaya dönüştürün.",
  "AI writer'yi aç",
  "AI writer kilidini aç",
  "Envanter yönetimi",
  "Tüm listeler",
  "Her mülkü arayın, düzenleyin ve bir sonraki aşamaya hazır tutun.",
  "Yayındaki site, {cap} plan sınırınızın {visible} en son güncellenen aktif listelerini gösterir.",
  "Promülk envanteri",
  "Bu çalışma alanında {count} listeleme",
  "Bu çalışma alanındaki {count} listeleri",
  "Başlık veya şehri arayın",
  "Listeleri arayın",
  "Duruma göre filtrele",
  "Mülk türüne göre filtrele",
  "Durum",
  "Proözellik türü",
  "Tüm durumlar",
  "Tüm türler",
  "Önceki sayfa",
  "Sonraki sayfa",
  "Sayfa {current} / {total}",
  "{title} için işlemler",
  "Düzenle",
  "Benzersiz ziyaretçiler",
  "Sil",
  "Listeleri yükleyemedik. Toplama izinlerini kontrol edin ve tekrar deneyin.",
  "Bu filtrelerle eşleşen ilan yok.",
  "İlk listelemenizi oluşturun veya aramayı ve filtreleri ayarlayın.",
  "Listeler yükleniyor",
  "Tüm mülk türleri",
  "Kapak resmi",
  "Resim {n}",
  "Bu liste için bir başlık girin.",
  "Üç harfli bir para birimi kodu kullanın.",
  "Geçerli bir fiyat girin.",
  "Geçerli bir alan girin.",
  "Bir ülke seçin.",
  "Bir eyalet veya bölge seçin.",
  "Şehri veya bölgeyi girin.",
  "Sokak adresini girin.",
  "Geçerli bir e-posta adresi girin.",
  "Geçerli bir telefon numarası girin.",
  "Geçerli bir numara girin.",
  "Bir tam sayı girin.",
  "Mülkün bulunduğu ülke.",
  "Mülkün bulunduğu eyalet, il veya bölge.",
  "Mülkiyet alanını ölçmek için kullanılan birim.",
  "Ülkeler yüklenemedi.",
  "Devletler yüklenemedi.",
  "Şehirler yüklenemedi.",
  "Şu ana kadarki görüntülemeler imzasız ziyaretçilere ait olduğundan benzersiz kullanıcılar listelenemez.",
  "Austin, Teksas'ta çağdaş 3 yatak odalı ev",
  "<p>Modern yüzeylere, mükemmel doğal ışığa ve iki araçlık garaja sahip aydınlık ve ferah ev. Mağazalara, restoranlara ve ana ulaşım yollarına yakın konum.</p><p>İyi bağlantılara sahip bir mahallede rahat bir ev arayan profesyoneller veya büyüyen bir aile için idealdir.</p>",
  "Yüzme havuzu, Spor salonu, Garaj, Merkezi havalandırma",
  "Benzersiz ziyaretçiler",
  "“{title}”yi görüntüleyenlerin her biri bir kez sayıldı.",
  "Benzersiz ziyaretçiler yükleniyor",
  "Benzersiz ziyaretçiler yüklenemedi. Tekrar deneyin.",
  "Bu ilanı henüz kimse görmedi.",
  "{count} benzersiz ziyaretçi",
  "{count} tekil ziyaretçi",
  "{count} imzasız görünüm",
  "{count} imzasız görüntülemeler",
  "{count} görünümü",
  "{count} görüntüleme",
  "son {when}",
  "Oturum açmış ziyaretçi",
  "Bu giriş silinsin mi?",
  "“{title}” aktif listelemelerden kaldırılacak. Arşivlenmiş listeler etkinleştirildiğinde yine de görüntüleyebilirsiniz.",
  "İptal",
  "İlanı sil",
  "Promülk",
  "Tür",
  "Fiyat",
  "Durum",
  "Görünümler",
  "Güncellendi",
  "Eylemler",
  "İçerik stüdyosu",
  "Dikkat çeken listeler yazın",
  "Mülkiyet bilgilerini bir kez ekleyin ve yapay zekanın bunları gösterişli pazarlama kopyalarına dönüştürmesine izin verin. Yayınlamadan önce her ayrıntıyı inceleyin.",
  "AI Listing Writer, Pro ve Business üzerindedir",
  "Mülk bilgilerinizden profesyonel listeleme kopyası oluşturmak için yükseltme yapın.",
  "Portföy zekası",
  "Gelişmiş analitik",
  "Halihazırda sahip olduğunuz verilerden envanter karışımınızı, etkinliğinizi ve içerik hazırlığınızı anlayın.",
  "Yenile",
  "Analytics Pro ve Business üzerindedir",
  "Envanter karışımını, etkinliği ve içerik hazırlığını görmek için yükseltme yapın.",
  "Analitikleri hesaplayamadık. Toplama izinlerini kontrol edin ve tekrar deneyin.",
  "Takip edilen envanter",
  "Koleksiyondaki listeler",
  "AI-ready içeriği",
  "AI alanları doldurulmuş listeler",
  "Aktif şehirler",
  "Aşağıda gösterilen ilk beş şehir",
  "Etkinlik sinyali",
  "Son altı ayda eklenen ilanlar",
  "Listeleme etkinliği",
  "Son altı takvim ayında oluşturulan yeni kayıtlar.",
  "En popüler şehirler",
  "Coğrafi yoğunluğu görmek için konum ekleyin.",
  "Proözel karışım",
  "Envanter mülk türüne göre gruplandırılmıştır.",
  "Mülk karışımınızı görmek için liste ekleyin.",
  "Ortalama istenen fiyat",
  "Karşılaştırmaları anlamlı kılmak için para birimine göre gruplandırılmıştır.",
  "Fiyatlandırma sinyallerini görmek için liste ekleyin.",
  "{count} listeleme",
  "{count} listeleri",
  "İlan durumu",
  "İlanlar eklendiğinde durum dökümünüz görünecektir.",
  "İşlem karışımı",
  "Listelemeler eklendiğinde işlem karışımınız görünecektir.",
  "Analizler, mevcut listelerin toplanmasından hesaplanır ve talep üzerine yenilenir.",
  "Henüz listeleme verisi yok",
  "Envanterinizdeki mevcut dağıtım.",
  "Uygulama planları",
  "Envanterinize uygun planı seçin",
  "Ücretsiz denemeniz tüm Business özelliklerini içerir. Bittikten sonra canlı site ve güvenlikli araçlar aktif planınızı takip eder.",
  "Listelemeleri yayınlamak ve fiyat teklifleri toplamak için Basic ile başlayın. Yapay zeka kopyalarına, 360° turlarına, analizlere ve daha fazla pazarlama aracına ihtiyaç duyduğunuzda Pro veya Business sürümüne yükseltin.",
  "Mevcut plan",
  "Ücretsiz deneme",
  "En popüler",
  "Özellik karşılaştırması",
  "Basic, Pro ve Business'de neler bulunur?",
  "Özellik",
  "Dahil",
  "Dahil değil",
  "Basic",
  "Pro",
  "Business",
  "Ücretsiz",
  "Uygulamaya dahil",
  "aylık",
  "Küçük bir envanter yayınlayın ve siteden gelen soruları toplayın.",
  "Yapay zeka kopyası, 360° turları, ziyaretçi analizleri ve portföy analizleri.",
  "Sınırsız listeleme, yerinde yapay zeka asistanı ve eksiksiz pazarlama araçları.",
  "Aktif listeler",
  "10'a kadar",
  "50'ye kadar",
  "Sınırsız",
  "Listeler ve mülk ayrıntısı widget'ları",
  "Listeleme sayfalarında sahip iletişim bilgileri",
  "Teklif talep formu",
  "Üyeler için kayıtlı mülkler",
  "AI Listing Writer",
  "360° sanal tur",
  "Benzersiz ziyaretçi görüşleri",
  "Portföy analitiği",
  "Listeleme sayfalarında sosyal paylaşım",
  "Fiyat teklifi isteği e-posta bildirimleri",
  "Tesis içi mülk yapay zeka asistanı",
  "Mülk sayfalarındaki ilgili listeler",
  "Çoklu 360° tur sahneleri",
  "Öncelikli destek",
  "Çalışma alanı tercihleri",
  "Ayarlar",
  "Yeni listeler için makul varsayılanlar belirleyin ve çalışma alanının ekibinizin aktif olarak yönettiği kayıtlara odaklanmasını sağlayın.",
  "Varsayılanları listeleme",
  "Bu tercihler yeni listeleri önceden doldurur. Mevcut kayıtlar değiştirilmez.",
  "Varsayılan para birimi",
  "Yeni listeleme fiyatları için önceden seçilen para birimi.",
  "Tam ISO 4217 para birimi listesinden seçim yapın.",
  "Varsayılan alan birimi",
  "Yeni listeleme alanları için önceden seçilen ölçüm birimi.",
  "Yeni kayıtlarda alan alanına uygulanır.",
  "Varsayılan listeleme durumu",
  "Yeni listelere atanan iş akışı durumu.",
  "Bu iş akışı aşamasıyla yeni listeler açılır.",
  "Arşivlenmiş listeleri dahil et",
  "Etkinleştirildiğinde, arşivlenen listeler varsayılan olarak Listeler görünümünde görünür.",
  "Arşivlenen kayıtları varsayılan olarak Listeler görünümünde görünür tutun.",
  "Kontrol paneli dili",
  "Bu çalışma alanının dilini seçin veya Wix hesap dilini izleyin.",
  "Auto (Wix account language)",
  "Bu tarayıcı için yerel olarak kaydedildi",
  "Değişiklikler henüz kaydedilmedi",
  "Sıfırla",
  "Ayarları kaydet",
  "Çalışma alanı ayarları kaydedildi.",
  "Ayarlar bu tarayıcıya kaydedilemedi.",
  "Saved Properties başlatıcı",
  "Üyenin kayıtlı özellikleri düğmesini ve çekmecesini canlı sitenize ekleyin veya geri yükleyin.",
  "Birden fazla kez çalıştırmak güvenlidir.",
  "Başlatıcıyı yerleştir",
  "Yerleştiriliyor…",
  "Saved Properties başlatıcısı sitede aktif.",
  "Başlatıcı yerleştirilemedi.",
  "Yardım: {hint}",
  "Potansiyel müşteri yönetimi",
  "Fiyat teklifi istekleri",
  "Mülk sorgularını inceleyin ve takip durumunu güncel tutun.",
  "Gelen istekler",
  "{count} isteği",
  "{count} istekleri",
  "Mülk ara",
  "Fiyat teklifi isteklerini ara",
  "Fiyat teklifi isteklerini duruma göre filtreleyin",
  "Fiyat teklifi isteklerini yenile",
  "Fiyat teklifi istekleri yüklenemedi.",
  "İstek güncellenemedi.",
  "Bu filtrelerle eşleşen fiyat teklifi isteği yok.",
  "Mesaj verilmedi.",
  "Dahili notlar",
  "{title} için notlar",
  "{title} durumu",
  "Arşiv",
  "Sayfa {current}",
  "Önceki",
  "Sonraki",
  "Yeni",
  "İletişime geçildi",
  "Alıntı yapıldı",
  "Kapalı",
  "Başlarken",
  "Bu çalışma alanı nasıl kullanılır?",
  "Burada listeler oluşturun, bunları site widget'larıyla yayınlayın, ardından bu kontrol panelinden fiyat teklifi isteklerini ve ziyaretçi faaliyetlerini takip edin.",
  "Önerilen yol",
  "En az bir aktif liste ekleyin, widget'ları sitenize yerleştirin ve ardından bir ziyaretçi bir sorgu gönderdikten sonra Fiyat Teklifi isteklerini kontrol edin.",
  "Adım {n}",
  "Liste oluşturma ve yönetme",
  "Her mülkü tek bir envanterde tutun.",
  "Konum, fiyat, görseller ve isteğe bağlı 360° turunu içeren bir liste ekleyin.",
  "Acente/sahip iletişim bilgileri site sahibinden doldurulur ve ilan bazında düzenlenebilir.",
  "Benzersiz ziyaretçileri düzenlemek, incelemek veya silmek için listeleme işlemleri menüsünü kullanın.",
  "Yayındaki sitede yalnızca etkin listeler görünür.",
  "Listeleri sitede yayınlayın",
  "Ziyaretçilere envanter ve mülk ayrıntılarını gösterin.",
  "Emlak listeleri widget'ını /properties gibi bir sayfaya ekleyin.",
  "Özellik ayrıntısı widget'ını /property-details gibi bir sayfaya ekleyin.",
  "Düzenleyicide İletişim, fiyat teklifi isteği, paylaşım ve ilgili listeleri açın veya kapatın.",
  "Üyelerin evlere yer işareti koyabilmesi için Ayarlar'dan Saved Properties başlatıcısını ekleyin.",
  "Ayarları aç",
  "Ziyaretçi sorularını ele almak",
  "Alıcıların listeden ayrılmadan sizinle iletişime geçmesine izin verin.",
  "Ziyaretçiler, İletişim etkinleştirildiğinde mülk sayfasında sahibinin adını, telefonunu ve e-posta adresini görür.",
  "Fiyat teklifi isteği, adı, e-postayı, telefonu ve biçimlendirilmiş bir mesajı toplar.",
  "Yeni istekler burada durum, notlar ve arşivle birlikte görünür.",
  "Fiyat teklifi bildirimleri, ilan acentesi e-postasını ve site sahibi e-postasını kullanır.",
  "Fiyat teklifi isteklerini aç",
  "Liste kopyasını AI ile yazın",
  "Gerçekleri pazarlamaya hazır açıklamalara dönüştürün.",
  "AI Listing Writer'yi açın veya liste düzenleyicide Yapay Zeka ile Yaz'ı kullanın.",
  "Oluşturulan kopyayı inceleyin ve yayınlamadan önce listeye kaydedin.",
  "Hangi listelerin en çok görüntülemeyi çektiğini görmek için Analytics'i kullanın.",
  "Daha fazla yardıma ihtiyacım var",
  "Çalışma alanı varsayılanları ve desteği",
  "Ayarlar'da varsayılan para birimini, alan birimini ve durumu ayarlayın. Yüklemeden sonra bir widget veya koleksiyon eksikse kenar çubuğundan uygulama geliştiricisiyle iletişime geçin.",
  "Liste ekle",
  "İlanı düzenle",
  "Mülk bilgilerinizi doğru ve yayına hazır tutun.",
  "Bu liste açılamıyor",
  "Listelere dön",
  "Bu liste bulunamadı.",
  "Bu liste yüklenemedi.",
  "{title} güncellendi.",
  "{title} eklendi.",
  "Liste kaydedilemedi.",
  "{title} arşivlendi.",
  "Liste arşivlenemedi.",
  "Yeni bir liste oluştur",
  "Listeleme ayrıntılarını düzenleyin",
  "Promülk hikayesi",
  "Gösterişli, yapılandırılmış bir açıklama eklemek için düzenleyiciyi kullanın.",
  "Başlık",
  "Bu özelliği tanımlayan kısa bir ad.",
  "Austin, Teksas'ta ışık dolu 3 yatak odalı ev",
  "Açıklama",
  "Mülkü, düzeni, bitişleri ve satış noktalarını açıklayın.",
  "Yapay zeka ile yazın",
  "AI writer (Pro)",
  "Düzenleyici yükleniyor…",
  "Adres",
  "Sokak adresini veya mülkün konum ayrıntılarını girin.",
  "Sokak adresi veya mahalle",
  "Şehir",
  "Önerilen bir şehri seçin veya manuel olarak girin.",
  "Bir şehir girin veya seçin",
  "Ülke",
  "Eyalet / bölge",
  "Resimleri listeleme",
  "Wix Media Manager arasından görsel seçin; ilk resim kapaktır.",
  "İlk görsel kartlarda ve özellik sayfasında kapak olarak kullanılır.",
  "Resimleri seçin",
  "Resim ekle",
  "Henüz resim seçilmedi.",
  "{n} resmini kaldır",
  "360° sanal tur",
  "Etkileşimli Three.js görüntüleyici için eşit dikdörtgen 360° fotoğraflar ekleyin. Ziyaretçiler odalar ve bakış açıları arasında geçiş yapabilir.",
  " Sanal turlar Pro ve Business'e dahildir; Şimdi eklerseniz fazladan resimler kontrol panelinde kalır.",
  " Pro siteleri ilk sahneyi gösteriyor; ek sahneler Business'de yayınlanıyor.",
  "360° panorama görüntüleri",
  "Etkileşimli Three.js görüntüleyici için eşit dikdörtgen 360° görüntüleri seçin. Ziyaretçiler sahneler arasında geçiş yapabilir.",
  "İsteğe bağlı. Her görsel eşdikdörtgensel bir 360° fotoğraf olmalıdır.",
  "360° panorama seçilmedi.",
  "Panoramayı kaldır {n}",
  "Sahne {n}",
  "Gerçekleri listeleme",
  "Bu alanlar filtreleri ve portföy analitiğini güçlendirir.",
  "İşlem türü",
  "Gayrimenkulün satılık mı, kiralık mı yoksa kiralık mı olduğu.",
  "Mülkü en iyi tanımlayan kategori.",
  "Bu liste için mevcut iş akışı aşaması.",
  "Promülk durumu",
  "Gayrimenkulün mevcut fiziki durumu.",
  "Mobilya durumu",
  "Mülkün mobilyasız, kısmen mobilyalı veya mobilyalı olup olmadığı.",
  "Görev süresi",
  "Mülkün mülkiyeti veya kira sözleşmesi.",
  "Kiralama sıklığı",
  "Kiralık veya kiralık ilanlar için ne sıklıkta kira bekleniyor.",
  "Fiyat",
  "Seçilen para birimindeki liste fiyatı.",
  "Para birimi",
  "Liste fiyatı için kullanılan üç harfli para birimi.",
  "Alan",
  "Seçilen alan birimindeki mülk boyutu.",
  "Alan birimi",
  "Olanaklar",
  "Önemli özellikleri virgülle ayırarak listeleyin.",
  "Yüzme havuzu, spor salonu, 7/24 güvenlik",
  "Kullanılabilirlik tarihi",
  "Mülkün kullanılabilir hale geldiği tarih.",
  "Temsilci / sahip iletişim kişisi",
  "İsim",
  "Bu listeden sorumlu temsilci veya sahip.",
  "Temsilci veya sahibin adı",
  "Telefon",
  "Listeleme sorguları için bir telefon numarası.",
  "Uluslararası telefon numarası",
  "E-posta",
  "Listeleme sorguları için bir e-posta adresi.",
  "Harita yerleşimi",
  "Enlem",
  "Harita yerleştirme için kullanılan mülk enlemi.",
  "Boylam",
  "Harita yerleştirme için kullanılan mülk boylamı.",
  "İlanı kaydet",
  "Kaydediliyor…",
  "AI writer",
  "Bu listedeki gerçekler sizin için doldurulmuştur. Yazma bittiğinde formdaki açıklama otomatik olarak güncellenir.",
  "İlan açıklaması güncellendi.",
  "Media Manager açılamadı.",
  "{label}'u seçin",
  "Bu liste için isteğe bağlı {label} değeri.",
  "İsteğe bağlı",
  "Yatak odaları",
  "Banyolar",
  "Yapım yılı",
  "Park alanları",
  "Servis ücreti",
  "Güvenlik depozitosu",
  "Gerekli",
  "Bir başlık ekleyin.",
  "Bir adres ekleyin.",
  "Bir şehir ekleyin.",
  "Bir fiyat ekleyin.",
  "Bir alan ekleyin.",
  "Kaydetmeden önce vurgulanan alanları düzeltin.",
  "Konum önerileri yüklenemedi. Hala değerleri yazabilirsiniz.",
  "Proözelliğin temelleri",
  "Açıklamada ne söylenmeli?",
  "Konum",
  "Austin, Teksas",
  "875.000$",
  "Yüzme havuzu, spor salonu, otopark",
  "Yazma stili",
  "Açıklama oluştur",
  "Açıklamanızı yazıyoruz…",
  "Oluşturulan açıklama",
  "Yazma bittiğinde bu kopya liste açıklamasına eklenir.",
  "Kopyayı inceleyin ve ardından girişinize kopyalayın.",
  "Kopyala",
  "Kopyalandı",
  "Oluşturulan özellik açıklaması",
  "Gösterişli kopyanız burada görünecek",
  "Bir stil seçin ve onaylanmış özellik bilgilerinden bir açıklama oluşturun.",
  "Proprofesyonel",
  "Açık ve güvenilir",
  "Lüks",
  "Yüksek ve istekli",
  "Kısa",
  "Kartlar için mükemmel",
  "SEO optimize edilmiş",
  "Arama dostu kopya",
  "Sosyal medya",
  "İlgi çekici ve paylaşılabilir",
  "Mobilyalı",
  "Yarı mobilyalı",
  "Mobilyasız",
  "Açıklama oluşturulamadı.",
  "AI Listing Writer, Pro ve Business'de mevcuttur.",
  "İlanınızın kopyasını paylaşın",
  "Alıcılara vakit geçirdikleri her yerde ulaşın.",
  "Kanal ekle",
  "Daha fazla paylaşım kanalı",
  "Oluşturulan listeleme kopyasını paylaşmak için bir platform seçin. Bazı kanallar, fotoğraf ekleyebilmeniz ve doğal bir şekilde yayınlayabilmeniz için önce başlığı kopyalar.",
  "WhatsApp",
  "Bir kişiye veya gruba gönderme",
  "Facebook",
  "Feed'inizde paylaşın",
  "Instagram",
  "Başlığı kopyalayın ve Instagram açın",
  "X",
  "Zaman çizelgenizde yayınlayın",
  "LinkedIn",
  "Ağınızla paylaşın",
  "Telegram",
  "Bir sohbete veya kanala gönderin",
  "Pinterest",
  "Başlığı kopyalayın ve Pinterest'yi açın",
  "Reddit",
  "Bir topluluğa gönder",
  "Threads",
  "Başlığı kopyalayın ve Threads dosyasını açın",
  "TikTok",
  "Başlığı kopyalayın ve TikTok dosyasını açın",
  "YouTube",
  "Başlığı kopyalayın ve YouTube'yi açın",
  "Snapchat",
  "Başlığı kopyalayın ve Snapchat'yi açın",
  "E-posta",
  "E-posta uygulamanızı açın",
  "Kısa mesaj",
  "Kısa mesaj olarak gönder",
  "Promülk listesi",
  "İlan açıklaması",
  "Bu mülkü sevmenin ışığını, düzenini, yüzeylerini ve nedenlerini açıklayın…",
  "Resimler açıklamaya eklenemedi.",
  "Açıklamaya videolar eklenemedi.",
  "Taslak",
  "Aktif",
  "Teklif altında",
  "Satıldı",
  "Arşivlendi",
  "satılık",
  "Kiralık",
  "kiralık",
  "ev",
  "Daire",
  "apartman dairesi",
  "Şehir evi",
  "Arsa",
  "Ofis",
  "Perakende",
  "Endüstriyel",
  "Karma kullanım",
  "Diğer",
  "Metrekare",
  "Metrekare",
  "Dönüm",
  "Yeni",
  "İyi",
  "Yenileme ihtiyacı var",
  "Mülkiyet",
  "Özel mülk",
  "Aylık",
  "Yıllık",
  "Metrekare",
  "Dönüm",
  "Yeni",
  "İyi",
  "Yenileme ihtiyacı var",
  "Mülkiyet",
  "Özel mülk",
  "Aylık",
  "Yıllık",
  "English",
  "中文",
  "हिन्दी",
  "Español",
  "العربية",
  "Français",
  "বাংলা",
  "Português",
  "Русский",
  "اردو",
  "Bahasa Indonesia",
  "Deutsch",
  "日本語",
  "Kiswahili",
  "Türkçe",
  "한국어",
  "Tiếng Việt",
  "Italiano",
  "ไทย",
  "Polski",
]);
