import React, { useCallback, useEffect, useMemo, useState, type FC, type ReactNode } from "react";
import { inputs, widget } from "@wix/editor";
import { Accordion, accordionItemBuilder, Box, Button, Dropdown, FillPreview, FormField, Input, listItemSelectBuilder, SidePanel, Slider, Text, ToggleSwitch, WixDesignSystemProvider } from "@wix/design-system";
import "@wix/design-system/styles.global.css";

import { DEFAULT_DETAIL_WIDGET_CONFIG, DEFAULT_LISTING_WIDGET_CONFIG, fontFamilyFromShorthand, parseWidgetJson, type DetailWidgetConfig, type ListingWidgetConfig, type WidgetFont, type WidgetSpacing } from "../../../lib/site-widget";

type PanelConfig = ListingWidgetConfig | DetailWidgetConfig;
type PanelKind = "listings" | "detail";
interface WidgetPanelProps { kind: PanelKind; }

function parseFont(value: unknown, fallback: WidgetFont): WidgetFont {
  if (typeof value === "object" && value !== null && "font" in value && typeof value.font === "string") return { font: value.font, textDecoration: "textDecoration" in value && typeof value.textDecoration === "string" ? value.textDecoration : undefined };
  return fallback;
}

function Field({ label, children }: { label: string; children: ReactNode }) { return <FormField label={label} labelSize="small" labelPlacement="top">{children}</FormField>; }
function TextField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <Field label={label}><Input size="small" value={value} onChange={(event) => onChange(event.target.value)} /></Field>; }
function ToggleField({ label, checked, onChange }: { label: string; checked: boolean; onChange: (value: boolean) => void }) { return <Box align="space-between" verticalAlign="middle" gap="SP2"><Text size="small">{label}</Text><ToggleSwitch size="small" checked={checked} onChange={(event) => onChange(event.target.checked)} /></Box>; }
function SelectField({ label, value, options, onChange }: { label: string; value: string; options: Array<{ id: string; label: string }>; onChange: (value: string) => void }) { const dropdownOptions = options.map((option) => listItemSelectBuilder({ id: option.id, title: option.label, label: option.label })); return <Field label={label}><Dropdown size="small" selectedId={value} options={dropdownOptions} valueParser={(option) => option.label} onSelect={(option) => onChange(String(option.id))} /></Field>; }
function RangeField({ label, value, min, max, step, onChange }: { label: string; value: number; min: number; max: number; step: number; onChange: (value: number) => void }) { return <Field label={`${label}: ${value}px`}><Slider value={[value]} min={min} max={max} step={step} onChange={(next) => onChange(Array.isArray(next) ? next[0] ?? value : next)} /></Field>; }
function ColorField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <Box align="space-between" verticalAlign="middle" gap="SP2"><Text size="small">{label}</Text><FillPreview size="small" aspectRatio={1} fill={value} onClick={() => { void inputs.selectColor(value, { onChange: (next) => { if (next) onChange(next); } }); }} /></Box>; }
function FontField({ label, value, onChange }: { label: string; value: WidgetFont; onChange: (value: WidgetFont) => void }) { return <Field label={label}><Box direction="vertical" gap="SP1"><Button size="small" priority="secondary" fullWidth onClick={() => { void inputs.selectFont({ font: value.font, textDecoration: value.textDecoration ?? "" }, { onChange: (next) => { if (next?.font) onChange({ font: next.font, textDecoration: next.textDecoration ?? "" }); } }); }}>Choose font</Button><Text size="tiny" secondary ellipsis>{value.font}</Text></Box></Field>; }
function SpacingFields({ label, value, onChange }: { label: string; value: WidgetSpacing; onChange: (side: keyof WidgetSpacing, value: number) => void }) { return <Box direction="vertical" gap="SP2"><Text size="small" weight="bold">{label}</Text><Box direction="vertical" gap="SP2"><Box gap="SP2"><RangeField label="Top" value={value.top} min={0} max={160} step={1} onChange={(next) => onChange("top", next)} /><RangeField label="Right" value={value.right} min={0} max={160} step={1} onChange={(next) => onChange("right", next)} /></Box><Box gap="SP2"><RangeField label="Bottom" value={value.bottom} min={0} max={160} step={1} onChange={(next) => onChange("bottom", next)} /><RangeField label="Left" value={value.left} min={0} max={160} step={1} onChange={(next) => onChange("left", next)} /></Box></Box></Box>; }

export const WidgetPanel: FC<WidgetPanelProps> = ({ kind }) => {
  const defaults = useMemo(() => kind === "listings" ? DEFAULT_LISTING_WIDGET_CONFIG : DEFAULT_DETAIL_WIDGET_CONFIG, [kind]);
  const [config, setConfig] = useState<PanelConfig>(defaults);
  const [loaded, setLoaded] = useState(false);
  useEffect(() => { void widget.getProp("config").then((value) => { setConfig(parseWidgetJson(value, defaults)); setLoaded(true); }).catch((error: unknown) => { console.error("Unable to load widget settings.", error); setLoaded(true); }); }, [defaults]);
  const update = useCallback((key: string, value: unknown) => { setConfig((current) => { const next = { ...current, [key]: value } as PanelConfig; void widget.setProp("config", JSON.stringify(next)).catch((error: unknown) => console.error("Unable to save widget setting.", error)); return next; }); }, []);
  const updateSpacing = useCallback((key: "containerMargin" | "containerPadding", side: keyof WidgetSpacing, value: number) => { setConfig((current) => { const next = { ...current, [key]: { ...current[key], [side]: value } } as PanelConfig; void widget.setProp("config", JSON.stringify(next)).catch((error: unknown) => console.error("Unable to save widget spacing.", error)); return next; }); }, []);
  const updateFont = useCallback((key: "titleFont" | "bodyFont", font: WidgetFont) => { update(key, font); const otherFont = key === "titleFont" ? config.bodyFont.font : config.titleFont.font; const fonts = [fontFamilyFromShorthand(font.font), fontFamilyFromShorthand(otherFont)].filter((value, index, values) => Boolean(value) && values.indexOf(value) === index); void widget.setPreloadFonts(fonts).catch((error: unknown) => console.error("Unable to preload widget font.", error)); }, [config.bodyFont.font, config.titleFont.font, update]);
  if (!loaded) return <WixDesignSystemProvider><SidePanel width="320" height="100vh"><SidePanel.Content><Box padding="SP4"><Text size="small">Loading settings…</Text></Box></SidePanel.Content></SidePanel></WixDesignSystemProvider>;

  const isListings = kind === "listings";
  const listingConfig = isListings ? config as ListingWidgetConfig : null;
  const detailConfig = isListings ? null : config as DetailWidgetConfig;
  const layoutOptions = [{ id: "grid", label: "Grid" }, { id: "carousel", label: "Carousel" }];
  const ratioOptions = [{ id: "landscape", label: "Landscape" }, { id: "square", label: "Square" }, { id: "portrait", label: "Portrait" }];
  const shadowOptions = [{ id: "none", label: "None" }, { id: "soft", label: "Soft" }, { id: "strong", label: "Strong" }];
  const items = [
    accordionItemBuilder({ title: "Content", initiallyOpen: true, children: <Box direction="vertical" gap="SP4">{listingConfig ? <><TextField label="Heading" value={listingConfig.title} onChange={(value) => update("title", value)} /><TextField label="Subheading" value={listingConfig.subtitle} onChange={(value) => update("subtitle", value)} /><ToggleField label="Show header" checked={listingConfig.showHeader} onChange={(value) => update("showHeader", value)} /><ToggleField label="Show location" checked={listingConfig.showLocation} onChange={(value) => update("showLocation", value)} /><ToggleField label="Show price" checked={listingConfig.showPrice} onChange={(value) => update("showPrice", value)} /><ToggleField label="Show status" checked={listingConfig.showStatus} onChange={(value) => update("showStatus", value)} /><ToggleField label="Show metadata" checked={listingConfig.showMetadata} onChange={(value) => update("showMetadata", value)} /></> : <><ToggleField label="Show location" checked={detailConfig?.showLocation ?? true} onChange={(value) => update("showLocation", value)} /><ToggleField label="Show description" checked={detailConfig?.showDescription ?? true} onChange={(value) => update("showDescription", value)} /><ToggleField label="Show amenities" checked={detailConfig?.showAmenities ?? true} onChange={(value) => update("showAmenities", value)} /><ToggleField label="Show agent" checked={detailConfig?.showAgent ?? true} onChange={(value) => update("showAgent", value)} /><ToggleField label="Show view count" checked={detailConfig?.showViewCount ?? true} onChange={(value) => update("showViewCount", value)} /></>}</Box> }),
    accordionItemBuilder({ title: "Layout and images", children: <Box direction="vertical" gap="SP4">{listingConfig ? <><SelectField label="Property presentation" value={listingConfig.layout} options={layoutOptions} onChange={(value) => update("layout", value)} /><RangeField label="Columns" value={listingConfig.columns} min={1} max={4} step={1} onChange={(value) => update("columns", value)} /><TextField label="Detail page path" value={listingConfig.detailPagePath} onChange={(value) => update("detailPagePath", value)} /></> : null}<SelectField label="Image ratio" value={config.imageRatio} options={ratioOptions} onChange={(value) => update("imageRatio", value)} /><ToggleField label="Show image arrows" checked={config.showImageControls} onChange={(value) => update("showImageControls", value)} /><ToggleField label="Show image dots" checked={config.showImageDots} onChange={(value) => update("showImageDots", value)} /></Box> }),
    accordionItemBuilder({ title: "Typography", children: <Box direction="vertical" gap="SP4"><FontField label="Title font" value={parseFont(config.titleFont, defaults.titleFont)} onChange={(value) => updateFont("titleFont", value)} /><FontField label="Body font" value={parseFont(config.bodyFont, defaults.bodyFont)} onChange={(value) => updateFont("bodyFont", value)} /></Box> }),
    accordionItemBuilder({ title: "Colors", children: <Box direction="vertical" gap="SP4"><ColorField label="Background" value={config.backgroundColor} onChange={(value) => update("backgroundColor", value)} /><ColorField label="Card" value={config.cardColor} onChange={(value) => update("cardColor", value)} /><ColorField label="Text" value={config.textColor} onChange={(value) => update("textColor", value)} /><ColorField label="Muted text" value={config.mutedColor} onChange={(value) => update("mutedColor", value)} /><ColorField label="Accent" value={config.accentColor} onChange={(value) => update("accentColor", value)} /><ColorField label="Border" value={config.cardBorderColor} onChange={(value) => update("cardBorderColor", value)} /></Box> }),
    accordionItemBuilder({ title: "Spacing and surfaces", children: <Box direction="vertical" gap="SP4"><SpacingFields label="Parent margin" value={config.containerMargin} onChange={(side, value) => updateSpacing("containerMargin", side, value)} /><SpacingFields label="Parent padding" value={config.containerPadding} onChange={(side, value) => updateSpacing("containerPadding", side, value)} /><RangeField label="Card radius" value={config.cardRadius} min={0} max={40} step={1} onChange={(value) => update("cardRadius", value)} /><RangeField label="Border width" value={config.cardBorderWidth} min={0} max={4} step={1} onChange={(value) => update("cardBorderWidth", value)} /><SelectField label="Card shadow" value={config.cardShadow} options={shadowOptions} onChange={(value) => update("cardShadow", value)} />{listingConfig ? <RangeField label="Grid gap" value={listingConfig.gap} min={0} max={48} step={4} onChange={(value) => update("gap", value)} /> : null}</Box> }),
    ...(detailConfig ? [accordionItemBuilder({ title: "Amenities", children: <Box direction="vertical" gap="SP4"><ColorField label="Amenity text" value={detailConfig.amenitiesTextColor} onChange={(value) => update("amenitiesTextColor", value)} /><ColorField label="Amenity background" value={detailConfig.amenitiesBackgroundColor} onChange={(value) => update("amenitiesBackgroundColor", value)} /></Box> })] : []),
  ];
  return <WixDesignSystemProvider><SidePanel width="320" height="100vh" hideOverflow={false}><SidePanel.Content noPadding stretchVertically><Box height="100%" overflow="auto" padding="SP4" direction="vertical" gap="SP4"><Text size="small" secondary>Customize the property widget.</Text><Accordion skin="light" hideShadow size="small" multiple items={items} /></Box></SidePanel.Content></SidePanel></WixDesignSystemProvider>;
};
