export const FIELD_HELP = {
  "Language": "Choose the language for built-in widget labels and messages. Custom headings keep the text you enter.",
  "Heading": "Set the main heading above the property listings.",
  "Subheading": "Set the supporting text below the listings heading.",
  "Show header": "Display the listings heading and subheading.",
  "Show location": "Display the property location.",
  "Show price": "Display the price on each property card.",
  "Show status": "Display the property status, such as available or sold.",
  "Show metadata": "Display property facts such as bedrooms, bathrooms, and area.",
  "Show description": "Display the full property description.",
  "Show amenities": "Display the property amenities.",
  "Show agent": "Display the agent information and contact options.",
  "Show view count": "Display how many times the property has been viewed.",
  "Show AI assistant": "Display the assistant visitors can ask about this property.",
  "Show social share": "Display options for sharing the property.",
  "Related listings heading": "Set the heading above the related property cards.",
  "Related listings subheading": "Set the supporting text below the related listings heading.",
  "Show related listings": "Display additional property cards below the property details.",
  "Related location": "Display the location on related property cards.",
  "Related price": "Display the price on related property cards.",
  "Related status": "Display the status on related property cards.",
  "Related metadata": "Display bedrooms, bathrooms, and area on related property cards.",
  "Show search": "Let visitors search the property listings.",
  "Show transaction filter": "Let visitors filter properties by transaction type, such as sale or rent.",
  "Show property type filter": "Let visitors filter by property type, such as apartment or house.",
  "Show price slider": "Let visitors select a minimum and maximum price.",
  "Show bedroom filter": "Let visitors filter properties by bedroom count.",
  "Filter background": "Choose the background color for the search and filter controls.",
  "Filter border": "Choose the border color for the search and filter area.",
  "Filter text": "Choose the text color for the search and filter controls.",
  "Filter radius": "Set the corner rounding of the filter area in pixels.",
  "Property presentation": "Choose a grid of cards or a horizontally scrolling carousel.",
  "Listings per row": "Set how many property cards appear side by side on wide screens.",
  "Tablet listings per row": "Set the number of cards per row in tablet-sized widget containers. This cannot exceed the desktop count.",
  "Mobile listings per row": "Set the number of cards per row in narrow widget containers. This cannot exceed the tablet count.",
  "Image ratio": "Choose landscape (16:10), square (1:1), or portrait (4:5) property images.",
  "Show image arrows": "Display previous and next arrows when a property has multiple images.",
  "Show image dots": "Display indicators for the current image when a property has multiple images.",
  "Loading behavior": "Choose a load more button, automatic loading as visitors scroll, or numbered pages.",
  "Listings per page": "Set how many properties load per page or batch, from 1 to 50.",
  "Load more label": "Set the button text used with the load more loading behavior.",
  "Previous label": "Set the previous-page button text for numbered pagination.",
  "Next label": "Set the next-page button text for numbered pagination.",
  "Control alignment": "Align the paging controls to the left, center, or right.",
  "Control spacing": "Set the space above the paging controls in pixels.",
  "Control radius": "Set the corner rounding of paging buttons in pixels.",
  "Show pagination icons": "Display arrow icons on the paging buttons.",
  "Control background": "Choose the background color of paging buttons.",
  "Control text": "Choose the text color of paging buttons.",
  "Control border": "Choose the border color of paging buttons.",
  "Title font": "Choose the font and text styling for widget headings and property titles.",
  "Body font": "Choose the font and text styling for the widget body text.",
  "Background": "Choose the background color of the widget.",
  "Card": "Choose the background color of property cards and content surfaces.",
  "Text": "Choose the primary text color.",
  "Muted text": "Choose the color for secondary text, such as locations and property facts.",
  "Accent": "Choose the highlight color used for links and emphasized controls.",
  "Border": "Choose the border color of cards and content surfaces.",
  "Parent margin": "Set the space outside the widget on each side, in pixels.",
  "Parent padding": "Set the space between the widget edges and its content, in pixels.",
  "Top": "Set the space on the top side in pixels.",
  "Right": "Set the space on the right side in pixels.",
  "Bottom": "Set the space on the bottom side in pixels.",
  "Left": "Set the space on the left side in pixels.",
  "Card radius": "Set the corner rounding of cards and content surfaces in pixels.",
  "Border width": "Set the thickness of card borders in pixels. Use 0 to hide them.",
  "Card shadow": "Choose no shadow, a soft shadow, or a strong shadow for cards.",
  "Grid gap": "Set the space between property cards in pixels.",
  "Amenity text": "Choose the text color of amenity labels.",
  "Amenity background": "Choose the background color of amenity labels.",
  "Facebook": "Choose the color of the Facebook sharing control.",
  "Instagram": "Choose the color of the Instagram sharing control.",
  "WhatsApp": "Choose the color of the WhatsApp sharing control.",
  "X": "Choose the color of the X sharing control.",
  "LinkedIn": "Choose the color of the LinkedIn sharing control.",
  "Number of cards": "Set how many related property cards to display, from 1 to 8.",
  "Card gap": "Set the space between related property cards in pixels."
} as const;

export type PanelFieldLabel = keyof typeof FIELD_HELP;
